{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/analytics": {},
                "https://www.googleapis.com/auth/analytics.edit": {},
                "https://www.googleapis.com/auth/analytics.manage.users": {},
                "https://www.googleapis.com/auth/analytics.manage.users.readonly": {},
                "https://www.googleapis.com/auth/analytics.provision": {},
                "https://www.googleapis.com/auth/analytics.readonly": {},
                "https://www.googleapis.com/auth/analytics.user.deletion": {}
            }
        }
    },
    "basePath": "/analytics/v3/",
    "baseUrl": "https://www.googleapis.com/analytics/v3/",
    "batchPath": "batch/analytics/v3",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/analytics/",
    "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/vI7LuHOBzgmLwBVRLzfesqzKeIc\"",
    "id": "analytics:v3",
    "kind": "discovery#restDescription",
    "name": "analytics",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "data": {
            "resources": {
                "ga": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.data.ga.get",
                            "path": "data/ga",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "mcf": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.data.mcf.get",
                            "path": "data/mcf",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "realtime": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.data.realtime.get",
                            "path": "data/realtime",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "management": {
            "resources": {
                "accountSummaries": {
                    "methods": {
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.accountSummaries.list",
                            "path": "management/accountSummaries",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "accountUserLinks": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.accountUserLinks.delete",
                            "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.accountUserLinks.insert",
                            "path": "management/accounts/{accountId}/entityUserLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.accountUserLinks.list",
                            "path": "management/accounts/{accountId}/entityUserLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users",
                                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.accountUserLinks.update",
                            "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        }
                    }
                },
                "accounts": {
                    "methods": {
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.accounts.list",
                            "path": "management/accounts",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "clientId": {
                    "methods": {
                        "hashClientId": {
                            "httpMethod": "POST",
                            "id": "analytics.management.clientId.hashClientId",
                            "path": "management/clientId:hashClientId",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "customDataSources": {
                    "methods": {
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.customDataSources.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "customDimensions": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.customDimensions.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.customDimensions.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.customDimensions.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.customDimensions.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.customDimensions.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "customMetrics": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.customMetrics.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.customMetrics.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.customMetrics.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.customMetrics.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.customMetrics.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "experiments": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.experiments.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.experiments.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.experiments.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.experiments.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.experiments.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.experiments.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "filters": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.filters.delete",
                            "path": "management/accounts/{accountId}/filters/{filterId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.filters.get",
                            "path": "management/accounts/{accountId}/filters/{filterId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.filters.insert",
                            "path": "management/accounts/{accountId}/filters",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.filters.list",
                            "path": "management/accounts/{accountId}/filters",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.filters.patch",
                            "path": "management/accounts/{accountId}/filters/{filterId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.filters.update",
                            "path": "management/accounts/{accountId}/filters/{filterId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "goals": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.goals.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.goals.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.goals.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.goals.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.goals.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "profileFilterLinks": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.profileFilterLinks.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.profileFilterLinks.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.profileFilterLinks.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.profileFilterLinks.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.profileFilterLinks.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.profileFilterLinks.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "profileUserLinks": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.profileUserLinks.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.profileUserLinks.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.profileUserLinks.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users",
                                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.profileUserLinks.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        }
                    }
                },
                "profiles": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.profiles.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.profiles.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.profiles.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.profiles.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.profiles.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.profiles.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "remarketingAudience": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.remarketingAudience.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.remarketingAudience.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.remarketingAudience.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.remarketingAudience.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.remarketingAudience.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.remarketingAudience.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "segments": {
                    "methods": {
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.segments.list",
                            "path": "management/segments",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "unsampledReports": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.unsampledReports.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.unsampledReports.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.unsampledReports.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.unsampledReports.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                },
                "uploads": {
                    "methods": {
                        "deleteUploadData": {
                            "httpMethod": "POST",
                            "id": "analytics.management.uploads.deleteUploadData",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.uploads.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.uploads.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "uploadData": {
                            "httpMethod": "POST",
                            "id": "analytics.management.uploads.uploadData",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit"
                            ],
                            "supportsMediaUpload": true
                        }
                    }
                },
                "webPropertyAdWordsLinks": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.webPropertyAdWordsLinks.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.webPropertyAdWordsLinks.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.webPropertyAdWordsLinks.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.webPropertyAdWordsLinks.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.webPropertyAdWordsLinks.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.webPropertyAdWordsLinks.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "webproperties": {
                    "methods": {
                        "get": {
                            "httpMethod": "GET",
                            "id": "analytics.management.webproperties.get",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.webproperties.insert",
                            "path": "management/accounts/{accountId}/webproperties",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.webproperties.list",
                            "path": "management/accounts/{accountId}/webproperties",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        },
                        "patch": {
                            "httpMethod": "PATCH",
                            "id": "analytics.management.webproperties.patch",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.webproperties.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.edit"
                            ]
                        }
                    }
                },
                "webpropertyUserLinks": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "analytics.management.webpropertyUserLinks.delete",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "analytics.management.webpropertyUserLinks.insert",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.management.webpropertyUserLinks.list",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users",
                                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
                            ]
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "id": "analytics.management.webpropertyUserLinks.update",
                            "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.manage.users"
                            ]
                        }
                    }
                }
            }
        },
        "metadata": {
            "resources": {
                "columns": {
                    "methods": {
                        "list": {
                            "httpMethod": "GET",
                            "id": "analytics.metadata.columns.list",
                            "path": "metadata/{reportType}/columns",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics",
                                "https://www.googleapis.com/auth/analytics.edit",
                                "https://www.googleapis.com/auth/analytics.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "provisioning": {
            "methods": {
                "createAccountTicket": {
                    "httpMethod": "POST",
                    "id": "analytics.provisioning.createAccountTicket",
                    "path": "provisioning/createAccountTicket",
                    "scopes": [
                        "https://www.googleapis.com/auth/analytics.provision"
                    ]
                },
                "createAccountTree": {
                    "httpMethod": "POST",
                    "id": "analytics.provisioning.createAccountTree",
                    "path": "provisioning/createAccountTree",
                    "scopes": [
                        "https://www.googleapis.com/auth/analytics.provision"
                    ]
                }
            }
        },
        "userDeletion": {
            "resources": {
                "userDeletionRequest": {
                    "methods": {
                        "upsert": {
                            "httpMethod": "POST",
                            "id": "analytics.userDeletion.userDeletionRequest.upsert",
                            "path": "userDeletion/userDeletionRequests:upsert",
                            "scopes": [
                                "https://www.googleapis.com/auth/analytics.user.deletion"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "analytics/v3/",
    "title": "Google Analytics API",
    "version": "v3"
}