{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/bigtable.admin": {},
                "https://www.googleapis.com/auth/bigtable.admin.cluster": {},
                "https://www.googleapis.com/auth/bigtable.admin.instance": {},
                "https://www.googleapis.com/auth/bigtable.admin.table": {},
                "https://www.googleapis.com/auth/cloud-bigtable.admin": {},
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {},
                "https://www.googleapis.com/auth/cloud-bigtable.admin.table": {},
                "https://www.googleapis.com/auth/cloud-platform": {},
                "https://www.googleapis.com/auth/cloud-platform.read-only": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://bigtableadmin.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Bigtable Admin",
    "discoveryVersion": "v1",
    "documentationLink": "https://cloud.google.com/bigtable/",
    "fullyEncodeReservedExpansion": true,
    "id": "bigtableadmin:v2",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://bigtableadmin.mtls.googleapis.com/",
    "name": "bigtableadmin",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "operations": {
            "methods": {
                "cancel": {
                    "flatPath": "v2/operations/{operationsId}:cancel",
                    "httpMethod": "POST",
                    "id": "bigtableadmin.operations.cancel",
                    "path": "v2/{+name}:cancel",
                    "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "delete": {
                    "flatPath": "v2/operations/{operationsId}",
                    "httpMethod": "DELETE",
                    "id": "bigtableadmin.operations.delete",
                    "path": "v2/{+name}",
                    "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "get": {
                    "flatPath": "v2/operations/{operationsId}",
                    "httpMethod": "GET",
                    "id": "bigtableadmin.operations.get",
                    "path": "v2/{+name}",
                    "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                    ]
                }
            },
            "resources": {
                "projects": {
                    "resources": {
                        "operations": {
                            "methods": {
                                "list": {
                                    "flatPath": "v2/operations/projects/{projectsId}/operations",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.operations.projects.operations.list",
                                    "path": "v2/{+name}/operations",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "projects": {
            "resources": {
                "instances": {
                    "methods": {
                        "create": {
                            "flatPath": "v2/projects/{projectsId}/instances",
                            "httpMethod": "POST",
                            "id": "bigtableadmin.projects.instances.create",
                            "path": "v2/{+parent}/instances",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "delete": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "DELETE",
                            "id": "bigtableadmin.projects.instances.delete",
                            "path": "v2/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "get": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "GET",
                            "id": "bigtableadmin.projects.instances.get",
                            "path": "v2/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only"
                            ]
                        },
                        "getIamPolicy": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
                            "httpMethod": "POST",
                            "id": "bigtableadmin.projects.instances.getIamPolicy",
                            "path": "v2/{+resource}:getIamPolicy",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "list": {
                            "flatPath": "v2/projects/{projectsId}/instances",
                            "httpMethod": "GET",
                            "id": "bigtableadmin.projects.instances.list",
                            "path": "v2/{+parent}/instances",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only"
                            ]
                        },
                        "partialUpdateInstance": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "PATCH",
                            "id": "bigtableadmin.projects.instances.partialUpdateInstance",
                            "path": "v2/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "setIamPolicy": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
                            "httpMethod": "POST",
                            "id": "bigtableadmin.projects.instances.setIamPolicy",
                            "path": "v2/{+resource}:setIamPolicy",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "testIamPermissions": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
                            "httpMethod": "POST",
                            "id": "bigtableadmin.projects.instances.testIamPermissions",
                            "path": "v2/{+resource}:testIamPermissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "update": {
                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "PUT",
                            "id": "bigtableadmin.projects.instances.update",
                            "path": "v2/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        }
                    },
                    "resources": {
                        "appProfiles": {
                            "methods": {
                                "create": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.appProfiles.create",
                                    "path": "v2/{+parent}/appProfiles",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                                    "httpMethod": "DELETE",
                                    "id": "bigtableadmin.projects.instances.appProfiles.delete",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.projects.instances.appProfiles.get",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.projects.instances.appProfiles.list",
                                    "path": "v2/{+parent}/appProfiles",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "patch": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                                    "httpMethod": "PATCH",
                                    "id": "bigtableadmin.projects.instances.appProfiles.patch",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                }
                            }
                        },
                        "clusters": {
                            "methods": {
                                "create": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.clusters.create",
                                    "path": "v2/{+parent}/clusters",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                                    "httpMethod": "DELETE",
                                    "id": "bigtableadmin.projects.instances.clusters.delete",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.projects.instances.clusters.get",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.projects.instances.clusters.list",
                                    "path": "v2/{+parent}/clusters",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                                    ]
                                },
                                "update": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                                    "httpMethod": "PUT",
                                    "id": "bigtableadmin.projects.instances.clusters.update",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                }
                            },
                            "resources": {
                                "backups": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                                            "httpMethod": "POST",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.create",
                                            "path": "v2/{+parent}/backups",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                                            "httpMethod": "DELETE",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.delete",
                                            "path": "v2/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                                            "httpMethod": "GET",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.get",
                                            "path": "v2/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "getIamPolicy": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:getIamPolicy",
                                            "httpMethod": "POST",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.getIamPolicy",
                                            "path": "v2/{+resource}:getIamPolicy",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                                            "httpMethod": "GET",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.list",
                                            "path": "v2/{+parent}/backups",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "patch": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                                            "httpMethod": "PATCH",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.patch",
                                            "path": "v2/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "setIamPolicy": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:setIamPolicy",
                                            "httpMethod": "POST",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.setIamPolicy",
                                            "path": "v2/{+resource}:setIamPolicy",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        },
                                        "testIamPermissions": {
                                            "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:testIamPermissions",
                                            "httpMethod": "POST",
                                            "id": "bigtableadmin.projects.instances.clusters.backups.testIamPermissions",
                                            "path": "v2/{+resource}:testIamPermissions",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/bigtable.admin",
                                                "https://www.googleapis.com/auth/bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                                "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                                "https://www.googleapis.com/auth/cloud-platform"
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "tables": {
                            "methods": {
                                "checkConsistency": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:checkConsistency",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.checkConsistency",
                                    "path": "v2/{+name}:checkConsistency",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "create": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.create",
                                    "path": "v2/{+parent}/tables",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                                    "httpMethod": "DELETE",
                                    "id": "bigtableadmin.projects.instances.tables.delete",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "dropRowRange": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:dropRowRange",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.dropRowRange",
                                    "path": "v2/{+name}:dropRowRange",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "generateConsistencyToken": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:generateConsistencyToken",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.generateConsistencyToken",
                                    "path": "v2/{+name}:generateConsistencyToken",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.projects.instances.tables.get",
                                    "path": "v2/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                                    ]
                                },
                                "getIamPolicy": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:getIamPolicy",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.getIamPolicy",
                                    "path": "v2/{+resource}:getIamPolicy",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                                    "httpMethod": "GET",
                                    "id": "bigtableadmin.projects.instances.tables.list",
                                    "path": "v2/{+parent}/tables",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/cloud-platform.read-only"
                                    ]
                                },
                                "modifyColumnFamilies": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:modifyColumnFamilies",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.modifyColumnFamilies",
                                    "path": "v2/{+name}:modifyColumnFamilies",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "restore": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables:restore",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.restore",
                                    "path": "v2/{+parent}/tables:restore",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "setIamPolicy": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:setIamPolicy",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.setIamPolicy",
                                    "path": "v2/{+resource}:setIamPolicy",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                },
                                "testIamPermissions": {
                                    "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:testIamPermissions",
                                    "httpMethod": "POST",
                                    "id": "bigtableadmin.projects.instances.tables.testIamPermissions",
                                    "path": "v2/{+resource}:testIamPermissions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/bigtable.admin",
                                        "https://www.googleapis.com/auth/bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                                        "https://www.googleapis.com/auth/cloud-platform"
                                    ]
                                }
                            }
                        }
                    }
                },
                "locations": {
                    "methods": {
                        "get": {
                            "flatPath": "v2/projects/{projectsId}/locations/{locationsId}",
                            "httpMethod": "GET",
                            "id": "bigtableadmin.projects.locations.get",
                            "path": "v2/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only"
                            ]
                        },
                        "list": {
                            "flatPath": "v2/projects/{projectsId}/locations",
                            "httpMethod": "GET",
                            "id": "bigtableadmin.projects.locations.list",
                            "path": "v2/{+name}/locations",
                            "scopes": [
                                "https://www.googleapis.com/auth/bigtable.admin",
                                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/bigtable.admin.instance",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://bigtableadmin.googleapis.com/",
    "servicePath": "",
    "title": "Cloud Bigtable Admin API",
    "version": "v2",
    "version_module": true
}