{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/blogger": {},
                "https://www.googleapis.com/auth/blogger.readonly": {}
            }
        }
    },
    "basePath": "/blogger/v3/",
    "baseUrl": "https://www.googleapis.com/blogger/v3/",
    "batchPath": "batch/blogger/v3",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/blogger/docs/3.0/getting_started",
    "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/xSOfH1Tz95YnVhKU4FjuY2Lv4PE\"",
    "id": "blogger:v3",
    "kind": "discovery#restDescription",
    "labels": [
        "limited_availability"
    ],
    "name": "blogger",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "blogUserInfos": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.blogUserInfos.get",
                    "path": "users/{userId}/blogs/{blogId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "blogs": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.blogs.get",
                    "path": "blogs/{blogId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "getByUrl": {
                    "httpMethod": "GET",
                    "id": "blogger.blogs.getByUrl",
                    "path": "blogs/byurl",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "listByUser": {
                    "httpMethod": "GET",
                    "id": "blogger.blogs.listByUser",
                    "path": "users/{userId}/blogs",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "approve": {
                    "httpMethod": "POST",
                    "id": "blogger.comments.approve",
                    "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/approve",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "blogger.comments.delete",
                    "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.comments.get",
                    "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "blogger.comments.list",
                    "path": "blogs/{blogId}/posts/{postId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "listByBlog": {
                    "httpMethod": "GET",
                    "id": "blogger.comments.listByBlog",
                    "path": "blogs/{blogId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "markAsSpam": {
                    "httpMethod": "POST",
                    "id": "blogger.comments.markAsSpam",
                    "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/spam",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "removeContent": {
                    "httpMethod": "POST",
                    "id": "blogger.comments.removeContent",
                    "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                }
            }
        },
        "pageViews": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.pageViews.get",
                    "path": "blogs/{blogId}/pageviews",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                }
            }
        },
        "pages": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "blogger.pages.delete",
                    "path": "blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.pages.get",
                    "path": "blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "blogger.pages.insert",
                    "path": "blogs/{blogId}/pages",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "blogger.pages.list",
                    "path": "blogs/{blogId}/pages",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "blogger.pages.patch",
                    "path": "blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "publish": {
                    "httpMethod": "POST",
                    "id": "blogger.pages.publish",
                    "path": "blogs/{blogId}/pages/{pageId}/publish",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "revert": {
                    "httpMethod": "POST",
                    "id": "blogger.pages.revert",
                    "path": "blogs/{blogId}/pages/{pageId}/revert",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "blogger.pages.update",
                    "path": "blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                }
            }
        },
        "postUserInfos": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.postUserInfos.get",
                    "path": "users/{userId}/blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "blogger.postUserInfos.list",
                    "path": "users/{userId}/blogs/{blogId}/posts",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "posts": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "blogger.posts.delete",
                    "path": "blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.posts.get",
                    "path": "blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "getByPath": {
                    "httpMethod": "GET",
                    "id": "blogger.posts.getByPath",
                    "path": "blogs/{blogId}/posts/bypath",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "blogger.posts.insert",
                    "path": "blogs/{blogId}/posts",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "blogger.posts.list",
                    "path": "blogs/{blogId}/posts",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "blogger.posts.patch",
                    "path": "blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "publish": {
                    "httpMethod": "POST",
                    "id": "blogger.posts.publish",
                    "path": "blogs/{blogId}/posts/{postId}/publish",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "revert": {
                    "httpMethod": "POST",
                    "id": "blogger.posts.revert",
                    "path": "blogs/{blogId}/posts/{postId}/revert",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "search": {
                    "httpMethod": "GET",
                    "id": "blogger.posts.search",
                    "path": "blogs/{blogId}/posts/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "blogger.posts.update",
                    "path": "blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                }
            }
        },
        "users": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "blogger.users.get",
                    "path": "users/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "blogger/v3/",
    "title": "Blogger API",
    "version": "v3"
}