{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/calendar": {},
                "https://www.googleapis.com/auth/calendar.acls": {},
                "https://www.googleapis.com/auth/calendar.acls.readonly": {},
                "https://www.googleapis.com/auth/calendar.app.created": {},
                "https://www.googleapis.com/auth/calendar.calendarlist": {},
                "https://www.googleapis.com/auth/calendar.calendarlist.readonly": {},
                "https://www.googleapis.com/auth/calendar.calendars": {},
                "https://www.googleapis.com/auth/calendar.calendars.readonly": {},
                "https://www.googleapis.com/auth/calendar.events": {},
                "https://www.googleapis.com/auth/calendar.events.freebusy": {},
                "https://www.googleapis.com/auth/calendar.events.owned": {},
                "https://www.googleapis.com/auth/calendar.events.owned.readonly": {},
                "https://www.googleapis.com/auth/calendar.events.public.readonly": {},
                "https://www.googleapis.com/auth/calendar.events.readonly": {},
                "https://www.googleapis.com/auth/calendar.readonly": {},
                "https://www.googleapis.com/auth/calendar.settings.readonly": {}
            }
        }
    },
    "basePath": "/calendar/v3/",
    "baseUrl": "https://www.googleapis.com/calendar/v3/",
    "batchPath": "batch/calendar/v3",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/google-apps/calendar/firstapp",
    "id": "calendar:v3",
    "kind": "discovery#restDescription",
    "name": "calendar",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "acl": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "calendar.acl.delete",
                    "path": "calendars/{calendarId}/acl/{ruleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "calendar.acl.get",
                    "path": "calendars/{calendarId}/acl/{ruleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls",
                        "https://www.googleapis.com/auth/calendar.acls.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "calendar.acl.insert",
                    "path": "calendars/{calendarId}/acl",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "calendar.acl.list",
                    "path": "calendars/{calendarId}/acl",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls",
                        "https://www.googleapis.com/auth/calendar.acls.readonly"
                    ],
                    "supportsSubscription": true
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "calendar.acl.patch",
                    "path": "calendars/{calendarId}/acl/{ruleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "calendar.acl.update",
                    "path": "calendars/{calendarId}/acl/{ruleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls"
                    ]
                },
                "watch": {
                    "httpMethod": "POST",
                    "id": "calendar.acl.watch",
                    "path": "calendars/{calendarId}/acl/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls",
                        "https://www.googleapis.com/auth/calendar.acls.readonly"
                    ],
                    "supportsSubscription": true
                }
            }
        },
        "calendarList": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "calendar.calendarList.delete",
                    "path": "users/me/calendarList/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendarlist"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "calendar.calendarList.get",
                    "path": "users/me/calendarList/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendarlist",
                        "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "calendar.calendarList.insert",
                    "path": "users/me/calendarList",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.calendarlist"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "calendar.calendarList.list",
                    "path": "users/me/calendarList",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.calendarlist",
                        "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ],
                    "supportsSubscription": true
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "calendar.calendarList.patch",
                    "path": "users/me/calendarList/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendarlist"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "calendar.calendarList.update",
                    "path": "users/me/calendarList/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendarlist"
                    ]
                },
                "watch": {
                    "httpMethod": "POST",
                    "id": "calendar.calendarList.watch",
                    "path": "users/me/calendarList/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.calendarlist",
                        "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ],
                    "supportsSubscription": true
                }
            }
        },
        "calendars": {
            "methods": {
                "clear": {
                    "httpMethod": "POST",
                    "id": "calendar.calendars.clear",
                    "path": "calendars/{calendarId}/clear",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.calendars"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "calendar.calendars.delete",
                    "path": "calendars/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendars"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "calendar.calendars.get",
                    "path": "calendars/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendars",
                        "https://www.googleapis.com/auth/calendar.calendars.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "calendar.calendars.insert",
                    "path": "calendars",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.calendars"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "calendar.calendars.patch",
                    "path": "calendars/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendars"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "calendar.calendars.update",
                    "path": "calendars/{calendarId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendars"
                    ]
                }
            }
        },
        "channels": {
            "methods": {
                "stop": {
                    "httpMethod": "POST",
                    "id": "calendar.channels.stop",
                    "path": "channels/stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.acls",
                        "https://www.googleapis.com/auth/calendar.acls.readonly",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendarlist",
                        "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.events.owned",
                        "https://www.googleapis.com/auth/calendar.events.owned.readonly",
                        "https://www.googleapis.com/auth/calendar.events.public.readonly",
                        "https://www.googleapis.com/auth/calendar.events.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly",
                        "https://www.googleapis.com/auth/calendar.settings.readonly"
                    ]
                }
            }
        },
        "colors": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "calendar.colors.get",
                    "path": "colors",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.calendarlist",
                        "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.events.owned",
                        "https://www.googleapis.com/auth/calendar.events.owned.readonly",
                        "https://www.googleapis.com/auth/calendar.events.public.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ]
                }
            }
        },
        "events": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "calendar.events.delete",
                    "path": "calendars/{calendarId}/events/{eventId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "calendar.events.get",
                    "path": "calendars/{calendarId}/events/{eventId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.events.owned",
                        "https://www.googleapis.com/auth/calendar.events.owned.readonly",
                        "https://www.googleapis.com/auth/calendar.events.public.readonly",
                        "https://www.googleapis.com/auth/calendar.events.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ]
                },
                "import": {
                    "httpMethod": "POST",
                    "id": "calendar.events.import",
                    "path": "calendars/{calendarId}/events/import",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "calendar.events.insert",
                    "path": "calendars/{calendarId}/events",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "instances": {
                    "httpMethod": "GET",
                    "id": "calendar.events.instances",
                    "path": "calendars/{calendarId}/events/{eventId}/instances",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.events.owned",
                        "https://www.googleapis.com/auth/calendar.events.owned.readonly",
                        "https://www.googleapis.com/auth/calendar.events.public.readonly",
                        "https://www.googleapis.com/auth/calendar.events.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ],
                    "supportsSubscription": true
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "calendar.events.list",
                    "path": "calendars/{calendarId}/events",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.events.owned",
                        "https://www.googleapis.com/auth/calendar.events.owned.readonly",
                        "https://www.googleapis.com/auth/calendar.events.public.readonly",
                        "https://www.googleapis.com/auth/calendar.events.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ],
                    "supportsSubscription": true
                },
                "move": {
                    "httpMethod": "POST",
                    "id": "calendar.events.move",
                    "path": "calendars/{calendarId}/events/{eventId}/move",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "calendar.events.patch",
                    "path": "calendars/{calendarId}/events/{eventId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "quickAdd": {
                    "httpMethod": "POST",
                    "id": "calendar.events.quickAdd",
                    "path": "calendars/{calendarId}/events/quickAdd",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "calendar.events.update",
                    "path": "calendars/{calendarId}/events/{eventId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.owned"
                    ]
                },
                "watch": {
                    "httpMethod": "POST",
                    "id": "calendar.events.watch",
                    "path": "calendars/{calendarId}/events/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.app.created",
                        "https://www.googleapis.com/auth/calendar.events",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.events.owned",
                        "https://www.googleapis.com/auth/calendar.events.owned.readonly",
                        "https://www.googleapis.com/auth/calendar.events.public.readonly",
                        "https://www.googleapis.com/auth/calendar.events.readonly",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ],
                    "supportsSubscription": true
                }
            }
        },
        "freebusy": {
            "methods": {
                "query": {
                    "httpMethod": "POST",
                    "id": "calendar.freebusy.query",
                    "path": "freeBusy",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.events.freebusy",
                        "https://www.googleapis.com/auth/calendar.readonly"
                    ]
                }
            }
        },
        "settings": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "calendar.settings.get",
                    "path": "users/me/settings/{setting}",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.readonly",
                        "https://www.googleapis.com/auth/calendar.settings.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "calendar.settings.list",
                    "path": "users/me/settings",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.readonly",
                        "https://www.googleapis.com/auth/calendar.settings.readonly"
                    ],
                    "supportsSubscription": true
                },
                "watch": {
                    "httpMethod": "POST",
                    "id": "calendar.settings.watch",
                    "path": "users/me/settings/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/calendar",
                        "https://www.googleapis.com/auth/calendar.readonly",
                        "https://www.googleapis.com/auth/calendar.settings.readonly"
                    ],
                    "supportsSubscription": true
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "calendar/v3/",
    "title": "Calendar API",
    "version": "v3"
}