{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/classroom.announcements": {},
                "https://www.googleapis.com/auth/classroom.announcements.readonly": {},
                "https://www.googleapis.com/auth/classroom.courses": {},
                "https://www.googleapis.com/auth/classroom.courses.readonly": {},
                "https://www.googleapis.com/auth/classroom.coursework.me": {},
                "https://www.googleapis.com/auth/classroom.coursework.me.readonly": {},
                "https://www.googleapis.com/auth/classroom.coursework.students": {},
                "https://www.googleapis.com/auth/classroom.coursework.students.readonly": {},
                "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly": {},
                "https://www.googleapis.com/auth/classroom.guardianlinks.students": {},
                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly": {},
                "https://www.googleapis.com/auth/classroom.profile.emails": {},
                "https://www.googleapis.com/auth/classroom.profile.photos": {},
                "https://www.googleapis.com/auth/classroom.push-notifications": {},
                "https://www.googleapis.com/auth/classroom.rosters": {},
                "https://www.googleapis.com/auth/classroom.rosters.readonly": {},
                "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly": {},
                "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly": {},
                "https://www.googleapis.com/auth/classroom.topics": {},
                "https://www.googleapis.com/auth/classroom.topics.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://classroom.googleapis.com/",
    "batchPath": "batch",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/classroom/",
    "fullyEncodeReservedExpansion": true,
    "id": "classroom:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://classroom.mtls.googleapis.com/",
    "name": "classroom",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "courses": {
            "methods": {
                "create": {
                    "flatPath": "v1/courses",
                    "httpMethod": "POST",
                    "id": "classroom.courses.create",
                    "path": "v1/courses",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "delete": {
                    "flatPath": "v1/courses/{id}",
                    "httpMethod": "DELETE",
                    "id": "classroom.courses.delete",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "get": {
                    "flatPath": "v1/courses/{id}",
                    "httpMethod": "GET",
                    "id": "classroom.courses.get",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses",
                        "https://www.googleapis.com/auth/classroom.courses.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v1/courses",
                    "httpMethod": "GET",
                    "id": "classroom.courses.list",
                    "path": "v1/courses",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses",
                        "https://www.googleapis.com/auth/classroom.courses.readonly"
                    ]
                },
                "patch": {
                    "flatPath": "v1/courses/{id}",
                    "httpMethod": "PATCH",
                    "id": "classroom.courses.patch",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "update": {
                    "flatPath": "v1/courses/{id}",
                    "httpMethod": "PUT",
                    "id": "classroom.courses.update",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                }
            },
            "resources": {
                "aliases": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/courses/{courseId}/aliases",
                            "httpMethod": "POST",
                            "id": "classroom.courses.aliases.create",
                            "path": "v1/courses/{courseId}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.courses"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/courses/{courseId}/aliases/{alias}",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.aliases.delete",
                            "path": "v1/courses/{courseId}/aliases/{alias}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.courses"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/courses/{courseId}/aliases",
                            "httpMethod": "GET",
                            "id": "classroom.courses.aliases.list",
                            "path": "v1/courses/{courseId}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.courses",
                                "https://www.googleapis.com/auth/classroom.courses.readonly"
                            ]
                        }
                    }
                },
                "announcements": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/courses/{courseId}/announcements",
                            "httpMethod": "POST",
                            "id": "classroom.courses.announcements.create",
                            "path": "v1/courses/{courseId}/announcements",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.announcements"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/courses/{courseId}/announcements/{id}",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.announcements.delete",
                            "path": "v1/courses/{courseId}/announcements/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.announcements"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/courses/{courseId}/announcements/{id}",
                            "httpMethod": "GET",
                            "id": "classroom.courses.announcements.get",
                            "path": "v1/courses/{courseId}/announcements/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.announcements",
                                "https://www.googleapis.com/auth/classroom.announcements.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/courses/{courseId}/announcements",
                            "httpMethod": "GET",
                            "id": "classroom.courses.announcements.list",
                            "path": "v1/courses/{courseId}/announcements",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.announcements",
                                "https://www.googleapis.com/auth/classroom.announcements.readonly"
                            ]
                        },
                        "modifyAssignees": {
                            "flatPath": "v1/courses/{courseId}/announcements/{id}:modifyAssignees",
                            "httpMethod": "POST",
                            "id": "classroom.courses.announcements.modifyAssignees",
                            "path": "v1/courses/{courseId}/announcements/{id}:modifyAssignees",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.announcements"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/courses/{courseId}/announcements/{id}",
                            "httpMethod": "PATCH",
                            "id": "classroom.courses.announcements.patch",
                            "path": "v1/courses/{courseId}/announcements/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.announcements"
                            ]
                        }
                    }
                },
                "courseWork": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/courses/{courseId}/courseWork",
                            "httpMethod": "POST",
                            "id": "classroom.courses.courseWork.create",
                            "path": "v1/courses/{courseId}/courseWork",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.coursework.students"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/courses/{courseId}/courseWork/{id}",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.courseWork.delete",
                            "path": "v1/courses/{courseId}/courseWork/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.coursework.students"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/courses/{courseId}/courseWork/{id}",
                            "httpMethod": "GET",
                            "id": "classroom.courses.courseWork.get",
                            "path": "v1/courses/{courseId}/courseWork/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.coursework.me",
                                "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                                "https://www.googleapis.com/auth/classroom.coursework.students",
                                "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/courses/{courseId}/courseWork",
                            "httpMethod": "GET",
                            "id": "classroom.courses.courseWork.list",
                            "path": "v1/courses/{courseId}/courseWork",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.coursework.me",
                                "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                                "https://www.googleapis.com/auth/classroom.coursework.students",
                                "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
                            ]
                        },
                        "modifyAssignees": {
                            "flatPath": "v1/courses/{courseId}/courseWork/{id}:modifyAssignees",
                            "httpMethod": "POST",
                            "id": "classroom.courses.courseWork.modifyAssignees",
                            "path": "v1/courses/{courseId}/courseWork/{id}:modifyAssignees",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.coursework.students"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/courses/{courseId}/courseWork/{id}",
                            "httpMethod": "PATCH",
                            "id": "classroom.courses.courseWork.patch",
                            "path": "v1/courses/{courseId}/courseWork/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.coursework.students"
                            ]
                        }
                    },
                    "resources": {
                        "studentSubmissions": {
                            "methods": {
                                "get": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
                                    "httpMethod": "GET",
                                    "id": "classroom.courses.courseWork.studentSubmissions.get",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.me",
                                        "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                                        "https://www.googleapis.com/auth/classroom.coursework.students",
                                        "https://www.googleapis.com/auth/classroom.coursework.students.readonly",
                                        "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly",
                                        "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions",
                                    "httpMethod": "GET",
                                    "id": "classroom.courses.courseWork.studentSubmissions.list",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.me",
                                        "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                                        "https://www.googleapis.com/auth/classroom.coursework.students",
                                        "https://www.googleapis.com/auth/classroom.coursework.students.readonly",
                                        "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly",
                                        "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
                                    ]
                                },
                                "modifyAttachments": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments",
                                    "httpMethod": "POST",
                                    "id": "classroom.courses.courseWork.studentSubmissions.modifyAttachments",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.me",
                                        "https://www.googleapis.com/auth/classroom.coursework.students"
                                    ]
                                },
                                "patch": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
                                    "httpMethod": "PATCH",
                                    "id": "classroom.courses.courseWork.studentSubmissions.patch",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.me",
                                        "https://www.googleapis.com/auth/classroom.coursework.students"
                                    ]
                                },
                                "reclaim": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim",
                                    "httpMethod": "POST",
                                    "id": "classroom.courses.courseWork.studentSubmissions.reclaim",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.me"
                                    ]
                                },
                                "return": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return",
                                    "httpMethod": "POST",
                                    "id": "classroom.courses.courseWork.studentSubmissions.return",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.students"
                                    ]
                                },
                                "turnIn": {
                                    "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn",
                                    "httpMethod": "POST",
                                    "id": "classroom.courses.courseWork.studentSubmissions.turnIn",
                                    "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/classroom.coursework.me"
                                    ]
                                }
                            }
                        }
                    }
                },
                "students": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/courses/{courseId}/students",
                            "httpMethod": "POST",
                            "id": "classroom.courses.students.create",
                            "path": "v1/courses/{courseId}/students",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/courses/{courseId}/students/{userId}",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.students.delete",
                            "path": "v1/courses/{courseId}/students/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/courses/{courseId}/students/{userId}",
                            "httpMethod": "GET",
                            "id": "classroom.courses.students.get",
                            "path": "v1/courses/{courseId}/students/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/courses/{courseId}/students",
                            "httpMethod": "GET",
                            "id": "classroom.courses.students.list",
                            "path": "v1/courses/{courseId}/students",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        }
                    }
                },
                "teachers": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/courses/{courseId}/teachers",
                            "httpMethod": "POST",
                            "id": "classroom.courses.teachers.create",
                            "path": "v1/courses/{courseId}/teachers",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/courses/{courseId}/teachers/{userId}",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.teachers.delete",
                            "path": "v1/courses/{courseId}/teachers/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/courses/{courseId}/teachers/{userId}",
                            "httpMethod": "GET",
                            "id": "classroom.courses.teachers.get",
                            "path": "v1/courses/{courseId}/teachers/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/courses/{courseId}/teachers",
                            "httpMethod": "GET",
                            "id": "classroom.courses.teachers.list",
                            "path": "v1/courses/{courseId}/teachers",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        }
                    }
                },
                "topics": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/courses/{courseId}/topics",
                            "httpMethod": "POST",
                            "id": "classroom.courses.topics.create",
                            "path": "v1/courses/{courseId}/topics",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.topics"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/courses/{courseId}/topics/{id}",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.topics.delete",
                            "path": "v1/courses/{courseId}/topics/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.topics"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/courses/{courseId}/topics/{id}",
                            "httpMethod": "GET",
                            "id": "classroom.courses.topics.get",
                            "path": "v1/courses/{courseId}/topics/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.topics",
                                "https://www.googleapis.com/auth/classroom.topics.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/courses/{courseId}/topics",
                            "httpMethod": "GET",
                            "id": "classroom.courses.topics.list",
                            "path": "v1/courses/{courseId}/topics",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.topics",
                                "https://www.googleapis.com/auth/classroom.topics.readonly"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/courses/{courseId}/topics/{id}",
                            "httpMethod": "PATCH",
                            "id": "classroom.courses.topics.patch",
                            "path": "v1/courses/{courseId}/topics/{id}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.topics"
                            ]
                        }
                    }
                }
            }
        },
        "invitations": {
            "methods": {
                "accept": {
                    "flatPath": "v1/invitations/{id}:accept",
                    "httpMethod": "POST",
                    "id": "classroom.invitations.accept",
                    "path": "v1/invitations/{id}:accept",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters"
                    ]
                },
                "create": {
                    "flatPath": "v1/invitations",
                    "httpMethod": "POST",
                    "id": "classroom.invitations.create",
                    "path": "v1/invitations",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters"
                    ]
                },
                "delete": {
                    "flatPath": "v1/invitations/{id}",
                    "httpMethod": "DELETE",
                    "id": "classroom.invitations.delete",
                    "path": "v1/invitations/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters"
                    ]
                },
                "get": {
                    "flatPath": "v1/invitations/{id}",
                    "httpMethod": "GET",
                    "id": "classroom.invitations.get",
                    "path": "v1/invitations/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters",
                        "https://www.googleapis.com/auth/classroom.rosters.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v1/invitations",
                    "httpMethod": "GET",
                    "id": "classroom.invitations.list",
                    "path": "v1/invitations",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters",
                        "https://www.googleapis.com/auth/classroom.rosters.readonly"
                    ]
                }
            }
        },
        "registrations": {
            "methods": {
                "create": {
                    "flatPath": "v1/registrations",
                    "httpMethod": "POST",
                    "id": "classroom.registrations.create",
                    "path": "v1/registrations",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.push-notifications"
                    ]
                },
                "delete": {
                    "flatPath": "v1/registrations/{registrationId}",
                    "httpMethod": "DELETE",
                    "id": "classroom.registrations.delete",
                    "path": "v1/registrations/{registrationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.push-notifications"
                    ]
                }
            }
        },
        "userProfiles": {
            "methods": {
                "get": {
                    "flatPath": "v1/userProfiles/{userId}",
                    "httpMethod": "GET",
                    "id": "classroom.userProfiles.get",
                    "path": "v1/userProfiles/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.profile.emails",
                        "https://www.googleapis.com/auth/classroom.profile.photos",
                        "https://www.googleapis.com/auth/classroom.rosters",
                        "https://www.googleapis.com/auth/classroom.rosters.readonly"
                    ]
                }
            },
            "resources": {
                "guardianInvitations": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/userProfiles/{studentId}/guardianInvitations",
                            "httpMethod": "POST",
                            "id": "classroom.userProfiles.guardianInvitations.create",
                            "path": "v1/userProfiles/{studentId}/guardianInvitations",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
                            "httpMethod": "GET",
                            "id": "classroom.userProfiles.guardianInvitations.get",
                            "path": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/userProfiles/{studentId}/guardianInvitations",
                            "httpMethod": "GET",
                            "id": "classroom.userProfiles.guardianInvitations.list",
                            "path": "v1/userProfiles/{studentId}/guardianInvitations",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
                            "httpMethod": "PATCH",
                            "id": "classroom.userProfiles.guardianInvitations.patch",
                            "path": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students"
                            ]
                        }
                    }
                },
                "guardians": {
                    "methods": {
                        "delete": {
                            "flatPath": "v1/userProfiles/{studentId}/guardians/{guardianId}",
                            "httpMethod": "DELETE",
                            "id": "classroom.userProfiles.guardians.delete",
                            "path": "v1/userProfiles/{studentId}/guardians/{guardianId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/userProfiles/{studentId}/guardians/{guardianId}",
                            "httpMethod": "GET",
                            "id": "classroom.userProfiles.guardians.get",
                            "path": "v1/userProfiles/{studentId}/guardians/{guardianId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly",
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/userProfiles/{studentId}/guardians",
                            "httpMethod": "GET",
                            "id": "classroom.userProfiles.guardians.list",
                            "path": "v1/userProfiles/{studentId}/guardians",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly",
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://classroom.googleapis.com/",
    "servicePath": "",
    "title": "Google Classroom API",
    "version": "v1"
}