{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud_search": {},
                "https://www.googleapis.com/auth/cloud_search.debug": {},
                "https://www.googleapis.com/auth/cloud_search.indexing": {},
                "https://www.googleapis.com/auth/cloud_search.query": {},
                "https://www.googleapis.com/auth/cloud_search.settings": {},
                "https://www.googleapis.com/auth/cloud_search.settings.indexing": {},
                "https://www.googleapis.com/auth/cloud_search.settings.query": {},
                "https://www.googleapis.com/auth/cloud_search.stats": {},
                "https://www.googleapis.com/auth/cloud_search.stats.indexing": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://cloudsearch.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Cloud Search",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
    "fullyEncodeReservedExpansion": true,
    "id": "cloudsearch:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/",
    "name": "cloudsearch",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "debug": {
            "resources": {
                "datasources": {
                    "resources": {
                        "items": {
                            "methods": {
                                "checkAccess": {
                                    "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.debug.datasources.items.checkAccess",
                                    "path": "v1/debug/{+name}:checkAccess",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.debug"
                                    ]
                                },
                                "searchByViewUrl": {
                                    "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                                    "path": "v1/debug/{+name}/items:searchByViewUrl",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.debug"
                                    ]
                                }
                            },
                            "resources": {
                                "unmappedids": {
                                    "methods": {
                                        "list": {
                                            "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                                            "httpMethod": "GET",
                                            "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                                            "path": "v1/debug/{+parent}/unmappedids",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud_search",
                                                "https://www.googleapis.com/auth/cloud_search.debug"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "identitysources": {
                    "resources": {
                        "items": {
                            "methods": {
                                "listForunmappedidentity": {
                                    "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                                    "path": "v1/debug/{+parent}/items:forunmappedidentity",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.debug"
                                    ]
                                }
                            }
                        },
                        "unmappedids": {
                            "methods": {
                                "list": {
                                    "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.debug.identitysources.unmappedids.list",
                                    "path": "v1/debug/{+parent}/unmappedids",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.debug"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "indexing": {
            "resources": {
                "datasources": {
                    "methods": {
                        "deleteSchema": {
                            "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
                            "httpMethod": "DELETE",
                            "id": "cloudsearch.indexing.datasources.deleteSchema",
                            "path": "v1/indexing/{+name}/schema",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        },
                        "getSchema": {
                            "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
                            "httpMethod": "GET",
                            "id": "cloudsearch.indexing.datasources.getSchema",
                            "path": "v1/indexing/{+name}/schema",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        },
                        "updateSchema": {
                            "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
                            "httpMethod": "PUT",
                            "id": "cloudsearch.indexing.datasources.updateSchema",
                            "path": "v1/indexing/{+name}/schema",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        }
                    },
                    "resources": {
                        "items": {
                            "methods": {
                                "delete": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                                    "httpMethod": "DELETE",
                                    "id": "cloudsearch.indexing.datasources.items.delete",
                                    "path": "v1/indexing/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "deleteQueueItems": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                                    "path": "v1/indexing/{+name}/items:deleteQueueItems",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.indexing.datasources.items.get",
                                    "path": "v1/indexing/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "index": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.indexing.datasources.items.index",
                                    "path": "v1/indexing/{+name}:index",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.indexing.datasources.items.list",
                                    "path": "v1/indexing/{+name}/items",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "poll": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.indexing.datasources.items.poll",
                                    "path": "v1/indexing/{+name}/items:poll",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "push": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.indexing.datasources.items.push",
                                    "path": "v1/indexing/{+name}:push",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "unreserve": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.indexing.datasources.items.unreserve",
                                    "path": "v1/indexing/{+name}/items:unreserve",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                },
                                "upload": {
                                    "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                                    "httpMethod": "POST",
                                    "id": "cloudsearch.indexing.datasources.items.upload",
                                    "path": "v1/indexing/{+name}:upload",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.indexing"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "media": {
            "methods": {
                "upload": {
                    "flatPath": "v1/media/{mediaId}",
                    "httpMethod": "POST",
                    "id": "cloudsearch.media.upload",
                    "path": "v1/media/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.indexing"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "operations": {
            "methods": {
                "get": {
                    "flatPath": "v1/operations/{operationsId}",
                    "httpMethod": "GET",
                    "id": "cloudsearch.operations.get",
                    "path": "v1/{+name}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug",
                        "https://www.googleapis.com/auth/cloud_search.indexing",
                        "https://www.googleapis.com/auth/cloud_search.settings",
                        "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                        "https://www.googleapis.com/auth/cloud_search.settings.query"
                    ]
                }
            }
        },
        "query": {
            "methods": {
                "search": {
                    "flatPath": "v1/query/search",
                    "httpMethod": "POST",
                    "id": "cloudsearch.query.search",
                    "path": "v1/query/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.query"
                    ]
                },
                "suggest": {
                    "flatPath": "v1/query/suggest",
                    "httpMethod": "POST",
                    "id": "cloudsearch.query.suggest",
                    "path": "v1/query/suggest",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.query"
                    ]
                }
            },
            "resources": {
                "sources": {
                    "methods": {
                        "list": {
                            "flatPath": "v1/query/sources",
                            "httpMethod": "GET",
                            "id": "cloudsearch.query.sources.list",
                            "path": "v1/query/sources",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.query"
                            ]
                        }
                    }
                }
            }
        },
        "settings": {
            "resources": {
                "datasources": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/settings/datasources",
                            "httpMethod": "POST",
                            "id": "cloudsearch.settings.datasources.create",
                            "path": "v1/settings/datasources",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/settings/datasources/{datasourcesId}",
                            "httpMethod": "DELETE",
                            "id": "cloudsearch.settings.datasources.delete",
                            "path": "v1/settings/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/settings/datasources/{datasourcesId}",
                            "httpMethod": "GET",
                            "id": "cloudsearch.settings.datasources.get",
                            "path": "v1/settings/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/settings/datasources",
                            "httpMethod": "GET",
                            "id": "cloudsearch.settings.datasources.list",
                            "path": "v1/settings/datasources",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        },
                        "update": {
                            "flatPath": "v1/settings/datasources/{datasourcesId}",
                            "httpMethod": "PUT",
                            "id": "cloudsearch.settings.datasources.update",
                            "path": "v1/settings/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
                            ]
                        }
                    }
                },
                "searchapplications": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/settings/searchapplications",
                            "httpMethod": "POST",
                            "id": "cloudsearch.settings.searchapplications.create",
                            "path": "v1/settings/searchapplications",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.query"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
                            "httpMethod": "DELETE",
                            "id": "cloudsearch.settings.searchapplications.delete",
                            "path": "v1/settings/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.query"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
                            "httpMethod": "GET",
                            "id": "cloudsearch.settings.searchapplications.get",
                            "path": "v1/settings/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.query"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/settings/searchapplications",
                            "httpMethod": "GET",
                            "id": "cloudsearch.settings.searchapplications.list",
                            "path": "v1/settings/searchapplications",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.query"
                            ]
                        },
                        "reset": {
                            "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
                            "httpMethod": "POST",
                            "id": "cloudsearch.settings.searchapplications.reset",
                            "path": "v1/settings/{+name}:reset",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.query"
                            ]
                        },
                        "update": {
                            "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
                            "httpMethod": "PUT",
                            "id": "cloudsearch.settings.searchapplications.update",
                            "path": "v1/settings/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud_search",
                                "https://www.googleapis.com/auth/cloud_search.settings",
                                "https://www.googleapis.com/auth/cloud_search.settings.query"
                            ]
                        }
                    }
                }
            }
        },
        "stats": {
            "methods": {
                "getIndex": {
                    "flatPath": "v1/stats/index",
                    "httpMethod": "GET",
                    "id": "cloudsearch.stats.getIndex",
                    "path": "v1/stats/index",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.stats",
                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                    ]
                },
                "getQuery": {
                    "flatPath": "v1/stats/query",
                    "httpMethod": "GET",
                    "id": "cloudsearch.stats.getQuery",
                    "path": "v1/stats/query",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.stats",
                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                    ]
                },
                "getSession": {
                    "flatPath": "v1/stats/session",
                    "httpMethod": "GET",
                    "id": "cloudsearch.stats.getSession",
                    "path": "v1/stats/session",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.stats",
                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                    ]
                },
                "getUser": {
                    "flatPath": "v1/stats/user",
                    "httpMethod": "GET",
                    "id": "cloudsearch.stats.getUser",
                    "path": "v1/stats/user",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.stats",
                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                    ]
                }
            },
            "resources": {
                "index": {
                    "resources": {
                        "datasources": {
                            "methods": {
                                "get": {
                                    "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.stats.index.datasources.get",
                                    "path": "v1/stats/index/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.stats",
                                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                                    ]
                                }
                            }
                        }
                    }
                },
                "query": {
                    "resources": {
                        "searchapplications": {
                            "methods": {
                                "get": {
                                    "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.stats.query.searchapplications.get",
                                    "path": "v1/stats/query/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.stats",
                                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                                    ]
                                }
                            }
                        }
                    }
                },
                "session": {
                    "resources": {
                        "searchapplications": {
                            "methods": {
                                "get": {
                                    "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.stats.session.searchapplications.get",
                                    "path": "v1/stats/session/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.stats",
                                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                                    ]
                                }
                            }
                        }
                    }
                },
                "user": {
                    "resources": {
                        "searchapplications": {
                            "methods": {
                                "get": {
                                    "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                                    "httpMethod": "GET",
                                    "id": "cloudsearch.stats.user.searchapplications.get",
                                    "path": "v1/stats/user/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud_search",
                                        "https://www.googleapis.com/auth/cloud_search.stats",
                                        "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://cloudsearch.googleapis.com/",
    "schemas": {
        "BooleanOperatorOptions": {
            "id": "BooleanOperatorOptions",
            "properties": {
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "BooleanPropertyOptions": {
            "id": "BooleanPropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "BooleanOperatorOptions"
                }
            },
            "type": "object"
        },
        "CheckAccessResponse": {
            "id": "CheckAccessResponse",
            "properties": {
                "hasAccess": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "CompositeFilter": {
            "id": "CompositeFilter",
            "properties": {
                "logicOperator": {
                    "enum": [
                        "AND",
                        "OR",
                        "NOT"
                    ],
                    "type": "string"
                },
                "subFilters": {
                    "items": {
                        "$ref": "Filter"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "CustomerIndexStats": {
            "id": "CustomerIndexStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "itemCountByStatus": {
                    "items": {
                        "$ref": "ItemCountByStatus"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "CustomerQueryStats": {
            "id": "CustomerQueryStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "queryCountByStatus": {
                    "items": {
                        "$ref": "QueryCountByStatus"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "CustomerSessionStats": {
            "id": "CustomerSessionStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "searchSessionsCount": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CustomerUserStats": {
            "id": "CustomerUserStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "oneDayActiveUsersCount": {
                    "format": "int64",
                    "type": "string"
                },
                "sevenDaysActiveUsersCount": {
                    "format": "int64",
                    "type": "string"
                },
                "thirtyDaysActiveUsersCount": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DataSource": {
            "id": "DataSource",
            "properties": {
                "disableModifications": {
                    "type": "boolean"
                },
                "disableServing": {
                    "type": "boolean"
                },
                "displayName": {
                    "type": "string"
                },
                "indexingServiceAccounts": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "itemsVisibility": {
                    "items": {
                        "$ref": "GSuitePrincipal"
                    },
                    "type": "array"
                },
                "name": {
                    "type": "string"
                },
                "operationIds": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "shortName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DataSourceIndexStats": {
            "id": "DataSourceIndexStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "itemCountByStatus": {
                    "items": {
                        "$ref": "ItemCountByStatus"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "DataSourceRestriction": {
            "id": "DataSourceRestriction",
            "properties": {
                "filterOptions": {
                    "items": {
                        "$ref": "FilterOptions"
                    },
                    "type": "array"
                },
                "source": {
                    "$ref": "Source"
                }
            },
            "type": "object"
        },
        "Date": {
            "id": "Date",
            "properties": {
                "day": {
                    "format": "int32",
                    "type": "integer"
                },
                "month": {
                    "format": "int32",
                    "type": "integer"
                },
                "year": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "DateOperatorOptions": {
            "id": "DateOperatorOptions",
            "properties": {
                "greaterThanOperatorName": {
                    "type": "string"
                },
                "lessThanOperatorName": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DatePropertyOptions": {
            "id": "DatePropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "DateOperatorOptions"
                }
            },
            "type": "object"
        },
        "DateValues": {
            "id": "DateValues",
            "properties": {
                "values": {
                    "items": {
                        "$ref": "Date"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "DebugOptions": {
            "id": "DebugOptions",
            "properties": {
                "enableDebugging": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "DeleteQueueItemsRequest": {
            "id": "DeleteQueueItemsRequest",
            "properties": {
                "connectorName": {
                    "type": "string"
                },
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "queue": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DisplayedProperty": {
            "id": "DisplayedProperty",
            "properties": {
                "propertyName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DoubleOperatorOptions": {
            "id": "DoubleOperatorOptions",
            "properties": {
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DoublePropertyOptions": {
            "id": "DoublePropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "DoubleOperatorOptions"
                }
            },
            "type": "object"
        },
        "DoubleValues": {
            "id": "DoubleValues",
            "properties": {
                "values": {
                    "items": {
                        "format": "double",
                        "type": "number"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "DriveFollowUpRestrict": {
            "id": "DriveFollowUpRestrict",
            "properties": {
                "type": {
                    "enum": [
                        "UNSPECIFIED",
                        "FOLLOWUP_SUGGESTIONS",
                        "FOLLOWUP_ACTION_ITEMS"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DriveLocationRestrict": {
            "id": "DriveLocationRestrict",
            "properties": {
                "type": {
                    "enum": [
                        "UNSPECIFIED",
                        "TRASHED",
                        "STARRED"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DriveMimeTypeRestrict": {
            "id": "DriveMimeTypeRestrict",
            "properties": {
                "type": {
                    "enum": [
                        "UNSPECIFIED",
                        "PDF",
                        "DOCUMENT",
                        "PRESENTATION",
                        "SPREADSHEET",
                        "FORM",
                        "DRAWING",
                        "SCRIPT",
                        "MAP",
                        "IMAGE",
                        "AUDIO",
                        "VIDEO",
                        "FOLDER",
                        "ARCHIVE",
                        "SITE"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DriveTimeSpanRestrict": {
            "id": "DriveTimeSpanRestrict",
            "properties": {
                "type": {
                    "enum": [
                        "UNSPECIFIED",
                        "TODAY",
                        "YESTERDAY",
                        "LAST_7_DAYS",
                        "LAST_30_DAYS",
                        "LAST_90_DAYS"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "EmailAddress": {
            "id": "EmailAddress",
            "properties": {
                "emailAddress": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "EnumOperatorOptions": {
            "id": "EnumOperatorOptions",
            "properties": {
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "EnumPropertyOptions": {
            "id": "EnumPropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "EnumOperatorOptions"
                },
                "orderedRanking": {
                    "enum": [
                        "NO_ORDER",
                        "ASCENDING",
                        "DESCENDING"
                    ],
                    "type": "string"
                },
                "possibleValues": {
                    "items": {
                        "$ref": "EnumValuePair"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "EnumValuePair": {
            "id": "EnumValuePair",
            "properties": {
                "integerValue": {
                    "format": "int32",
                    "type": "integer"
                },
                "stringValue": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "EnumValues": {
            "id": "EnumValues",
            "properties": {
                "values": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ErrorInfo": {
            "id": "ErrorInfo",
            "properties": {
                "errorMessages": {
                    "items": {
                        "$ref": "ErrorMessage"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ErrorMessage": {
            "id": "ErrorMessage",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "source": {
                    "$ref": "Source"
                }
            },
            "type": "object"
        },
        "FacetBucket": {
            "id": "FacetBucket",
            "properties": {
                "count": {
                    "format": "int32",
                    "type": "integer"
                },
                "percentage": {
                    "format": "int32",
                    "type": "integer"
                },
                "value": {
                    "$ref": "Value"
                }
            },
            "type": "object"
        },
        "FacetOptions": {
            "id": "FacetOptions",
            "properties": {
                "numFacetBuckets": {
                    "format": "int32",
                    "type": "integer"
                },
                "objectType": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                },
                "sourceName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "FacetResult": {
            "id": "FacetResult",
            "properties": {
                "buckets": {
                    "items": {
                        "$ref": "FacetBucket"
                    },
                    "type": "array"
                },
                "objectType": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                },
                "sourceName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "FieldViolation": {
            "id": "FieldViolation",
            "properties": {
                "field": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Filter": {
            "id": "Filter",
            "properties": {
                "compositeFilter": {
                    "$ref": "CompositeFilter"
                },
                "valueFilter": {
                    "$ref": "ValueFilter"
                }
            },
            "type": "object"
        },
        "FilterOptions": {
            "id": "FilterOptions",
            "properties": {
                "filter": {
                    "$ref": "Filter"
                },
                "objectType": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "FreshnessOptions": {
            "id": "FreshnessOptions",
            "properties": {
                "freshnessDuration": {
                    "format": "google-duration",
                    "type": "string"
                },
                "freshnessProperty": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "GSuitePrincipal": {
            "id": "GSuitePrincipal",
            "properties": {
                "gsuiteDomain": {
                    "type": "boolean"
                },
                "gsuiteGroupEmail": {
                    "type": "string"
                },
                "gsuiteUserEmail": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "GetCustomerIndexStatsResponse": {
            "id": "GetCustomerIndexStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "CustomerIndexStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetCustomerQueryStatsResponse": {
            "id": "GetCustomerQueryStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "CustomerQueryStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetCustomerSessionStatsResponse": {
            "id": "GetCustomerSessionStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "CustomerSessionStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetCustomerUserStatsResponse": {
            "id": "GetCustomerUserStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "CustomerUserStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetDataSourceIndexStatsResponse": {
            "id": "GetDataSourceIndexStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "DataSourceIndexStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetSearchApplicationQueryStatsResponse": {
            "id": "GetSearchApplicationQueryStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "SearchApplicationQueryStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetSearchApplicationSessionStatsResponse": {
            "id": "GetSearchApplicationSessionStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "SearchApplicationSessionStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetSearchApplicationUserStatsResponse": {
            "id": "GetSearchApplicationUserStatsResponse",
            "properties": {
                "stats": {
                    "items": {
                        "$ref": "SearchApplicationUserStats"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "HtmlOperatorOptions": {
            "id": "HtmlOperatorOptions",
            "properties": {
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "HtmlPropertyOptions": {
            "id": "HtmlPropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "HtmlOperatorOptions"
                },
                "retrievalImportance": {
                    "$ref": "RetrievalImportance"
                }
            },
            "type": "object"
        },
        "HtmlValues": {
            "id": "HtmlValues",
            "properties": {
                "values": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "IndexItemOptions": {
            "id": "IndexItemOptions",
            "properties": {
                "allowUnknownGsuitePrincipals": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "IndexItemRequest": {
            "id": "IndexItemRequest",
            "properties": {
                "connectorName": {
                    "type": "string"
                },
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "indexItemOptions": {
                    "$ref": "IndexItemOptions"
                },
                "item": {
                    "$ref": "Item"
                },
                "mode": {
                    "enum": [
                        "UNSPECIFIED",
                        "SYNCHRONOUS",
                        "ASYNCHRONOUS"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "IntegerOperatorOptions": {
            "id": "IntegerOperatorOptions",
            "properties": {
                "greaterThanOperatorName": {
                    "type": "string"
                },
                "lessThanOperatorName": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "IntegerPropertyOptions": {
            "id": "IntegerPropertyOptions",
            "properties": {
                "maximumValue": {
                    "format": "int64",
                    "type": "string"
                },
                "minimumValue": {
                    "format": "int64",
                    "type": "string"
                },
                "operatorOptions": {
                    "$ref": "IntegerOperatorOptions"
                },
                "orderedRanking": {
                    "enum": [
                        "NO_ORDER",
                        "ASCENDING",
                        "DESCENDING"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "IntegerValues": {
            "id": "IntegerValues",
            "properties": {
                "values": {
                    "items": {
                        "format": "int64",
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Interaction": {
            "id": "Interaction",
            "properties": {
                "interactionTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "principal": {
                    "$ref": "Principal"
                },
                "type": {
                    "enum": [
                        "UNSPECIFIED",
                        "VIEW",
                        "EDIT"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Item": {
            "id": "Item",
            "properties": {
                "acl": {
                    "$ref": "ItemAcl"
                },
                "content": {
                    "$ref": "ItemContent"
                },
                "itemType": {
                    "enum": [
                        "UNSPECIFIED",
                        "CONTENT_ITEM",
                        "CONTAINER_ITEM",
                        "VIRTUAL_CONTAINER_ITEM"
                    ],
                    "type": "string"
                },
                "metadata": {
                    "$ref": "ItemMetadata"
                },
                "name": {
                    "type": "string"
                },
                "payload": {
                    "format": "byte",
                    "type": "string"
                },
                "queue": {
                    "type": "string"
                },
                "status": {
                    "$ref": "ItemStatus"
                },
                "structuredData": {
                    "$ref": "ItemStructuredData"
                },
                "version": {
                    "format": "byte",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ItemAcl": {
            "id": "ItemAcl",
            "properties": {
                "aclInheritanceType": {
                    "enum": [
                        "NOT_APPLICABLE",
                        "CHILD_OVERRIDE",
                        "PARENT_OVERRIDE",
                        "BOTH_PERMIT"
                    ],
                    "type": "string"
                },
                "deniedReaders": {
                    "items": {
                        "$ref": "Principal"
                    },
                    "type": "array"
                },
                "inheritAclFrom": {
                    "type": "string"
                },
                "owners": {
                    "items": {
                        "$ref": "Principal"
                    },
                    "type": "array"
                },
                "readers": {
                    "items": {
                        "$ref": "Principal"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ItemContent": {
            "id": "ItemContent",
            "properties": {
                "contentDataRef": {
                    "$ref": "UploadItemRef"
                },
                "contentFormat": {
                    "enum": [
                        "UNSPECIFIED",
                        "HTML",
                        "TEXT",
                        "RAW"
                    ],
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "inlineContent": {
                    "format": "byte",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ItemCountByStatus": {
            "id": "ItemCountByStatus",
            "properties": {
                "count": {
                    "format": "int64",
                    "type": "string"
                },
                "statusCode": {
                    "enum": [
                        "CODE_UNSPECIFIED",
                        "ERROR",
                        "MODIFIED",
                        "NEW_ITEM",
                        "ACCEPTED"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ItemMetadata": {
            "id": "ItemMetadata",
            "properties": {
                "containerName": {
                    "type": "string"
                },
                "contentLanguage": {
                    "type": "string"
                },
                "createTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "interactions": {
                    "items": {
                        "$ref": "Interaction"
                    },
                    "type": "array"
                },
                "keywords": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "mimeType": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "searchQualityMetadata": {
                    "$ref": "SearchQualityMetadata"
                },
                "sourceRepositoryUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updateTime": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ItemStatus": {
            "id": "ItemStatus",
            "properties": {
                "code": {
                    "enum": [
                        "CODE_UNSPECIFIED",
                        "ERROR",
                        "MODIFIED",
                        "NEW_ITEM",
                        "ACCEPTED"
                    ],
                    "type": "string"
                },
                "processingErrors": {
                    "items": {
                        "$ref": "ProcessingError"
                    },
                    "type": "array"
                },
                "repositoryErrors": {
                    "items": {
                        "$ref": "RepositoryError"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ItemStructuredData": {
            "id": "ItemStructuredData",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "object": {
                    "$ref": "StructuredDataObject"
                }
            },
            "type": "object"
        },
        "ListDataSourceResponse": {
            "id": "ListDataSourceResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "sources": {
                    "items": {
                        "$ref": "DataSource"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListItemNamesForUnmappedIdentityResponse": {
            "id": "ListItemNamesForUnmappedIdentityResponse",
            "properties": {
                "itemNames": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ListItemsResponse": {
            "id": "ListItemsResponse",
            "properties": {
                "items": {
                    "items": {
                        "$ref": "Item"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ListQuerySourcesResponse": {
            "id": "ListQuerySourcesResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "sources": {
                    "items": {
                        "$ref": "QuerySource"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListSearchApplicationsResponse": {
            "id": "ListSearchApplicationsResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "searchApplications": {
                    "items": {
                        "$ref": "SearchApplication"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListUnmappedIdentitiesResponse": {
            "id": "ListUnmappedIdentitiesResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "unmappedIdentities": {
                    "items": {
                        "$ref": "UnmappedIdentity"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "MatchRange": {
            "id": "MatchRange",
            "properties": {
                "end": {
                    "format": "int32",
                    "type": "integer"
                },
                "start": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "Media": {
            "id": "Media",
            "properties": {
                "resourceName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Metadata": {
            "id": "Metadata",
            "properties": {
                "createTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "displayOptions": {
                    "$ref": "ResultDisplayMetadata"
                },
                "fields": {
                    "items": {
                        "$ref": "NamedProperty"
                    },
                    "type": "array"
                },
                "mimeType": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "Person"
                },
                "source": {
                    "$ref": "Source"
                },
                "updateTime": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Metaline": {
            "id": "Metaline",
            "properties": {
                "properties": {
                    "items": {
                        "$ref": "DisplayedProperty"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Name": {
            "id": "Name",
            "properties": {
                "displayName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "NamedProperty": {
            "id": "NamedProperty",
            "properties": {
                "booleanValue": {
                    "type": "boolean"
                },
                "dateValues": {
                    "$ref": "DateValues"
                },
                "doubleValues": {
                    "$ref": "DoubleValues"
                },
                "enumValues": {
                    "$ref": "EnumValues"
                },
                "htmlValues": {
                    "$ref": "HtmlValues"
                },
                "integerValues": {
                    "$ref": "IntegerValues"
                },
                "name": {
                    "type": "string"
                },
                "objectValues": {
                    "$ref": "ObjectValues"
                },
                "textValues": {
                    "$ref": "TextValues"
                },
                "timestampValues": {
                    "$ref": "TimestampValues"
                }
            },
            "type": "object"
        },
        "ObjectDefinition": {
            "id": "ObjectDefinition",
            "properties": {
                "name": {
                    "type": "string"
                },
                "options": {
                    "$ref": "ObjectOptions"
                },
                "propertyDefinitions": {
                    "items": {
                        "$ref": "PropertyDefinition"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ObjectDisplayOptions": {
            "id": "ObjectDisplayOptions",
            "properties": {
                "metalines": {
                    "items": {
                        "$ref": "Metaline"
                    },
                    "type": "array"
                },
                "objectDisplayLabel": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ObjectOptions": {
            "id": "ObjectOptions",
            "properties": {
                "displayOptions": {
                    "$ref": "ObjectDisplayOptions"
                },
                "freshnessOptions": {
                    "$ref": "FreshnessOptions"
                }
            },
            "type": "object"
        },
        "ObjectPropertyOptions": {
            "id": "ObjectPropertyOptions",
            "properties": {
                "subobjectProperties": {
                    "items": {
                        "$ref": "PropertyDefinition"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ObjectValues": {
            "id": "ObjectValues",
            "properties": {
                "values": {
                    "items": {
                        "$ref": "StructuredDataObject"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Operation": {
            "id": "Operation",
            "properties": {
                "done": {
                    "type": "boolean"
                },
                "error": {
                    "$ref": "Status"
                },
                "metadata": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "PeopleSuggestion": {
            "id": "PeopleSuggestion",
            "properties": {
                "person": {
                    "$ref": "Person"
                }
            },
            "type": "object"
        },
        "Person": {
            "id": "Person",
            "properties": {
                "emailAddresses": {
                    "items": {
                        "$ref": "EmailAddress"
                    },
                    "type": "array"
                },
                "name": {
                    "type": "string"
                },
                "obfuscatedId": {
                    "type": "string"
                },
                "personNames": {
                    "items": {
                        "$ref": "Name"
                    },
                    "type": "array"
                },
                "photos": {
                    "items": {
                        "$ref": "Photo"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Photo": {
            "id": "Photo",
            "properties": {
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "PollItemsRequest": {
            "id": "PollItemsRequest",
            "properties": {
                "connectorName": {
                    "type": "string"
                },
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "limit": {
                    "format": "int32",
                    "type": "integer"
                },
                "queue": {
                    "type": "string"
                },
                "statusCodes": {
                    "items": {
                        "enum": [
                            "CODE_UNSPECIFIED",
                            "ERROR",
                            "MODIFIED",
                            "NEW_ITEM",
                            "ACCEPTED"
                        ],
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "PollItemsResponse": {
            "id": "PollItemsResponse",
            "properties": {
                "items": {
                    "items": {
                        "$ref": "Item"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Principal": {
            "id": "Principal",
            "properties": {
                "groupResourceName": {
                    "type": "string"
                },
                "gsuitePrincipal": {
                    "$ref": "GSuitePrincipal"
                },
                "userResourceName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ProcessingError": {
            "id": "ProcessingError",
            "properties": {
                "code": {
                    "enum": [
                        "PROCESSING_ERROR_CODE_UNSPECIFIED",
                        "MALFORMED_REQUEST",
                        "UNSUPPORTED_CONTENT_FORMAT",
                        "INDIRECT_BROKEN_ACL",
                        "ACL_CYCLE"
                    ],
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "fieldViolations": {
                    "items": {
                        "$ref": "FieldViolation"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "PropertyDefinition": {
            "id": "PropertyDefinition",
            "properties": {
                "booleanPropertyOptions": {
                    "$ref": "BooleanPropertyOptions"
                },
                "datePropertyOptions": {
                    "$ref": "DatePropertyOptions"
                },
                "displayOptions": {
                    "$ref": "PropertyDisplayOptions"
                },
                "doublePropertyOptions": {
                    "$ref": "DoublePropertyOptions"
                },
                "enumPropertyOptions": {
                    "$ref": "EnumPropertyOptions"
                },
                "htmlPropertyOptions": {
                    "$ref": "HtmlPropertyOptions"
                },
                "integerPropertyOptions": {
                    "$ref": "IntegerPropertyOptions"
                },
                "isFacetable": {
                    "type": "boolean"
                },
                "isRepeatable": {
                    "type": "boolean"
                },
                "isReturnable": {
                    "type": "boolean"
                },
                "isSortable": {
                    "type": "boolean"
                },
                "isSuggestable": {
                    "type": "boolean"
                },
                "isWildcardSearchable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "objectPropertyOptions": {
                    "$ref": "ObjectPropertyOptions"
                },
                "textPropertyOptions": {
                    "$ref": "TextPropertyOptions"
                },
                "timestampPropertyOptions": {
                    "$ref": "TimestampPropertyOptions"
                }
            },
            "type": "object"
        },
        "PropertyDisplayOptions": {
            "id": "PropertyDisplayOptions",
            "properties": {
                "displayLabel": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "PushItem": {
            "id": "PushItem",
            "properties": {
                "contentHash": {
                    "type": "string"
                },
                "metadataHash": {
                    "type": "string"
                },
                "payload": {
                    "format": "byte",
                    "type": "string"
                },
                "queue": {
                    "type": "string"
                },
                "repositoryError": {
                    "$ref": "RepositoryError"
                },
                "structuredDataHash": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "UNSPECIFIED",
                        "MODIFIED",
                        "NOT_MODIFIED",
                        "REPOSITORY_ERROR",
                        "REQUEUE"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "PushItemRequest": {
            "id": "PushItemRequest",
            "properties": {
                "connectorName": {
                    "type": "string"
                },
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "item": {
                    "$ref": "PushItem"
                }
            },
            "type": "object"
        },
        "QueryCountByStatus": {
            "id": "QueryCountByStatus",
            "properties": {
                "count": {
                    "format": "int64",
                    "type": "string"
                },
                "statusCode": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "QueryInterpretation": {
            "id": "QueryInterpretation",
            "properties": {
                "interpretationType": {
                    "enum": [
                        "NONE",
                        "BLEND",
                        "REPLACE"
                    ],
                    "type": "string"
                },
                "interpretedQuery": {
                    "type": "string"
                },
                "reason": {
                    "enum": [
                        "UNSPECIFIED",
                        "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
                        "NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "QueryInterpretationOptions": {
            "id": "QueryInterpretationOptions",
            "properties": {
                "disableNlInterpretation": {
                    "type": "boolean"
                },
                "enableVerbatimMode": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "QueryItem": {
            "id": "QueryItem",
            "properties": {
                "isSynthetic": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "QueryOperator": {
            "id": "QueryOperator",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "enumValues": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "greaterThanOperatorName": {
                    "type": "string"
                },
                "isFacetable": {
                    "type": "boolean"
                },
                "isRepeatable": {
                    "type": "boolean"
                },
                "isReturnable": {
                    "type": "boolean"
                },
                "isSortable": {
                    "type": "boolean"
                },
                "isSuggestable": {
                    "type": "boolean"
                },
                "lessThanOperatorName": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "UNKNOWN",
                        "INTEGER",
                        "DOUBLE",
                        "TIMESTAMP",
                        "BOOLEAN",
                        "ENUM",
                        "DATE",
                        "TEXT",
                        "HTML"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "QuerySource": {
            "id": "QuerySource",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "operators": {
                    "items": {
                        "$ref": "QueryOperator"
                    },
                    "type": "array"
                },
                "shortName": {
                    "type": "string"
                },
                "source": {
                    "$ref": "Source"
                }
            },
            "type": "object"
        },
        "QuerySuggestion": {
            "id": "QuerySuggestion",
            "properties": {},
            "type": "object"
        },
        "RepositoryError": {
            "id": "RepositoryError",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "httpStatusCode": {
                    "format": "int32",
                    "type": "integer"
                },
                "type": {
                    "enum": [
                        "UNKNOWN",
                        "NETWORK_ERROR",
                        "DNS_ERROR",
                        "CONNECTION_ERROR",
                        "AUTHENTICATION_ERROR",
                        "AUTHORIZATION_ERROR",
                        "SERVER_ERROR",
                        "QUOTA_EXCEEDED",
                        "SERVICE_UNAVAILABLE",
                        "CLIENT_ERROR"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RequestOptions": {
            "id": "RequestOptions",
            "properties": {
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "languageCode": {
                    "type": "string"
                },
                "searchApplicationId": {
                    "type": "string"
                },
                "timeZone": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ResetSearchApplicationRequest": {
            "id": "ResetSearchApplicationRequest",
            "properties": {
                "debugOptions": {
                    "$ref": "DebugOptions"
                }
            },
            "type": "object"
        },
        "ResponseDebugInfo": {
            "id": "ResponseDebugInfo",
            "properties": {
                "formattedDebugInfo": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RestrictItem": {
            "id": "RestrictItem",
            "properties": {
                "driveFollowUpRestrict": {
                    "$ref": "DriveFollowUpRestrict"
                },
                "driveLocationRestrict": {
                    "$ref": "DriveLocationRestrict"
                },
                "driveMimeTypeRestrict": {
                    "$ref": "DriveMimeTypeRestrict"
                },
                "driveTimeSpanRestrict": {
                    "$ref": "DriveTimeSpanRestrict"
                },
                "searchOperator": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ResultCounts": {
            "id": "ResultCounts",
            "properties": {
                "sourceResultCounts": {
                    "items": {
                        "$ref": "SourceResultCount"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ResultDebugInfo": {
            "id": "ResultDebugInfo",
            "properties": {
                "formattedDebugInfo": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ResultDisplayField": {
            "id": "ResultDisplayField",
            "properties": {
                "label": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                },
                "property": {
                    "$ref": "NamedProperty"
                }
            },
            "type": "object"
        },
        "ResultDisplayLine": {
            "id": "ResultDisplayLine",
            "properties": {
                "fields": {
                    "items": {
                        "$ref": "ResultDisplayField"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ResultDisplayMetadata": {
            "id": "ResultDisplayMetadata",
            "properties": {
                "metalines": {
                    "items": {
                        "$ref": "ResultDisplayLine"
                    },
                    "type": "array"
                },
                "objectTypeLabel": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RetrievalImportance": {
            "id": "RetrievalImportance",
            "properties": {
                "importance": {
                    "enum": [
                        "DEFAULT",
                        "HIGHEST",
                        "HIGH",
                        "LOW",
                        "NONE"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Schema": {
            "id": "Schema",
            "properties": {
                "objectDefinitions": {
                    "items": {
                        "$ref": "ObjectDefinition"
                    },
                    "type": "array"
                },
                "operationIds": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ScoringConfig": {
            "id": "ScoringConfig",
            "properties": {
                "disableFreshness": {
                    "type": "boolean"
                },
                "disablePersonalization": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "SearchApplication": {
            "id": "SearchApplication",
            "properties": {
                "dataSourceRestrictions": {
                    "items": {
                        "$ref": "DataSourceRestriction"
                    },
                    "type": "array"
                },
                "defaultFacetOptions": {
                    "items": {
                        "$ref": "FacetOptions"
                    },
                    "type": "array"
                },
                "defaultSortOptions": {
                    "$ref": "SortOptions"
                },
                "displayName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operationIds": {
                    "items": {
                        "type": "string"
                    },
                    "readOnly": true,
                    "type": "array"
                },
                "scoringConfig": {
                    "$ref": "ScoringConfig"
                },
                "sourceConfig": {
                    "items": {
                        "$ref": "SourceConfig"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "SearchApplicationQueryStats": {
            "id": "SearchApplicationQueryStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "queryCountByStatus": {
                    "items": {
                        "$ref": "QueryCountByStatus"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "SearchApplicationSessionStats": {
            "id": "SearchApplicationSessionStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "searchSessionsCount": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SearchApplicationUserStats": {
            "id": "SearchApplicationUserStats",
            "properties": {
                "date": {
                    "$ref": "Date"
                },
                "oneDayActiveUsersCount": {
                    "format": "int64",
                    "type": "string"
                },
                "sevenDaysActiveUsersCount": {
                    "format": "int64",
                    "type": "string"
                },
                "thirtyDaysActiveUsersCount": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SearchItemsByViewUrlRequest": {
            "id": "SearchItemsByViewUrlRequest",
            "properties": {
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "pageToken": {
                    "type": "string"
                },
                "viewUrl": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SearchItemsByViewUrlResponse": {
            "id": "SearchItemsByViewUrlResponse",
            "properties": {
                "items": {
                    "items": {
                        "$ref": "Item"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SearchQualityMetadata": {
            "id": "SearchQualityMetadata",
            "properties": {
                "quality": {
                    "format": "double",
                    "type": "number"
                }
            },
            "type": "object"
        },
        "SearchRequest": {
            "id": "SearchRequest",
            "properties": {
                "dataSourceRestrictions": {
                    "items": {
                        "$ref": "DataSourceRestriction"
                    },
                    "type": "array"
                },
                "facetOptions": {
                    "items": {
                        "$ref": "FacetOptions"
                    },
                    "type": "array"
                },
                "pageSize": {
                    "format": "int32",
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "queryInterpretationOptions": {
                    "$ref": "QueryInterpretationOptions"
                },
                "requestOptions": {
                    "$ref": "RequestOptions"
                },
                "sortOptions": {
                    "$ref": "SortOptions"
                },
                "start": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "SearchResponse": {
            "id": "SearchResponse",
            "properties": {
                "debugInfo": {
                    "$ref": "ResponseDebugInfo"
                },
                "errorInfo": {
                    "$ref": "ErrorInfo"
                },
                "facetResults": {
                    "items": {
                        "$ref": "FacetResult"
                    },
                    "type": "array"
                },
                "hasMoreResults": {
                    "type": "boolean"
                },
                "queryInterpretation": {
                    "$ref": "QueryInterpretation"
                },
                "resultCountEstimate": {
                    "format": "int64",
                    "type": "string"
                },
                "resultCountExact": {
                    "format": "int64",
                    "type": "string"
                },
                "resultCounts": {
                    "$ref": "ResultCounts"
                },
                "results": {
                    "items": {
                        "$ref": "SearchResult"
                    },
                    "type": "array"
                },
                "spellResults": {
                    "items": {
                        "$ref": "SpellResult"
                    },
                    "type": "array"
                },
                "structuredResults": {
                    "items": {
                        "$ref": "StructuredResult"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "SearchResult": {
            "id": "SearchResult",
            "properties": {
                "clusteredResults": {
                    "items": {
                        "$ref": "SearchResult"
                    },
                    "type": "array"
                },
                "debugInfo": {
                    "$ref": "ResultDebugInfo"
                },
                "metadata": {
                    "$ref": "Metadata"
                },
                "snippet": {
                    "$ref": "Snippet"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Snippet": {
            "id": "Snippet",
            "properties": {
                "matchRanges": {
                    "items": {
                        "$ref": "MatchRange"
                    },
                    "type": "array"
                },
                "snippet": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SortOptions": {
            "id": "SortOptions",
            "properties": {
                "operatorName": {
                    "type": "string"
                },
                "sortOrder": {
                    "enum": [
                        "ASCENDING",
                        "DESCENDING"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Source": {
            "id": "Source",
            "properties": {
                "name": {
                    "type": "string"
                },
                "predefinedSource": {
                    "enum": [
                        "NONE",
                        "QUERY_HISTORY",
                        "PERSON",
                        "GOOGLE_DRIVE",
                        "GOOGLE_GMAIL",
                        "GOOGLE_SITES",
                        "GOOGLE_GROUPS",
                        "GOOGLE_CALENDAR",
                        "GOOGLE_KEEP"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SourceConfig": {
            "id": "SourceConfig",
            "properties": {
                "crowdingConfig": {
                    "$ref": "SourceCrowdingConfig"
                },
                "scoringConfig": {
                    "$ref": "SourceScoringConfig"
                },
                "source": {
                    "$ref": "Source"
                }
            },
            "type": "object"
        },
        "SourceCrowdingConfig": {
            "id": "SourceCrowdingConfig",
            "properties": {
                "numResults": {
                    "format": "int32",
                    "type": "integer"
                },
                "numSuggestions": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "SourceResultCount": {
            "id": "SourceResultCount",
            "properties": {
                "hasMoreResults": {
                    "type": "boolean"
                },
                "resultCountEstimate": {
                    "format": "int64",
                    "type": "string"
                },
                "resultCountExact": {
                    "format": "int64",
                    "type": "string"
                },
                "source": {
                    "$ref": "Source"
                }
            },
            "type": "object"
        },
        "SourceScoringConfig": {
            "id": "SourceScoringConfig",
            "properties": {
                "sourceImportance": {
                    "enum": [
                        "DEFAULT",
                        "LOW",
                        "HIGH"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SpellResult": {
            "id": "SpellResult",
            "properties": {
                "suggestedQuery": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "StartUploadItemRequest": {
            "id": "StartUploadItemRequest",
            "properties": {
                "connectorName": {
                    "type": "string"
                },
                "debugOptions": {
                    "$ref": "DebugOptions"
                }
            },
            "type": "object"
        },
        "Status": {
            "id": "Status",
            "properties": {
                "code": {
                    "format": "int32",
                    "type": "integer"
                },
                "details": {
                    "items": {
                        "additionalProperties": {
                            "type": "any"
                        },
                        "type": "object"
                    },
                    "type": "array"
                },
                "message": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "StructuredDataObject": {
            "id": "StructuredDataObject",
            "properties": {
                "properties": {
                    "items": {
                        "$ref": "NamedProperty"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "StructuredResult": {
            "id": "StructuredResult",
            "properties": {
                "person": {
                    "$ref": "Person"
                }
            },
            "type": "object"
        },
        "SuggestRequest": {
            "id": "SuggestRequest",
            "properties": {
                "dataSourceRestrictions": {
                    "items": {
                        "$ref": "DataSourceRestriction"
                    },
                    "type": "array"
                },
                "query": {
                    "type": "string"
                },
                "requestOptions": {
                    "$ref": "RequestOptions"
                }
            },
            "type": "object"
        },
        "SuggestResponse": {
            "id": "SuggestResponse",
            "properties": {
                "suggestResults": {
                    "items": {
                        "$ref": "SuggestResult"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "SuggestResult": {
            "id": "SuggestResult",
            "properties": {
                "peopleSuggestion": {
                    "$ref": "PeopleSuggestion"
                },
                "querySuggestion": {
                    "$ref": "QuerySuggestion"
                },
                "source": {
                    "$ref": "Source"
                },
                "suggestedQuery": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TextOperatorOptions": {
            "id": "TextOperatorOptions",
            "properties": {
                "exactMatchWithOperator": {
                    "type": "boolean"
                },
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TextPropertyOptions": {
            "id": "TextPropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "TextOperatorOptions"
                },
                "retrievalImportance": {
                    "$ref": "RetrievalImportance"
                }
            },
            "type": "object"
        },
        "TextValues": {
            "id": "TextValues",
            "properties": {
                "values": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "TimestampOperatorOptions": {
            "id": "TimestampOperatorOptions",
            "properties": {
                "greaterThanOperatorName": {
                    "type": "string"
                },
                "lessThanOperatorName": {
                    "type": "string"
                },
                "operatorName": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TimestampPropertyOptions": {
            "id": "TimestampPropertyOptions",
            "properties": {
                "operatorOptions": {
                    "$ref": "TimestampOperatorOptions"
                }
            },
            "type": "object"
        },
        "TimestampValues": {
            "id": "TimestampValues",
            "properties": {
                "values": {
                    "items": {
                        "format": "google-datetime",
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "UnmappedIdentity": {
            "id": "UnmappedIdentity",
            "properties": {
                "externalIdentity": {
                    "$ref": "Principal"
                },
                "resolutionStatusCode": {
                    "enum": [
                        "CODE_UNSPECIFIED",
                        "NOT_FOUND",
                        "IDENTITY_SOURCE_NOT_FOUND",
                        "IDENTITY_SOURCE_MISCONFIGURED",
                        "TOO_MANY_MAPPINGS_FOUND",
                        "INTERNAL_ERROR"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "UnreserveItemsRequest": {
            "id": "UnreserveItemsRequest",
            "properties": {
                "connectorName": {
                    "type": "string"
                },
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "queue": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "UpdateDataSourceRequest": {
            "id": "UpdateDataSourceRequest",
            "properties": {
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "source": {
                    "$ref": "DataSource"
                }
            },
            "type": "object"
        },
        "UpdateSchemaRequest": {
            "id": "UpdateSchemaRequest",
            "properties": {
                "debugOptions": {
                    "$ref": "DebugOptions"
                },
                "schema": {
                    "$ref": "Schema"
                },
                "validateOnly": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "UploadItemRef": {
            "id": "UploadItemRef",
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Value": {
            "id": "Value",
            "properties": {
                "booleanValue": {
                    "type": "boolean"
                },
                "dateValue": {
                    "$ref": "Date"
                },
                "doubleValue": {
                    "format": "double",
                    "type": "number"
                },
                "integerValue": {
                    "format": "int64",
                    "type": "string"
                },
                "stringValue": {
                    "type": "string"
                },
                "timestampValue": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ValueFilter": {
            "id": "ValueFilter",
            "properties": {
                "operatorName": {
                    "type": "string"
                },
                "value": {
                    "$ref": "Value"
                }
            },
            "type": "object"
        }
    },
    "servicePath": "",
    "title": "Cloud Search API",
    "version": "v1",
    "version_module": true
}