{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud-identity.groups": {},
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {},
                "https://www.googleapis.com/auth/cloud-platform": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://cloudidentity.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Cloud Identity",
    "discoveryVersion": "v1",
    "documentationLink": "https://cloud.google.com/identity/",
    "fullyEncodeReservedExpansion": true,
    "id": "cloudidentity:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
    "name": "cloudidentity",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "groups": {
            "methods": {
                "create": {
                    "flatPath": "v1/groups",
                    "httpMethod": "POST",
                    "id": "cloudidentity.groups.create",
                    "path": "v1/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "delete": {
                    "flatPath": "v1/groups/{groupsId}",
                    "httpMethod": "DELETE",
                    "id": "cloudidentity.groups.delete",
                    "path": "v1/{+name}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "get": {
                    "flatPath": "v1/groups/{groupsId}",
                    "httpMethod": "GET",
                    "id": "cloudidentity.groups.get",
                    "path": "v1/{+name}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "list": {
                    "flatPath": "v1/groups",
                    "httpMethod": "GET",
                    "id": "cloudidentity.groups.list",
                    "path": "v1/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "lookup": {
                    "flatPath": "v1/groups:lookup",
                    "httpMethod": "GET",
                    "id": "cloudidentity.groups.lookup",
                    "path": "v1/groups:lookup",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "patch": {
                    "flatPath": "v1/groups/{groupsId}",
                    "httpMethod": "PATCH",
                    "id": "cloudidentity.groups.patch",
                    "path": "v1/{+name}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "search": {
                    "flatPath": "v1/groups:search",
                    "httpMethod": "GET",
                    "id": "cloudidentity.groups.search",
                    "path": "v1/groups:search",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-identity.groups",
                        "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                }
            },
            "resources": {
                "memberships": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/groups/{groupsId}/memberships",
                            "httpMethod": "POST",
                            "id": "cloudidentity.groups.memberships.create",
                            "path": "v1/{+parent}/memberships",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-identity.groups",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
                            "httpMethod": "DELETE",
                            "id": "cloudidentity.groups.memberships.delete",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-identity.groups",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
                            "httpMethod": "GET",
                            "id": "cloudidentity.groups.memberships.get",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-identity.groups",
                                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/groups/{groupsId}/memberships",
                            "httpMethod": "GET",
                            "id": "cloudidentity.groups.memberships.list",
                            "path": "v1/{+parent}/memberships",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-identity.groups",
                                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "lookup": {
                            "flatPath": "v1/groups/{groupsId}/memberships:lookup",
                            "httpMethod": "GET",
                            "id": "cloudidentity.groups.memberships.lookup",
                            "path": "v1/{+parent}/memberships:lookup",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-identity.groups",
                                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://cloudidentity.googleapis.com/",
    "servicePath": "",
    "title": "Cloud Identity API",
    "version": "v1",
    "version_module": true
}