{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/display-video": {},
                "https://www.googleapis.com/auth/display-video-mediaplanning": {},
                "https://www.googleapis.com/auth/display-video-user-management": {},
                "https://www.googleapis.com/auth/doubleclickbidmanager": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://displayvideo.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Display Video",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/display-video/",
    "fullyEncodeReservedExpansion": true,
    "id": "displayvideo:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
    "name": "displayvideo",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "advertisers": {
            "methods": {
                "audit": {
                    "flatPath": "v1/advertisers/{advertisersId}:audit",
                    "httpMethod": "GET",
                    "id": "displayvideo.advertisers.audit",
                    "path": "v1/advertisers/{+advertiserId}:audit",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "bulkEditAdvertiserAssignedTargetingOptions": {
                    "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
                    "httpMethod": "POST",
                    "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
                    "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "bulkListAdvertiserAssignedTargetingOptions": {
                    "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions",
                    "httpMethod": "GET",
                    "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
                    "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "create": {
                    "flatPath": "v1/advertisers",
                    "httpMethod": "POST",
                    "id": "displayvideo.advertisers.create",
                    "path": "v1/advertisers",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "delete": {
                    "flatPath": "v1/advertisers/{advertisersId}",
                    "httpMethod": "DELETE",
                    "id": "displayvideo.advertisers.delete",
                    "path": "v1/advertisers/{+advertiserId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "get": {
                    "flatPath": "v1/advertisers/{advertisersId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.advertisers.get",
                    "path": "v1/advertisers/{+advertiserId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/advertisers",
                    "httpMethod": "GET",
                    "id": "displayvideo.advertisers.list",
                    "path": "v1/advertisers",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "patch": {
                    "flatPath": "v1/advertisers/{advertisersId}",
                    "httpMethod": "PATCH",
                    "id": "displayvideo.advertisers.patch",
                    "path": "v1/advertisers/{+advertiserId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            },
            "resources": {
                "assets": {
                    "methods": {
                        "upload": {
                            "flatPath": "v1/advertisers/{advertisersId}/assets",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.assets.upload",
                            "path": "v1/advertisers/{+advertiserId}/assets",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ],
                            "supportsMediaUpload": true
                        }
                    }
                },
                "campaigns": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/campaigns",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.campaigns.create",
                            "path": "v1/advertisers/{+advertiserId}/campaigns",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video",
                                "https://www.googleapis.com/auth/display-video-mediaplanning"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
                            "httpMethod": "DELETE",
                            "id": "displayvideo.advertisers.campaigns.delete",
                            "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video",
                                "https://www.googleapis.com/auth/display-video-mediaplanning"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.campaigns.get",
                            "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video",
                                "https://www.googleapis.com/auth/display-video-mediaplanning"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/campaigns",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.campaigns.list",
                            "path": "v1/advertisers/{+advertiserId}/campaigns",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video",
                                "https://www.googleapis.com/auth/display-video-mediaplanning"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.campaigns.patch",
                            "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video",
                                "https://www.googleapis.com/auth/display-video-mediaplanning"
                            ]
                        }
                    }
                },
                "channels": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/channels",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.channels.create",
                            "path": "v1/advertisers/{+advertiserId}/channels",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.channels.get",
                            "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/channels",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.channels.list",
                            "path": "v1/advertisers/{+advertiserId}/channels",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.channels.patch",
                            "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    },
                    "resources": {
                        "sites": {
                            "methods": {
                                "bulkEdit": {
                                    "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                                    "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "create": {
                                    "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.channels.sites.create",
                                    "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                                    "httpMethod": "DELETE",
                                    "id": "displayvideo.advertisers.channels.sites.delete",
                                    "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.advertisers.channels.sites.list",
                                    "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                }
                            }
                        }
                    }
                },
                "creatives": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/creatives",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.creatives.create",
                            "path": "v1/advertisers/{+advertiserId}/creatives",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
                            "httpMethod": "DELETE",
                            "id": "displayvideo.advertisers.creatives.delete",
                            "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.creatives.get",
                            "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/creatives",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.creatives.list",
                            "path": "v1/advertisers/{+advertiserId}/creatives",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.creatives.patch",
                            "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    }
                },
                "insertionOrders": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.insertionOrders.create",
                            "path": "v1/advertisers/{+advertiserId}/insertionOrders",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
                            "httpMethod": "DELETE",
                            "id": "displayvideo.advertisers.insertionOrders.delete",
                            "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.insertionOrders.get",
                            "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.insertionOrders.list",
                            "path": "v1/advertisers/{+advertiserId}/insertionOrders",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.insertionOrders.patch",
                            "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    }
                },
                "lineItems": {
                    "methods": {
                        "bulkEditLineItemAssignedTargetingOptions": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "bulkListLineItemAssignedTargetingOptions": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.lineItems.create",
                            "path": "v1/advertisers/{+advertiserId}/lineItems",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
                            "httpMethod": "DELETE",
                            "id": "displayvideo.advertisers.lineItems.delete",
                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.lineItems.get",
                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.lineItems.list",
                            "path": "v1/advertisers/{+advertiserId}/lineItems",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.lineItems.patch",
                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    },
                    "resources": {
                        "targetingTypes": {
                            "resources": {
                                "assignedTargetingOptions": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                                            "httpMethod": "POST",
                                            "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/display-video"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                                            "httpMethod": "DELETE",
                                            "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/display-video"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                                            "httpMethod": "GET",
                                            "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/display-video"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                                            "httpMethod": "GET",
                                            "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                                            "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/display-video"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "locationLists": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/locationLists",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.locationLists.create",
                            "path": "v1/advertisers/{+advertiserId}/locationLists",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.locationLists.get",
                            "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/locationLists",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.locationLists.list",
                            "path": "v1/advertisers/{+advertiserId}/locationLists",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.locationLists.patch",
                            "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    },
                    "resources": {
                        "assignedLocations": {
                            "methods": {
                                "bulkEdit": {
                                    "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                                    "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "create": {
                                    "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                                    "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                                    "httpMethod": "DELETE",
                                    "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                                    "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                                    "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                }
                            }
                        }
                    }
                },
                "negativeKeywordLists": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
                            "httpMethod": "POST",
                            "id": "displayvideo.advertisers.negativeKeywordLists.create",
                            "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
                            "httpMethod": "DELETE",
                            "id": "displayvideo.advertisers.negativeKeywordLists.delete",
                            "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.negativeKeywordLists.get",
                            "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
                            "httpMethod": "GET",
                            "id": "displayvideo.advertisers.negativeKeywordLists.list",
                            "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.advertisers.negativeKeywordLists.patch",
                            "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    },
                    "resources": {
                        "negativeKeywords": {
                            "methods": {
                                "bulkEdit": {
                                    "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                                    "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "create": {
                                    "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                                    "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                                    "httpMethod": "DELETE",
                                    "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                                    "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                                    "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                }
                            }
                        }
                    }
                },
                "targetingTypes": {
                    "resources": {
                        "assignedTargetingOptions": {
                            "methods": {
                                "create": {
                                    "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                                    "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                                    "httpMethod": "DELETE",
                                    "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                                    "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                                    "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                                    "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "combinedAudiences": {
            "methods": {
                "get": {
                    "flatPath": "v1/combinedAudiences/{combinedAudiencesId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.combinedAudiences.get",
                    "path": "v1/combinedAudiences/{+combinedAudienceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/combinedAudiences",
                    "httpMethod": "GET",
                    "id": "displayvideo.combinedAudiences.list",
                    "path": "v1/combinedAudiences",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "customBiddingAlgorithms": {
            "methods": {
                "get": {
                    "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.customBiddingAlgorithms.get",
                    "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/customBiddingAlgorithms",
                    "httpMethod": "GET",
                    "id": "displayvideo.customBiddingAlgorithms.list",
                    "path": "v1/customBiddingAlgorithms",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "customLists": {
            "methods": {
                "get": {
                    "flatPath": "v1/customLists/{customListsId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.customLists.get",
                    "path": "v1/customLists/{+customListId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/customLists",
                    "httpMethod": "GET",
                    "id": "displayvideo.customLists.list",
                    "path": "v1/customLists",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "firstAndThirdPartyAudiences": {
            "methods": {
                "get": {
                    "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.firstAndThirdPartyAudiences.get",
                    "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/firstAndThirdPartyAudiences",
                    "httpMethod": "GET",
                    "id": "displayvideo.firstAndThirdPartyAudiences.list",
                    "path": "v1/firstAndThirdPartyAudiences",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "floodlightGroups": {
            "methods": {
                "get": {
                    "flatPath": "v1/floodlightGroups/{floodlightGroupsId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.floodlightGroups.get",
                    "path": "v1/floodlightGroups/{+floodlightGroupId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "patch": {
                    "flatPath": "v1/floodlightGroups/{floodlightGroupId}",
                    "httpMethod": "PATCH",
                    "id": "displayvideo.floodlightGroups.patch",
                    "path": "v1/floodlightGroups/{floodlightGroupId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "googleAudiences": {
            "methods": {
                "get": {
                    "flatPath": "v1/googleAudiences/{googleAudiencesId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.googleAudiences.get",
                    "path": "v1/googleAudiences/{+googleAudienceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/googleAudiences",
                    "httpMethod": "GET",
                    "id": "displayvideo.googleAudiences.list",
                    "path": "v1/googleAudiences",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "inventorySourceGroups": {
            "methods": {
                "create": {
                    "flatPath": "v1/inventorySourceGroups",
                    "httpMethod": "POST",
                    "id": "displayvideo.inventorySourceGroups.create",
                    "path": "v1/inventorySourceGroups",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "delete": {
                    "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
                    "httpMethod": "DELETE",
                    "id": "displayvideo.inventorySourceGroups.delete",
                    "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "get": {
                    "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.inventorySourceGroups.get",
                    "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/inventorySourceGroups",
                    "httpMethod": "GET",
                    "id": "displayvideo.inventorySourceGroups.list",
                    "path": "v1/inventorySourceGroups",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "patch": {
                    "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
                    "httpMethod": "PATCH",
                    "id": "displayvideo.inventorySourceGroups.patch",
                    "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            },
            "resources": {
                "assignedInventorySources": {
                    "methods": {
                        "bulkEdit": {
                            "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
                            "httpMethod": "POST",
                            "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
                            "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "create": {
                            "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
                            "httpMethod": "POST",
                            "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
                            "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
                            "httpMethod": "DELETE",
                            "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
                            "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
                            "httpMethod": "GET",
                            "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
                            "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    }
                }
            }
        },
        "inventorySources": {
            "methods": {
                "get": {
                    "flatPath": "v1/inventorySources/{inventorySourcesId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.inventorySources.get",
                    "path": "v1/inventorySources/{+inventorySourceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/inventorySources",
                    "httpMethod": "GET",
                    "id": "displayvideo.inventorySources.list",
                    "path": "v1/inventorySources",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            }
        },
        "media": {
            "methods": {
                "download": {
                    "flatPath": "download/{downloadId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.media.download",
                    "path": "download/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video",
                        "https://www.googleapis.com/auth/doubleclickbidmanager"
                    ],
                    "supportsMediaDownload": true
                }
            }
        },
        "partners": {
            "methods": {
                "bulkEditPartnerAssignedTargetingOptions": {
                    "flatPath": "v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions",
                    "httpMethod": "POST",
                    "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions",
                    "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "get": {
                    "flatPath": "v1/partners/{partnersId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.partners.get",
                    "path": "v1/partners/{+partnerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                },
                "list": {
                    "flatPath": "v1/partners",
                    "httpMethod": "GET",
                    "id": "displayvideo.partners.list",
                    "path": "v1/partners",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            },
            "resources": {
                "channels": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/partners/{partnersId}/channels",
                            "httpMethod": "POST",
                            "id": "displayvideo.partners.channels.create",
                            "path": "v1/partners/{+partnerId}/channels",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.partners.channels.get",
                            "path": "v1/partners/{+partnerId}/channels/{+channelId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/partners/{partnersId}/channels",
                            "httpMethod": "GET",
                            "id": "displayvideo.partners.channels.list",
                            "path": "v1/partners/{+partnerId}/channels",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
                            "httpMethod": "PATCH",
                            "id": "displayvideo.partners.channels.patch",
                            "path": "v1/partners/{+partnerId}/channels/{channelId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    },
                    "resources": {
                        "sites": {
                            "methods": {
                                "bulkEdit": {
                                    "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.partners.channels.sites.bulkEdit",
                                    "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "create": {
                                    "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.partners.channels.sites.create",
                                    "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                                    "httpMethod": "DELETE",
                                    "id": "displayvideo.partners.channels.sites.delete",
                                    "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.partners.channels.sites.list",
                                    "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                }
                            }
                        }
                    }
                },
                "targetingTypes": {
                    "resources": {
                        "assignedTargetingOptions": {
                            "methods": {
                                "create": {
                                    "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                                    "httpMethod": "POST",
                                    "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                                    "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                                    "httpMethod": "DELETE",
                                    "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                                    "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                                    "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                                    "httpMethod": "GET",
                                    "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                                    "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/display-video"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "sdfdownloadtasks": {
            "methods": {
                "create": {
                    "flatPath": "v1/sdfdownloadtasks",
                    "httpMethod": "POST",
                    "id": "displayvideo.sdfdownloadtasks.create",
                    "path": "v1/sdfdownloadtasks",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                    ]
                }
            },
            "resources": {
                "operations": {
                    "methods": {
                        "get": {
                            "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.sdfdownloadtasks.operations.get",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video",
                                "https://www.googleapis.com/auth/doubleclickbidmanager"
                            ]
                        }
                    }
                }
            }
        },
        "targetingTypes": {
            "resources": {
                "targetingOptions": {
                    "methods": {
                        "get": {
                            "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
                            "httpMethod": "GET",
                            "id": "displayvideo.targetingTypes.targetingOptions.get",
                            "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions",
                            "httpMethod": "GET",
                            "id": "displayvideo.targetingTypes.targetingOptions.list",
                            "path": "v1/targetingTypes/{+targetingType}/targetingOptions",
                            "scopes": [
                                "https://www.googleapis.com/auth/display-video"
                            ]
                        }
                    }
                }
            }
        },
        "users": {
            "methods": {
                "bulkEditAssignedUserRoles": {
                    "flatPath": "v1/users/{usersId}:bulkEditAssignedUserRoles",
                    "httpMethod": "POST",
                    "id": "displayvideo.users.bulkEditAssignedUserRoles",
                    "path": "v1/users/{+userId}:bulkEditAssignedUserRoles",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video-user-management"
                    ]
                },
                "create": {
                    "flatPath": "v1/users",
                    "httpMethod": "POST",
                    "id": "displayvideo.users.create",
                    "path": "v1/users",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video-user-management"
                    ]
                },
                "delete": {
                    "flatPath": "v1/users/{usersId}",
                    "httpMethod": "DELETE",
                    "id": "displayvideo.users.delete",
                    "path": "v1/users/{+userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video-user-management"
                    ]
                },
                "get": {
                    "flatPath": "v1/users/{usersId}",
                    "httpMethod": "GET",
                    "id": "displayvideo.users.get",
                    "path": "v1/users/{+userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video-user-management"
                    ]
                },
                "list": {
                    "flatPath": "v1/users",
                    "httpMethod": "GET",
                    "id": "displayvideo.users.list",
                    "path": "v1/users",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video-user-management"
                    ]
                },
                "patch": {
                    "flatPath": "v1/users/{usersId}",
                    "httpMethod": "PATCH",
                    "id": "displayvideo.users.patch",
                    "path": "v1/users/{+userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/display-video-user-management"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://displayvideo.googleapis.com/",
    "servicePath": "",
    "title": "Display & Video 360 API",
    "version": "v1",
    "version_module": true
}