{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/documents": {},
                "https://www.googleapis.com/auth/documents.readonly": {},
                "https://www.googleapis.com/auth/drive": {},
                "https://www.googleapis.com/auth/drive.file": {},
                "https://www.googleapis.com/auth/drive.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://docs.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Docs",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/docs/",
    "fullyEncodeReservedExpansion": true,
    "id": "docs:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://docs.mtls.googleapis.com/",
    "name": "docs",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "documents": {
            "methods": {
                "batchUpdate": {
                    "flatPath": "v1/documents/{documentId}:batchUpdate",
                    "httpMethod": "POST",
                    "id": "docs.documents.batchUpdate",
                    "path": "v1/documents/{documentId}:batchUpdate",
                    "scopes": [
                        "https://www.googleapis.com/auth/documents",
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "create": {
                    "flatPath": "v1/documents",
                    "httpMethod": "POST",
                    "id": "docs.documents.create",
                    "path": "v1/documents",
                    "scopes": [
                        "https://www.googleapis.com/auth/documents",
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "flatPath": "v1/documents/{documentId}",
                    "httpMethod": "GET",
                    "id": "docs.documents.get",
                    "path": "v1/documents/{documentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/documents",
                        "https://www.googleapis.com/auth/documents.readonly",
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://docs.googleapis.com/",
    "servicePath": "",
    "title": "Google Docs API",
    "version": "v1",
    "version_module": true
}