{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive": {},
                "https://www.googleapis.com/auth/drive.appdata": {},
                "https://www.googleapis.com/auth/drive.file": {},
                "https://www.googleapis.com/auth/drive.metadata": {},
                "https://www.googleapis.com/auth/drive.metadata.readonly": {},
                "https://www.googleapis.com/auth/drive.photos.readonly": {},
                "https://www.googleapis.com/auth/drive.readonly": {},
                "https://www.googleapis.com/auth/drive.scripts": {}
            }
        }
    },
    "basePath": "/drive/v3/",
    "baseUrl": "https://www.googleapis.com/drive/v3/",
    "batchPath": "batch/drive/v3",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/drive/",
    "id": "drive:v3",
    "kind": "discovery#restDescription",
    "name": "drive",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "about": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.about.get",
                    "path": "about",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "changes": {
            "methods": {
                "getStartPageToken": {
                    "httpMethod": "GET",
                    "id": "drive.changes.getStartPageToken",
                    "path": "changes/startPageToken",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.changes.list",
                    "path": "changes",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsSubscription": true
                },
                "watch": {
                    "httpMethod": "POST",
                    "id": "drive.changes.watch",
                    "path": "changes/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsSubscription": true
                }
            }
        },
        "channels": {
            "methods": {
                "stop": {
                    "httpMethod": "POST",
                    "id": "drive.channels.stop",
                    "path": "channels/stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "create": {
                    "httpMethod": "POST",
                    "id": "drive.comments.create",
                    "path": "files/{fileId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.comments.delete",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.comments.get",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.comments.list",
                    "path": "files/{fileId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.comments.update",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "drives": {
            "methods": {
                "create": {
                    "httpMethod": "POST",
                    "id": "drive.drives.create",
                    "path": "drives",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.drives.delete",
                    "path": "drives/{driveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.drives.get",
                    "path": "drives/{driveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "hide": {
                    "httpMethod": "POST",
                    "id": "drive.drives.hide",
                    "path": "drives/{driveId}/hide",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.drives.list",
                    "path": "drives",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "unhide": {
                    "httpMethod": "POST",
                    "id": "drive.drives.unhide",
                    "path": "drives/{driveId}/unhide",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.drives.update",
                    "path": "drives/{driveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                }
            }
        },
        "files": {
            "methods": {
                "copy": {
                    "httpMethod": "POST",
                    "id": "drive.files.copy",
                    "path": "files/{fileId}/copy",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.photos.readonly"
                    ]
                },
                "create": {
                    "httpMethod": "POST",
                    "id": "drive.files.create",
                    "path": "files",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "supportsMediaUpload": true,
                    "supportsSubscription": true
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.files.delete",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "emptyTrash": {
                    "httpMethod": "DELETE",
                    "id": "drive.files.emptyTrash",
                    "path": "files/trash",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "export": {
                    "httpMethod": "GET",
                    "id": "drive.files.export",
                    "path": "files/{fileId}/export",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true
                },
                "generateIds": {
                    "httpMethod": "GET",
                    "id": "drive.files.generateIds",
                    "path": "files/generateIds",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.files.get",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true,
                    "supportsSubscription": true,
                    "useMediaDownloadService": true
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.files.list",
                    "path": "files",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.files.update",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ],
                    "supportsMediaUpload": true
                },
                "watch": {
                    "httpMethod": "POST",
                    "id": "drive.files.watch",
                    "path": "files/{fileId}/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true,
                    "supportsSubscription": true,
                    "useMediaDownloadService": true
                }
            }
        },
        "permissions": {
            "methods": {
                "create": {
                    "httpMethod": "POST",
                    "id": "drive.permissions.create",
                    "path": "files/{fileId}/permissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.permissions.delete",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.permissions.get",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.permissions.list",
                    "path": "files/{fileId}/permissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.permissions.update",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "replies": {
            "methods": {
                "create": {
                    "httpMethod": "POST",
                    "id": "drive.replies.create",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.replies.delete",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.replies.get",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.replies.list",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.replies.update",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "revisions": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.revisions.delete",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.revisions.get",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true,
                    "useMediaDownloadService": true
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.revisions.list",
                    "path": "files/{fileId}/revisions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.revisions.update",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "teamdrives": {
            "methods": {
                "create": {
                    "httpMethod": "POST",
                    "id": "drive.teamdrives.create",
                    "path": "teamdrives",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.teamdrives.delete",
                    "path": "teamdrives/{teamDriveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "drive.teamdrives.get",
                    "path": "teamdrives/{teamDriveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "drive.teamdrives.list",
                    "path": "teamdrives",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PATCH",
                    "id": "drive.teamdrives.update",
                    "path": "teamdrives/{teamDriveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "drive/v3/",
    "title": "Drive API",
    "version": "v3"
}