{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/fitness.activity.read": {},
                "https://www.googleapis.com/auth/fitness.activity.write": {},
                "https://www.googleapis.com/auth/fitness.blood_glucose.read": {},
                "https://www.googleapis.com/auth/fitness.blood_glucose.write": {},
                "https://www.googleapis.com/auth/fitness.blood_pressure.read": {},
                "https://www.googleapis.com/auth/fitness.blood_pressure.write": {},
                "https://www.googleapis.com/auth/fitness.body.read": {},
                "https://www.googleapis.com/auth/fitness.body.write": {},
                "https://www.googleapis.com/auth/fitness.body_temperature.read": {},
                "https://www.googleapis.com/auth/fitness.body_temperature.write": {},
                "https://www.googleapis.com/auth/fitness.location.read": {},
                "https://www.googleapis.com/auth/fitness.location.write": {},
                "https://www.googleapis.com/auth/fitness.nutrition.read": {},
                "https://www.googleapis.com/auth/fitness.nutrition.write": {},
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read": {},
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write": {},
                "https://www.googleapis.com/auth/fitness.reproductive_health.read": {},
                "https://www.googleapis.com/auth/fitness.reproductive_health.write": {}
            }
        }
    },
    "basePath": "/fitness/v1/users/",
    "baseUrl": "https://www.googleapis.com/fitness/v1/users/",
    "batchPath": "batch/fitness/v1",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/fit/rest/v1/get-started",
    "id": "fitness:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://www.mtls.googleapis.com/",
    "name": "fitness",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "users": {
            "resources": {
                "dataSources": {
                    "methods": {
                        "create": {
                            "flatPath": "{userId}/dataSources",
                            "httpMethod": "POST",
                            "id": "fitness.users.dataSources.create",
                            "path": "{userId}/dataSources",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        },
                        "delete": {
                            "flatPath": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "DELETE",
                            "id": "fitness.users.dataSources.delete",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        },
                        "get": {
                            "flatPath": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "GET",
                            "id": "fitness.users.dataSources.get",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        },
                        "list": {
                            "flatPath": "{userId}/dataSources",
                            "httpMethod": "GET",
                            "id": "fitness.users.dataSources.list",
                            "path": "{userId}/dataSources",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        },
                        "update": {
                            "flatPath": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "PUT",
                            "id": "fitness.users.dataSources.update",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        }
                    },
                    "resources": {
                        "dataPointChanges": {
                            "methods": {
                                "list": {
                                    "flatPath": "{userId}/dataSources/{dataSourceId}/dataPointChanges",
                                    "httpMethod": "GET",
                                    "id": "fitness.users.dataSources.dataPointChanges.list",
                                    "path": "{userId}/dataSources/{dataSourceId}/dataPointChanges",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.read",
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.read",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.read",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.read",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ]
                                }
                            }
                        },
                        "datasets": {
                            "methods": {
                                "delete": {
                                    "flatPath": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "httpMethod": "DELETE",
                                    "id": "fitness.users.dataSources.datasets.delete",
                                    "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ]
                                },
                                "get": {
                                    "flatPath": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "httpMethod": "GET",
                                    "id": "fitness.users.dataSources.datasets.get",
                                    "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.read",
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.read",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.read",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.read",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ]
                                },
                                "patch": {
                                    "flatPath": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "httpMethod": "PATCH",
                                    "id": "fitness.users.dataSources.datasets.patch",
                                    "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ]
                                }
                            }
                        }
                    }
                },
                "dataset": {
                    "methods": {
                        "aggregate": {
                            "flatPath": "{userId}/dataset:aggregate",
                            "httpMethod": "POST",
                            "id": "fitness.users.dataset.aggregate",
                            "path": "{userId}/dataset:aggregate",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        }
                    }
                },
                "sessions": {
                    "methods": {
                        "delete": {
                            "flatPath": "{userId}/sessions/{sessionId}",
                            "httpMethod": "DELETE",
                            "id": "fitness.users.sessions.delete",
                            "path": "{userId}/sessions/{sessionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write"
                            ]
                        },
                        "list": {
                            "flatPath": "{userId}/sessions",
                            "httpMethod": "GET",
                            "id": "fitness.users.sessions.list",
                            "path": "{userId}/sessions",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ]
                        },
                        "update": {
                            "flatPath": "{userId}/sessions/{sessionId}",
                            "httpMethod": "PUT",
                            "id": "fitness.users.sessions.update",
                            "path": "{userId}/sessions/{sessionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "fitness/v1/users/",
    "title": "Fitness API",
    "version": "v1"
}