{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive.appdata": {},
                "https://www.googleapis.com/auth/games": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://games.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Games",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/games/",
    "id": "games:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://games.mtls.googleapis.com/",
    "name": "games",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "achievementDefinitions": {
            "methods": {
                "list": {
                    "flatPath": "games/v1/achievements",
                    "httpMethod": "GET",
                    "id": "games.achievementDefinitions.list",
                    "path": "games/v1/achievements",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "achievements": {
            "methods": {
                "increment": {
                    "flatPath": "games/v1/achievements/{achievementId}/increment",
                    "httpMethod": "POST",
                    "id": "games.achievements.increment",
                    "path": "games/v1/achievements/{achievementId}/increment",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "flatPath": "games/v1/players/{playerId}/achievements",
                    "httpMethod": "GET",
                    "id": "games.achievements.list",
                    "path": "games/v1/players/{playerId}/achievements",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "reveal": {
                    "flatPath": "games/v1/achievements/{achievementId}/reveal",
                    "httpMethod": "POST",
                    "id": "games.achievements.reveal",
                    "path": "games/v1/achievements/{achievementId}/reveal",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "setStepsAtLeast": {
                    "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
                    "httpMethod": "POST",
                    "id": "games.achievements.setStepsAtLeast",
                    "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "unlock": {
                    "flatPath": "games/v1/achievements/{achievementId}/unlock",
                    "httpMethod": "POST",
                    "id": "games.achievements.unlock",
                    "path": "games/v1/achievements/{achievementId}/unlock",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "updateMultiple": {
                    "flatPath": "games/v1/achievements/updateMultiple",
                    "httpMethod": "POST",
                    "id": "games.achievements.updateMultiple",
                    "path": "games/v1/achievements/updateMultiple",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "applications": {
            "methods": {
                "get": {
                    "flatPath": "games/v1/applications/{applicationId}",
                    "httpMethod": "GET",
                    "id": "games.applications.get",
                    "path": "games/v1/applications/{applicationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "played": {
                    "flatPath": "games/v1/applications/played",
                    "httpMethod": "POST",
                    "id": "games.applications.played",
                    "path": "games/v1/applications/played",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "verify": {
                    "flatPath": "games/v1/applications/{applicationId}/verify",
                    "httpMethod": "GET",
                    "id": "games.applications.verify",
                    "path": "games/v1/applications/{applicationId}/verify",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "events": {
            "methods": {
                "listByPlayer": {
                    "flatPath": "games/v1/events",
                    "httpMethod": "GET",
                    "id": "games.events.listByPlayer",
                    "path": "games/v1/events",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "listDefinitions": {
                    "flatPath": "games/v1/eventDefinitions",
                    "httpMethod": "GET",
                    "id": "games.events.listDefinitions",
                    "path": "games/v1/eventDefinitions",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "record": {
                    "flatPath": "games/v1/events",
                    "httpMethod": "POST",
                    "id": "games.events.record",
                    "path": "games/v1/events",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "leaderboards": {
            "methods": {
                "get": {
                    "flatPath": "games/v1/leaderboards/{leaderboardId}",
                    "httpMethod": "GET",
                    "id": "games.leaderboards.get",
                    "path": "games/v1/leaderboards/{leaderboardId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "flatPath": "games/v1/leaderboards",
                    "httpMethod": "GET",
                    "id": "games.leaderboards.list",
                    "path": "games/v1/leaderboards",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "metagame": {
            "methods": {
                "getMetagameConfig": {
                    "flatPath": "games/v1/metagameConfig",
                    "httpMethod": "GET",
                    "id": "games.metagame.getMetagameConfig",
                    "path": "games/v1/metagameConfig",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "listCategoriesByPlayer": {
                    "flatPath": "games/v1/players/{playerId}/categories/{collection}",
                    "httpMethod": "GET",
                    "id": "games.metagame.listCategoriesByPlayer",
                    "path": "games/v1/players/{playerId}/categories/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "players": {
            "methods": {
                "get": {
                    "flatPath": "games/v1/players/{playerId}",
                    "httpMethod": "GET",
                    "id": "games.players.get",
                    "path": "games/v1/players/{playerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "flatPath": "games/v1/players/me/players/{collection}",
                    "httpMethod": "GET",
                    "id": "games.players.list",
                    "path": "games/v1/players/me/players/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "revisions": {
            "methods": {
                "check": {
                    "flatPath": "games/v1/revisions/check",
                    "httpMethod": "GET",
                    "id": "games.revisions.check",
                    "path": "games/v1/revisions/check",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "scores": {
            "methods": {
                "get": {
                    "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
                    "httpMethod": "GET",
                    "id": "games.scores.get",
                    "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
                    "httpMethod": "GET",
                    "id": "games.scores.list",
                    "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "listWindow": {
                    "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
                    "httpMethod": "GET",
                    "id": "games.scores.listWindow",
                    "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "submit": {
                    "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
                    "httpMethod": "POST",
                    "id": "games.scores.submit",
                    "path": "games/v1/leaderboards/{leaderboardId}/scores",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "submitMultiple": {
                    "flatPath": "games/v1/leaderboards/scores",
                    "httpMethod": "POST",
                    "id": "games.scores.submitMultiple",
                    "path": "games/v1/leaderboards/scores",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "snapshots": {
            "methods": {
                "get": {
                    "flatPath": "games/v1/snapshots/{snapshotId}",
                    "httpMethod": "GET",
                    "id": "games.snapshots.get",
                    "path": "games/v1/snapshots/{snapshotId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "flatPath": "games/v1/players/{playerId}/snapshots",
                    "httpMethod": "GET",
                    "id": "games.snapshots.list",
                    "path": "games/v1/players/{playerId}/snapshots",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "stats": {
            "methods": {
                "get": {
                    "flatPath": "games/v1/stats",
                    "httpMethod": "GET",
                    "id": "games.stats.get",
                    "path": "games/v1/stats",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://games.googleapis.com/",
    "servicePath": "",
    "title": "Google Play Game Services",
    "version": "v1"
}