{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive.appdata": {},
                "https://www.googleapis.com/auth/games": {}
            }
        }
    },
    "basePath": "/games/v1/",
    "baseUrl": "https://www.googleapis.com/games/v1/",
    "batchPath": "batch/games/v1",
    "canonicalName": "Games",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/games/services/",
    "id": "games:v1",
    "kind": "discovery#restDescription",
    "name": "games",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "achievementDefinitions": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "games.achievementDefinitions.list",
                    "path": "achievements",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "achievements": {
            "methods": {
                "increment": {
                    "httpMethod": "POST",
                    "id": "games.achievements.increment",
                    "path": "achievements/{achievementId}/increment",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.achievements.list",
                    "path": "players/{playerId}/achievements",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "reveal": {
                    "httpMethod": "POST",
                    "id": "games.achievements.reveal",
                    "path": "achievements/{achievementId}/reveal",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "setStepsAtLeast": {
                    "httpMethod": "POST",
                    "id": "games.achievements.setStepsAtLeast",
                    "path": "achievements/{achievementId}/setStepsAtLeast",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "unlock": {
                    "httpMethod": "POST",
                    "id": "games.achievements.unlock",
                    "path": "achievements/{achievementId}/unlock",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "updateMultiple": {
                    "httpMethod": "POST",
                    "id": "games.achievements.updateMultiple",
                    "path": "achievements/updateMultiple",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "applications": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "games.applications.get",
                    "path": "applications/{applicationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "played": {
                    "httpMethod": "POST",
                    "id": "games.applications.played",
                    "path": "applications/played",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "verify": {
                    "httpMethod": "GET",
                    "id": "games.applications.verify",
                    "path": "applications/{applicationId}/verify",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "events": {
            "methods": {
                "listByPlayer": {
                    "httpMethod": "GET",
                    "id": "games.events.listByPlayer",
                    "path": "events",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "listDefinitions": {
                    "httpMethod": "GET",
                    "id": "games.events.listDefinitions",
                    "path": "eventDefinitions",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "record": {
                    "httpMethod": "POST",
                    "id": "games.events.record",
                    "path": "events",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "leaderboards": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "games.leaderboards.get",
                    "path": "leaderboards/{leaderboardId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.leaderboards.list",
                    "path": "leaderboards",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "metagame": {
            "methods": {
                "getMetagameConfig": {
                    "httpMethod": "GET",
                    "id": "games.metagame.getMetagameConfig",
                    "path": "metagameConfig",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "listCategoriesByPlayer": {
                    "httpMethod": "GET",
                    "id": "games.metagame.listCategoriesByPlayer",
                    "path": "players/{playerId}/categories/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "players": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "games.players.get",
                    "path": "players/{playerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.players.list",
                    "path": "players/me/players/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "pushtokens": {
            "methods": {
                "remove": {
                    "httpMethod": "POST",
                    "id": "games.pushtokens.remove",
                    "path": "pushtokens/remove",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "games.pushtokens.update",
                    "path": "pushtokens",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "revisions": {
            "methods": {
                "check": {
                    "httpMethod": "GET",
                    "id": "games.revisions.check",
                    "path": "revisions/check",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "rooms": {
            "methods": {
                "create": {
                    "httpMethod": "POST",
                    "id": "games.rooms.create",
                    "path": "rooms/create",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "decline": {
                    "httpMethod": "POST",
                    "id": "games.rooms.decline",
                    "path": "rooms/{roomId}/decline",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "dismiss": {
                    "httpMethod": "POST",
                    "id": "games.rooms.dismiss",
                    "path": "rooms/{roomId}/dismiss",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "games.rooms.get",
                    "path": "rooms/{roomId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "join": {
                    "httpMethod": "POST",
                    "id": "games.rooms.join",
                    "path": "rooms/{roomId}/join",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "leave": {
                    "httpMethod": "POST",
                    "id": "games.rooms.leave",
                    "path": "rooms/{roomId}/leave",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.rooms.list",
                    "path": "rooms",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "reportStatus": {
                    "httpMethod": "POST",
                    "id": "games.rooms.reportStatus",
                    "path": "rooms/{roomId}/reportstatus",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "scores": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "games.scores.get",
                    "path": "players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.scores.list",
                    "path": "leaderboards/{leaderboardId}/scores/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "listWindow": {
                    "httpMethod": "GET",
                    "id": "games.scores.listWindow",
                    "path": "leaderboards/{leaderboardId}/window/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "submit": {
                    "httpMethod": "POST",
                    "id": "games.scores.submit",
                    "path": "leaderboards/{leaderboardId}/scores",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "submitMultiple": {
                    "httpMethod": "POST",
                    "id": "games.scores.submitMultiple",
                    "path": "leaderboards/scores",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "snapshots": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "games.snapshots.get",
                    "path": "snapshots/{snapshotId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.snapshots.list",
                    "path": "players/{playerId}/snapshots",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        },
        "turnBasedMatches": {
            "methods": {
                "cancel": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.cancel",
                    "path": "turnbasedmatches/{matchId}/cancel",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "create": {
                    "httpMethod": "POST",
                    "id": "games.turnBasedMatches.create",
                    "path": "turnbasedmatches/create",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "decline": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.decline",
                    "path": "turnbasedmatches/{matchId}/decline",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "dismiss": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.dismiss",
                    "path": "turnbasedmatches/{matchId}/dismiss",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "finish": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.finish",
                    "path": "turnbasedmatches/{matchId}/finish",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "games.turnBasedMatches.get",
                    "path": "turnbasedmatches/{matchId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "join": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.join",
                    "path": "turnbasedmatches/{matchId}/join",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "leave": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.leave",
                    "path": "turnbasedmatches/{matchId}/leave",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "leaveTurn": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.leaveTurn",
                    "path": "turnbasedmatches/{matchId}/leaveTurn",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "games.turnBasedMatches.list",
                    "path": "turnbasedmatches",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "rematch": {
                    "httpMethod": "POST",
                    "id": "games.turnBasedMatches.rematch",
                    "path": "turnbasedmatches/{matchId}/rematch",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "sync": {
                    "httpMethod": "GET",
                    "id": "games.turnBasedMatches.sync",
                    "path": "turnbasedmatches/sync",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                },
                "takeTurn": {
                    "httpMethod": "PUT",
                    "id": "games.turnBasedMatches.takeTurn",
                    "path": "turnbasedmatches/{matchId}/turn",
                    "scopes": [
                        "https://www.googleapis.com/auth/games"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "games/v1/",
    "title": "Google Play Game Services API",
    "version": "v1"
}