{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://mail.google.com/": {},
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {},
                "https://www.googleapis.com/auth/gmail.addons.current.message.action": {},
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {},
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {},
                "https://www.googleapis.com/auth/gmail.compose": {},
                "https://www.googleapis.com/auth/gmail.insert": {},
                "https://www.googleapis.com/auth/gmail.labels": {},
                "https://www.googleapis.com/auth/gmail.metadata": {},
                "https://www.googleapis.com/auth/gmail.modify": {},
                "https://www.googleapis.com/auth/gmail.readonly": {},
                "https://www.googleapis.com/auth/gmail.send": {},
                "https://www.googleapis.com/auth/gmail.settings.basic": {},
                "https://www.googleapis.com/auth/gmail.settings.sharing": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://gmail.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Gmail",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/gmail/api/",
    "id": "gmail:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
    "name": "gmail",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "users": {
            "methods": {
                "getProfile": {
                    "flatPath": "gmail/v1/users/{userId}/profile",
                    "httpMethod": "GET",
                    "id": "gmail.users.getProfile",
                    "path": "gmail/v1/users/{userId}/profile",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.compose",
                        "https://www.googleapis.com/auth/gmail.metadata",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly"
                    ]
                },
                "stop": {
                    "flatPath": "gmail/v1/users/{userId}/stop",
                    "httpMethod": "POST",
                    "id": "gmail.users.stop",
                    "path": "gmail/v1/users/{userId}/stop",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.metadata",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly"
                    ]
                },
                "watch": {
                    "flatPath": "gmail/v1/users/{userId}/watch",
                    "httpMethod": "POST",
                    "id": "gmail.users.watch",
                    "path": "gmail/v1/users/{userId}/watch",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.metadata",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly"
                    ]
                }
            },
            "resources": {
                "drafts": {
                    "methods": {
                        "create": {
                            "flatPath": "gmail/v1/users/{userId}/drafts",
                            "httpMethod": "POST",
                            "id": "gmail.users.drafts.create",
                            "path": "gmail/v1/users/{userId}/drafts",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "delete": {
                            "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.drafts.delete",
                            "path": "gmail/v1/users/{userId}/drafts/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "get": {
                            "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
                            "httpMethod": "GET",
                            "id": "gmail.users.drafts.get",
                            "path": "gmail/v1/users/{userId}/drafts/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "gmail/v1/users/{userId}/drafts",
                            "httpMethod": "GET",
                            "id": "gmail.users.drafts.list",
                            "path": "gmail/v1/users/{userId}/drafts",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "send": {
                            "flatPath": "gmail/v1/users/{userId}/drafts/send",
                            "httpMethod": "POST",
                            "id": "gmail.users.drafts.send",
                            "path": "gmail/v1/users/{userId}/drafts/send",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "update": {
                            "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
                            "httpMethod": "PUT",
                            "id": "gmail.users.drafts.update",
                            "path": "gmail/v1/users/{userId}/drafts/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        }
                    }
                },
                "history": {
                    "methods": {
                        "list": {
                            "flatPath": "gmail/v1/users/{userId}/history",
                            "httpMethod": "GET",
                            "id": "gmail.users.history.list",
                            "path": "gmail/v1/users/{userId}/history",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        }
                    }
                },
                "labels": {
                    "methods": {
                        "create": {
                            "flatPath": "gmail/v1/users/{userId}/labels",
                            "httpMethod": "POST",
                            "id": "gmail.users.labels.create",
                            "path": "gmail/v1/users/{userId}/labels",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "delete": {
                            "flatPath": "gmail/v1/users/{userId}/labels/{id}",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.labels.delete",
                            "path": "gmail/v1/users/{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "get": {
                            "flatPath": "gmail/v1/users/{userId}/labels/{id}",
                            "httpMethod": "GET",
                            "id": "gmail.users.labels.get",
                            "path": "gmail/v1/users/{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "gmail/v1/users/{userId}/labels",
                            "httpMethod": "GET",
                            "id": "gmail.users.labels.list",
                            "path": "gmail/v1/users/{userId}/labels",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "patch": {
                            "flatPath": "gmail/v1/users/{userId}/labels/{id}",
                            "httpMethod": "PATCH",
                            "id": "gmail.users.labels.patch",
                            "path": "gmail/v1/users/{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "update": {
                            "flatPath": "gmail/v1/users/{userId}/labels/{id}",
                            "httpMethod": "PUT",
                            "id": "gmail.users.labels.update",
                            "path": "gmail/v1/users/{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        }
                    }
                },
                "messages": {
                    "methods": {
                        "batchDelete": {
                            "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.batchDelete",
                            "path": "gmail/v1/users/{userId}/messages/batchDelete",
                            "scopes": [
                                "https://mail.google.com/"
                            ]
                        },
                        "batchModify": {
                            "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.batchModify",
                            "path": "gmail/v1/users/{userId}/messages/batchModify",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "delete": {
                            "flatPath": "gmail/v1/users/{userId}/messages/{id}",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.messages.delete",
                            "path": "gmail/v1/users/{userId}/messages/{id}",
                            "scopes": [
                                "https://mail.google.com/"
                            ]
                        },
                        "get": {
                            "flatPath": "gmail/v1/users/{userId}/messages/{id}",
                            "httpMethod": "GET",
                            "id": "gmail.users.messages.get",
                            "path": "gmail/v1/users/{userId}/messages/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "import": {
                            "flatPath": "gmail/v1/users/{userId}/messages/import",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.import",
                            "path": "gmail/v1/users/{userId}/messages/import",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.insert",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "insert": {
                            "flatPath": "gmail/v1/users/{userId}/messages",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.insert",
                            "path": "gmail/v1/users/{userId}/messages",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.insert",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "list": {
                            "flatPath": "gmail/v1/users/{userId}/messages",
                            "httpMethod": "GET",
                            "id": "gmail.users.messages.list",
                            "path": "gmail/v1/users/{userId}/messages",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "modify": {
                            "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.modify",
                            "path": "gmail/v1/users/{userId}/messages/{id}/modify",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "send": {
                            "flatPath": "gmail/v1/users/{userId}/messages/send",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.send",
                            "path": "gmail/v1/users/{userId}/messages/send",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.send"
                            ],
                            "supportsMediaUpload": true
                        },
                        "trash": {
                            "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.trash",
                            "path": "gmail/v1/users/{userId}/messages/{id}/trash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "untrash": {
                            "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.untrash",
                            "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        }
                    },
                    "resources": {
                        "attachments": {
                            "methods": {
                                "get": {
                                    "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.messages.attachments.get",
                                    "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                                        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly"
                                    ]
                                }
                            }
                        }
                    }
                },
                "settings": {
                    "methods": {
                        "getAutoForwarding": {
                            "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
                            "httpMethod": "GET",
                            "id": "gmail.users.settings.getAutoForwarding",
                            "path": "gmail/v1/users/{userId}/settings/autoForwarding",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly",
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "getImap": {
                            "flatPath": "gmail/v1/users/{userId}/settings/imap",
                            "httpMethod": "GET",
                            "id": "gmail.users.settings.getImap",
                            "path": "gmail/v1/users/{userId}/settings/imap",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly",
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "getLanguage": {
                            "flatPath": "gmail/v1/users/{userId}/settings/language",
                            "httpMethod": "GET",
                            "id": "gmail.users.settings.getLanguage",
                            "path": "gmail/v1/users/{userId}/settings/language",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly",
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "getPop": {
                            "flatPath": "gmail/v1/users/{userId}/settings/pop",
                            "httpMethod": "GET",
                            "id": "gmail.users.settings.getPop",
                            "path": "gmail/v1/users/{userId}/settings/pop",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly",
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "getVacation": {
                            "flatPath": "gmail/v1/users/{userId}/settings/vacation",
                            "httpMethod": "GET",
                            "id": "gmail.users.settings.getVacation",
                            "path": "gmail/v1/users/{userId}/settings/vacation",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly",
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "updateAutoForwarding": {
                            "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
                            "httpMethod": "PUT",
                            "id": "gmail.users.settings.updateAutoForwarding",
                            "path": "gmail/v1/users/{userId}/settings/autoForwarding",
                            "scopes": [
                                "https://www.googleapis.com/auth/gmail.settings.sharing"
                            ]
                        },
                        "updateImap": {
                            "flatPath": "gmail/v1/users/{userId}/settings/imap",
                            "httpMethod": "PUT",
                            "id": "gmail.users.settings.updateImap",
                            "path": "gmail/v1/users/{userId}/settings/imap",
                            "scopes": [
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "updateLanguage": {
                            "flatPath": "gmail/v1/users/{userId}/settings/language",
                            "httpMethod": "PUT",
                            "id": "gmail.users.settings.updateLanguage",
                            "path": "gmail/v1/users/{userId}/settings/language",
                            "scopes": [
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "updatePop": {
                            "flatPath": "gmail/v1/users/{userId}/settings/pop",
                            "httpMethod": "PUT",
                            "id": "gmail.users.settings.updatePop",
                            "path": "gmail/v1/users/{userId}/settings/pop",
                            "scopes": [
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        },
                        "updateVacation": {
                            "flatPath": "gmail/v1/users/{userId}/settings/vacation",
                            "httpMethod": "PUT",
                            "id": "gmail.users.settings.updateVacation",
                            "path": "gmail/v1/users/{userId}/settings/vacation",
                            "scopes": [
                                "https://www.googleapis.com/auth/gmail.settings.basic"
                            ]
                        }
                    },
                    "resources": {
                        "delegates": {
                            "methods": {
                                "create": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                                    "httpMethod": "POST",
                                    "id": "gmail.users.settings.delegates.create",
                                    "path": "gmail/v1/users/{userId}/settings/delegates",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                                    "httpMethod": "DELETE",
                                    "id": "gmail.users.settings.delegates.delete",
                                    "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "get": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.delegates.get",
                                    "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "list": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.delegates.list",
                                    "path": "gmail/v1/users/{userId}/settings/delegates",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                }
                            }
                        },
                        "filters": {
                            "methods": {
                                "create": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/filters",
                                    "httpMethod": "POST",
                                    "id": "gmail.users.settings.filters.create",
                                    "path": "gmail/v1/users/{userId}/settings/filters",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                                    "httpMethod": "DELETE",
                                    "id": "gmail.users.settings.filters.delete",
                                    "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "get": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.filters.get",
                                    "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "list": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/filters",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.filters.list",
                                    "path": "gmail/v1/users/{userId}/settings/filters",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                }
                            }
                        },
                        "forwardingAddresses": {
                            "methods": {
                                "create": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                                    "httpMethod": "POST",
                                    "id": "gmail.users.settings.forwardingAddresses.create",
                                    "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                                    "httpMethod": "DELETE",
                                    "id": "gmail.users.settings.forwardingAddresses.delete",
                                    "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "get": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.forwardingAddresses.get",
                                    "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "list": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.forwardingAddresses.list",
                                    "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                }
                            }
                        },
                        "sendAs": {
                            "methods": {
                                "create": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                                    "httpMethod": "POST",
                                    "id": "gmail.users.settings.sendAs.create",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "httpMethod": "DELETE",
                                    "id": "gmail.users.settings.sendAs.delete",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "get": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.sendAs.get",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "list": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.settings.sendAs.list",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly",
                                        "https://www.googleapis.com/auth/gmail.settings.basic"
                                    ]
                                },
                                "patch": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "httpMethod": "PATCH",
                                    "id": "gmail.users.settings.sendAs.patch",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.basic",
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "update": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "httpMethod": "PUT",
                                    "id": "gmail.users.settings.sendAs.update",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.basic",
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                },
                                "verify": {
                                    "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                                    "httpMethod": "POST",
                                    "id": "gmail.users.settings.sendAs.verify",
                                    "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                                    ]
                                }
                            },
                            "resources": {
                                "smimeInfo": {
                                    "methods": {
                                        "delete": {
                                            "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                                            "httpMethod": "DELETE",
                                            "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                                            "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/gmail.settings.basic",
                                                "https://www.googleapis.com/auth/gmail.settings.sharing"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                                            "httpMethod": "GET",
                                            "id": "gmail.users.settings.sendAs.smimeInfo.get",
                                            "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                                            "scopes": [
                                                "https://mail.google.com/",
                                                "https://www.googleapis.com/auth/gmail.modify",
                                                "https://www.googleapis.com/auth/gmail.readonly",
                                                "https://www.googleapis.com/auth/gmail.settings.basic",
                                                "https://www.googleapis.com/auth/gmail.settings.sharing"
                                            ]
                                        },
                                        "insert": {
                                            "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                                            "httpMethod": "POST",
                                            "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                                            "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/gmail.settings.basic",
                                                "https://www.googleapis.com/auth/gmail.settings.sharing"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                                            "httpMethod": "GET",
                                            "id": "gmail.users.settings.sendAs.smimeInfo.list",
                                            "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                                            "scopes": [
                                                "https://mail.google.com/",
                                                "https://www.googleapis.com/auth/gmail.modify",
                                                "https://www.googleapis.com/auth/gmail.readonly",
                                                "https://www.googleapis.com/auth/gmail.settings.basic",
                                                "https://www.googleapis.com/auth/gmail.settings.sharing"
                                            ]
                                        },
                                        "setDefault": {
                                            "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                                            "httpMethod": "POST",
                                            "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                                            "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/gmail.settings.basic",
                                                "https://www.googleapis.com/auth/gmail.settings.sharing"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "threads": {
                    "methods": {
                        "delete": {
                            "flatPath": "gmail/v1/users/{userId}/threads/{id}",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.threads.delete",
                            "path": "gmail/v1/users/{userId}/threads/{id}",
                            "scopes": [
                                "https://mail.google.com/"
                            ]
                        },
                        "get": {
                            "flatPath": "gmail/v1/users/{userId}/threads/{id}",
                            "httpMethod": "GET",
                            "id": "gmail.users.threads.get",
                            "path": "gmail/v1/users/{userId}/threads/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "gmail/v1/users/{userId}/threads",
                            "httpMethod": "GET",
                            "id": "gmail.users.threads.list",
                            "path": "gmail/v1/users/{userId}/threads",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.metadata",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "modify": {
                            "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
                            "httpMethod": "POST",
                            "id": "gmail.users.threads.modify",
                            "path": "gmail/v1/users/{userId}/threads/{id}/modify",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "trash": {
                            "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
                            "httpMethod": "POST",
                            "id": "gmail.users.threads.trash",
                            "path": "gmail/v1/users/{userId}/threads/{id}/trash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "untrash": {
                            "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
                            "httpMethod": "POST",
                            "id": "gmail.users.threads.untrash",
                            "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://gmail.googleapis.com/",
    "servicePath": "",
    "title": "Gmail API",
    "version": "v1"
}