{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/glass.location": {},
                "https://www.googleapis.com/auth/glass.timeline": {}
            }
        }
    },
    "basePath": "/mirror/v1/",
    "baseUrl": "https://www.googleapis.com/mirror/v1/",
    "batchPath": "batch/mirror/v1",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/glass",
    "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/beqzjzqqUhkCytAlD4Bh0NthVOg\"",
    "id": "mirror:v1",
    "kind": "discovery#restDescription",
    "labels": [
        "limited_availability"
    ],
    "name": "mirror",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "accounts": {
            "methods": {
                "insert": {
                    "httpMethod": "POST",
                    "id": "mirror.accounts.insert",
                    "path": "accounts/{userToken}/{accountType}/{accountName}"
                }
            }
        },
        "contacts": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "mirror.contacts.delete",
                    "path": "contacts/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "mirror.contacts.get",
                    "path": "contacts/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "mirror.contacts.insert",
                    "path": "contacts",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "mirror.contacts.list",
                    "path": "contacts",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "mirror.contacts.patch",
                    "path": "contacts/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "mirror.contacts.update",
                    "path": "contacts/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                }
            }
        },
        "locations": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "mirror.locations.get",
                    "path": "locations/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "mirror.locations.list",
                    "path": "locations",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                }
            }
        },
        "settings": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "mirror.settings.get",
                    "path": "settings/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                }
            }
        },
        "subscriptions": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "mirror.subscriptions.delete",
                    "path": "subscriptions/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "mirror.subscriptions.insert",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "mirror.subscriptions.list",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "mirror.subscriptions.update",
                    "path": "subscriptions/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                }
            }
        },
        "timeline": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "mirror.timeline.delete",
                    "path": "timeline/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "mirror.timeline.get",
                    "path": "timeline/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "mirror.timeline.insert",
                    "path": "timeline",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ],
                    "supportsMediaUpload": true
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "mirror.timeline.list",
                    "path": "timeline",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "mirror.timeline.patch",
                    "path": "timeline/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "mirror.timeline.update",
                    "path": "timeline/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/glass.location",
                        "https://www.googleapis.com/auth/glass.timeline"
                    ],
                    "supportsMediaUpload": true
                }
            },
            "resources": {
                "attachments": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "id": "mirror.timeline.attachments.delete",
                            "path": "timeline/{itemId}/attachments/{attachmentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/glass.timeline"
                            ]
                        },
                        "get": {
                            "httpMethod": "GET",
                            "id": "mirror.timeline.attachments.get",
                            "path": "timeline/{itemId}/attachments/{attachmentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/glass.timeline"
                            ],
                            "supportsMediaDownload": true
                        },
                        "insert": {
                            "httpMethod": "POST",
                            "id": "mirror.timeline.attachments.insert",
                            "path": "timeline/{itemId}/attachments",
                            "scopes": [
                                "https://www.googleapis.com/auth/glass.timeline"
                            ],
                            "supportsMediaUpload": true
                        },
                        "list": {
                            "httpMethod": "GET",
                            "id": "mirror.timeline.attachments.list",
                            "path": "timeline/{itemId}/attachments",
                            "scopes": [
                                "https://www.googleapis.com/auth/glass.timeline"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "mirror/v1/",
    "title": "Google Mirror API",
    "version": "v1"
}