{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/contacts": {},
                "https://www.googleapis.com/auth/contacts.other.readonly": {},
                "https://www.googleapis.com/auth/contacts.readonly": {},
                "https://www.googleapis.com/auth/directory.readonly": {},
                "https://www.googleapis.com/auth/user.addresses.read": {},
                "https://www.googleapis.com/auth/user.birthday.read": {},
                "https://www.googleapis.com/auth/user.emails.read": {},
                "https://www.googleapis.com/auth/user.gender.read": {},
                "https://www.googleapis.com/auth/user.organization.read": {},
                "https://www.googleapis.com/auth/user.phonenumbers.read": {},
                "https://www.googleapis.com/auth/userinfo.email": {},
                "https://www.googleapis.com/auth/userinfo.profile": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://people.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "People Service",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/people/",
    "id": "people:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://people.mtls.googleapis.com/",
    "name": "people",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "contactGroups": {
            "methods": {
                "batchGet": {
                    "flatPath": "v1/contactGroups:batchGet",
                    "httpMethod": "GET",
                    "id": "people.contactGroups.batchGet",
                    "path": "v1/contactGroups:batchGet",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly"
                    ]
                },
                "create": {
                    "flatPath": "v1/contactGroups",
                    "httpMethod": "POST",
                    "id": "people.contactGroups.create",
                    "path": "v1/contactGroups",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                },
                "delete": {
                    "flatPath": "v1/contactGroups/{contactGroupsId}",
                    "httpMethod": "DELETE",
                    "id": "people.contactGroups.delete",
                    "path": "v1/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                },
                "get": {
                    "flatPath": "v1/contactGroups/{contactGroupsId}",
                    "httpMethod": "GET",
                    "id": "people.contactGroups.get",
                    "path": "v1/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v1/contactGroups",
                    "httpMethod": "GET",
                    "id": "people.contactGroups.list",
                    "path": "v1/contactGroups",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly"
                    ]
                },
                "update": {
                    "flatPath": "v1/contactGroups/{contactGroupsId}",
                    "httpMethod": "PUT",
                    "id": "people.contactGroups.update",
                    "path": "v1/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                }
            },
            "resources": {
                "members": {
                    "methods": {
                        "modify": {
                            "flatPath": "v1/contactGroups/{contactGroupsId}/members:modify",
                            "httpMethod": "POST",
                            "id": "people.contactGroups.members.modify",
                            "path": "v1/{+resourceName}/members:modify",
                            "scopes": [
                                "https://www.googleapis.com/auth/contacts"
                            ]
                        }
                    }
                }
            }
        },
        "otherContacts": {
            "methods": {
                "copyOtherContactToMyContactsGroup": {
                    "flatPath": "v1/otherContacts/{otherContactsId}:copyOtherContactToMyContactsGroup",
                    "httpMethod": "POST",
                    "id": "people.otherContacts.copyOtherContactToMyContactsGroup",
                    "path": "v1/{+resourceName}:copyOtherContactToMyContactsGroup",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.other.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v1/otherContacts",
                    "httpMethod": "GET",
                    "id": "people.otherContacts.list",
                    "path": "v1/otherContacts",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts.other.readonly"
                    ]
                }
            }
        },
        "people": {
            "methods": {
                "createContact": {
                    "flatPath": "v1/people:createContact",
                    "httpMethod": "POST",
                    "id": "people.people.createContact",
                    "path": "v1/people:createContact",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                },
                "deleteContact": {
                    "flatPath": "v1/people/{peopleId}:deleteContact",
                    "httpMethod": "DELETE",
                    "id": "people.people.deleteContact",
                    "path": "v1/{+resourceName}:deleteContact",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                },
                "deleteContactPhoto": {
                    "flatPath": "v1/people/{peopleId}:deleteContactPhoto",
                    "httpMethod": "DELETE",
                    "id": "people.people.deleteContactPhoto",
                    "path": "v1/{+resourceName}:deleteContactPhoto",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                },
                "get": {
                    "flatPath": "v1/people/{peopleId}",
                    "httpMethod": "GET",
                    "id": "people.people.get",
                    "path": "v1/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/directory.readonly",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.gender.read",
                        "https://www.googleapis.com/auth/user.organization.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ]
                },
                "getBatchGet": {
                    "flatPath": "v1/people:batchGet",
                    "httpMethod": "GET",
                    "id": "people.people.getBatchGet",
                    "path": "v1/people:batchGet",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/directory.readonly",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.gender.read",
                        "https://www.googleapis.com/auth/user.organization.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ]
                },
                "listDirectoryPeople": {
                    "flatPath": "v1/people:listDirectoryPeople",
                    "httpMethod": "GET",
                    "id": "people.people.listDirectoryPeople",
                    "path": "v1/people:listDirectoryPeople",
                    "scopes": [
                        "https://www.googleapis.com/auth/directory.readonly"
                    ]
                },
                "searchDirectoryPeople": {
                    "flatPath": "v1/people:searchDirectoryPeople",
                    "httpMethod": "GET",
                    "id": "people.people.searchDirectoryPeople",
                    "path": "v1/people:searchDirectoryPeople",
                    "scopes": [
                        "https://www.googleapis.com/auth/directory.readonly"
                    ]
                },
                "updateContact": {
                    "flatPath": "v1/people/{peopleId}:updateContact",
                    "httpMethod": "PATCH",
                    "id": "people.people.updateContact",
                    "path": "v1/{+resourceName}:updateContact",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                },
                "updateContactPhoto": {
                    "flatPath": "v1/people/{peopleId}:updateContactPhoto",
                    "httpMethod": "PATCH",
                    "id": "people.people.updateContactPhoto",
                    "path": "v1/{+resourceName}:updateContactPhoto",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts"
                    ]
                }
            },
            "resources": {
                "connections": {
                    "methods": {
                        "list": {
                            "flatPath": "v1/people/{peopleId}/connections",
                            "httpMethod": "GET",
                            "id": "people.people.connections.list",
                            "path": "v1/{+resourceName}/connections",
                            "scopes": [
                                "https://www.googleapis.com/auth/contacts",
                                "https://www.googleapis.com/auth/contacts.readonly"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://people.googleapis.com/",
    "servicePath": "",
    "title": "People API",
    "version": "v1",
    "version_module": true
}