{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/apps.order": {},
                "https://www.googleapis.com/auth/apps.order.readonly": {}
            }
        }
    },
    "basePath": "/apps/reseller/v1/",
    "baseUrl": "https://www.googleapis.com/apps/reseller/v1/",
    "batchPath": "batch/reseller/v1",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/google-apps/reseller/",
    "id": "reseller:v1",
    "kind": "discovery#restDescription",
    "labels": [
        "limited_availability"
    ],
    "name": "reseller",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "customers": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "id": "reseller.customers.get",
                    "path": "customers/{customerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "reseller.customers.insert",
                    "path": "customers",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "reseller.customers.patch",
                    "path": "customers/{customerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "reseller.customers.update",
                    "path": "customers/{customerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                }
            }
        },
        "resellernotify": {
            "methods": {
                "getwatchdetails": {
                    "httpMethod": "GET",
                    "id": "reseller.resellernotify.getwatchdetails",
                    "path": "resellernotify/getwatchdetails",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "register": {
                    "httpMethod": "POST",
                    "id": "reseller.resellernotify.register",
                    "path": "resellernotify/register",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "unregister": {
                    "httpMethod": "POST",
                    "id": "reseller.resellernotify.unregister",
                    "path": "resellernotify/unregister",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                }
            }
        },
        "subscriptions": {
            "methods": {
                "activate": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.activate",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/activate",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "changePlan": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.changePlan",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "changeRenewalSettings": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.changeRenewalSettings",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "changeSeats": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.changeSeats",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "reseller.subscriptions.delete",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "reseller.subscriptions.get",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.insert",
                    "path": "customers/{customerId}/subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "reseller.subscriptions.list",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "startPaidService": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.startPaidService",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "suspend": {
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.suspend",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/suspend",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "apps/reseller/v1/",
    "title": "Enterprise Apps Reseller API",
    "version": "v1"
}