{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://mail.google.com/": {},
                "https://www.google.com/calendar/feeds": {},
                "https://www.google.com/m8/feeds": {},
                "https://www.googleapis.com/auth/admin.directory.group": {},
                "https://www.googleapis.com/auth/admin.directory.user": {},
                "https://www.googleapis.com/auth/documents": {},
                "https://www.googleapis.com/auth/drive": {},
                "https://www.googleapis.com/auth/forms": {},
                "https://www.googleapis.com/auth/forms.currentonly": {},
                "https://www.googleapis.com/auth/groups": {},
                "https://www.googleapis.com/auth/script.deployments": {},
                "https://www.googleapis.com/auth/script.deployments.readonly": {},
                "https://www.googleapis.com/auth/script.metrics": {},
                "https://www.googleapis.com/auth/script.processes": {},
                "https://www.googleapis.com/auth/script.projects": {},
                "https://www.googleapis.com/auth/script.projects.readonly": {},
                "https://www.googleapis.com/auth/spreadsheets": {},
                "https://www.googleapis.com/auth/userinfo.email": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://script.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Script",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/apps-script/api/",
    "fullyEncodeReservedExpansion": true,
    "id": "script:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://script.mtls.googleapis.com/",
    "name": "script",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "processes": {
            "methods": {
                "list": {
                    "flatPath": "v1/processes",
                    "httpMethod": "GET",
                    "id": "script.processes.list",
                    "path": "v1/processes",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.processes"
                    ]
                },
                "listScriptProcesses": {
                    "flatPath": "v1/processes:listScriptProcesses",
                    "httpMethod": "GET",
                    "id": "script.processes.listScriptProcesses",
                    "path": "v1/processes:listScriptProcesses",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.processes"
                    ]
                }
            }
        },
        "projects": {
            "methods": {
                "create": {
                    "flatPath": "v1/projects",
                    "httpMethod": "POST",
                    "id": "script.projects.create",
                    "path": "v1/projects",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.projects"
                    ]
                },
                "get": {
                    "flatPath": "v1/projects/{scriptId}",
                    "httpMethod": "GET",
                    "id": "script.projects.get",
                    "path": "v1/projects/{scriptId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.projects",
                        "https://www.googleapis.com/auth/script.projects.readonly"
                    ]
                },
                "getContent": {
                    "flatPath": "v1/projects/{scriptId}/content",
                    "httpMethod": "GET",
                    "id": "script.projects.getContent",
                    "path": "v1/projects/{scriptId}/content",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.projects",
                        "https://www.googleapis.com/auth/script.projects.readonly"
                    ]
                },
                "getMetrics": {
                    "flatPath": "v1/projects/{scriptId}/metrics",
                    "httpMethod": "GET",
                    "id": "script.projects.getMetrics",
                    "path": "v1/projects/{scriptId}/metrics",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.metrics"
                    ]
                },
                "updateContent": {
                    "flatPath": "v1/projects/{scriptId}/content",
                    "httpMethod": "PUT",
                    "id": "script.projects.updateContent",
                    "path": "v1/projects/{scriptId}/content",
                    "scopes": [
                        "https://www.googleapis.com/auth/script.projects"
                    ]
                }
            },
            "resources": {
                "deployments": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/projects/{scriptId}/deployments",
                            "httpMethod": "POST",
                            "id": "script.projects.deployments.create",
                            "path": "v1/projects/{scriptId}/deployments",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.deployments"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
                            "httpMethod": "DELETE",
                            "id": "script.projects.deployments.delete",
                            "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.deployments"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
                            "httpMethod": "GET",
                            "id": "script.projects.deployments.get",
                            "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.deployments",
                                "https://www.googleapis.com/auth/script.deployments.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/projects/{scriptId}/deployments",
                            "httpMethod": "GET",
                            "id": "script.projects.deployments.list",
                            "path": "v1/projects/{scriptId}/deployments",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.deployments",
                                "https://www.googleapis.com/auth/script.deployments.readonly"
                            ]
                        },
                        "update": {
                            "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
                            "httpMethod": "PUT",
                            "id": "script.projects.deployments.update",
                            "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.deployments"
                            ]
                        }
                    }
                },
                "versions": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/projects/{scriptId}/versions",
                            "httpMethod": "POST",
                            "id": "script.projects.versions.create",
                            "path": "v1/projects/{scriptId}/versions",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.projects"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
                            "httpMethod": "GET",
                            "id": "script.projects.versions.get",
                            "path": "v1/projects/{scriptId}/versions/{versionNumber}",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.projects",
                                "https://www.googleapis.com/auth/script.projects.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/projects/{scriptId}/versions",
                            "httpMethod": "GET",
                            "id": "script.projects.versions.list",
                            "path": "v1/projects/{scriptId}/versions",
                            "scopes": [
                                "https://www.googleapis.com/auth/script.projects",
                                "https://www.googleapis.com/auth/script.projects.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "scripts": {
            "methods": {
                "run": {
                    "flatPath": "v1/scripts/{scriptId}:run",
                    "httpMethod": "POST",
                    "id": "script.scripts.run",
                    "path": "v1/scripts/{scriptId}:run",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.google.com/calendar/feeds",
                        "https://www.google.com/m8/feeds",
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/documents",
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/forms",
                        "https://www.googleapis.com/auth/forms.currentonly",
                        "https://www.googleapis.com/auth/groups",
                        "https://www.googleapis.com/auth/spreadsheets",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://script.googleapis.com/",
    "servicePath": "",
    "title": "Apps Script API",
    "version": "v1"
}