{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive": {},
                "https://www.googleapis.com/auth/drive.file": {},
                "https://www.googleapis.com/auth/drive.readonly": {},
                "https://www.googleapis.com/auth/spreadsheets": {},
                "https://www.googleapis.com/auth/spreadsheets.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://sheets.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Sheets",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/sheets/",
    "fullyEncodeReservedExpansion": true,
    "id": "sheets:v4",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://sheets.mtls.googleapis.com/",
    "name": "sheets",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "spreadsheets": {
            "methods": {
                "batchUpdate": {
                    "flatPath": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
                    "httpMethod": "POST",
                    "id": "sheets.spreadsheets.batchUpdate",
                    "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/spreadsheets"
                    ]
                },
                "create": {
                    "flatPath": "v4/spreadsheets",
                    "httpMethod": "POST",
                    "id": "sheets.spreadsheets.create",
                    "path": "v4/spreadsheets",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/spreadsheets"
                    ]
                },
                "get": {
                    "flatPath": "v4/spreadsheets/{spreadsheetId}",
                    "httpMethod": "GET",
                    "id": "sheets.spreadsheets.get",
                    "path": "v4/spreadsheets/{spreadsheetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly",
                        "https://www.googleapis.com/auth/spreadsheets",
                        "https://www.googleapis.com/auth/spreadsheets.readonly"
                    ]
                },
                "getByDataFilter": {
                    "flatPath": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
                    "httpMethod": "POST",
                    "id": "sheets.spreadsheets.getByDataFilter",
                    "path": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/spreadsheets"
                    ]
                }
            },
            "resources": {
                "developerMetadata": {
                    "methods": {
                        "get": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
                            "httpMethod": "GET",
                            "id": "sheets.spreadsheets.developerMetadata.get",
                            "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "search": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.developerMetadata.search",
                            "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        }
                    }
                },
                "sheets": {
                    "methods": {
                        "copyTo": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.sheets.copyTo",
                            "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        }
                    }
                },
                "values": {
                    "methods": {
                        "append": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.append",
                            "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "batchClear": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.batchClear",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "batchClearByDataFilter": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.batchClearByDataFilter",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "batchGet": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
                            "httpMethod": "GET",
                            "id": "sheets.spreadsheets.values.batchGet",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/drive.readonly",
                                "https://www.googleapis.com/auth/spreadsheets",
                                "https://www.googleapis.com/auth/spreadsheets.readonly"
                            ]
                        },
                        "batchGetByDataFilter": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.batchGetByDataFilter",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "batchUpdate": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.batchUpdate",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "batchUpdateByDataFilter": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.batchUpdateByDataFilter",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "clear": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.clear",
                            "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "get": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
                            "httpMethod": "GET",
                            "id": "sheets.spreadsheets.values.get",
                            "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/drive.readonly",
                                "https://www.googleapis.com/auth/spreadsheets",
                                "https://www.googleapis.com/auth/spreadsheets.readonly"
                            ]
                        },
                        "update": {
                            "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
                            "httpMethod": "PUT",
                            "id": "sheets.spreadsheets.values.update",
                            "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://sheets.googleapis.com/",
    "servicePath": "",
    "title": "Google Sheets API",
    "version": "v4",
    "version_module": true
}