{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/siteverification": {},
                "https://www.googleapis.com/auth/siteverification.verify_only": {}
            }
        }
    },
    "basePath": "/siteVerification/v1/",
    "baseUrl": "https://www.googleapis.com/siteVerification/v1/",
    "batchPath": "batch/siteVerification/v1",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/site-verification/",
    "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/ffKkQHIfwnRAzOSRWAT_SYBS6HY\"",
    "id": "siteVerification:v1",
    "kind": "discovery#restDescription",
    "name": "siteVerification",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "webResource": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "siteVerification.webResource.delete",
                    "path": "webResource/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "siteVerification.webResource.get",
                    "path": "webResource/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification"
                    ]
                },
                "getToken": {
                    "httpMethod": "POST",
                    "id": "siteVerification.webResource.getToken",
                    "path": "token",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification",
                        "https://www.googleapis.com/auth/siteverification.verify_only"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "siteVerification.webResource.insert",
                    "path": "webResource",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification",
                        "https://www.googleapis.com/auth/siteverification.verify_only"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "siteVerification.webResource.list",
                    "path": "webResource",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification"
                    ]
                },
                "patch": {
                    "httpMethod": "PATCH",
                    "id": "siteVerification.webResource.patch",
                    "path": "webResource/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "siteVerification.webResource.update",
                    "path": "webResource/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/siteverification"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "siteVerification/v1/",
    "title": "Google Site Verification API",
    "version": "v1"
}