{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive": {},
                "https://www.googleapis.com/auth/drive.file": {},
                "https://www.googleapis.com/auth/drive.readonly": {},
                "https://www.googleapis.com/auth/presentations": {},
                "https://www.googleapis.com/auth/presentations.readonly": {},
                "https://www.googleapis.com/auth/spreadsheets": {},
                "https://www.googleapis.com/auth/spreadsheets.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://slides.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Slides",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/slides/",
    "fullyEncodeReservedExpansion": true,
    "id": "slides:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://slides.mtls.googleapis.com/",
    "name": "slides",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "presentations": {
            "methods": {
                "batchUpdate": {
                    "flatPath": "v1/presentations/{presentationId}:batchUpdate",
                    "httpMethod": "POST",
                    "id": "slides.presentations.batchUpdate",
                    "path": "v1/presentations/{presentationId}:batchUpdate",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly",
                        "https://www.googleapis.com/auth/presentations",
                        "https://www.googleapis.com/auth/spreadsheets",
                        "https://www.googleapis.com/auth/spreadsheets.readonly"
                    ]
                },
                "create": {
                    "flatPath": "v1/presentations",
                    "httpMethod": "POST",
                    "id": "slides.presentations.create",
                    "path": "v1/presentations",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/presentations"
                    ]
                },
                "get": {
                    "flatPath": "v1/presentations/{presentationsId}",
                    "httpMethod": "GET",
                    "id": "slides.presentations.get",
                    "path": "v1/presentations/{+presentationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly",
                        "https://www.googleapis.com/auth/presentations",
                        "https://www.googleapis.com/auth/presentations.readonly"
                    ]
                }
            },
            "resources": {
                "pages": {
                    "methods": {
                        "get": {
                            "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}",
                            "httpMethod": "GET",
                            "id": "slides.presentations.pages.get",
                            "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/drive.readonly",
                                "https://www.googleapis.com/auth/presentations",
                                "https://www.googleapis.com/auth/presentations.readonly"
                            ]
                        },
                        "getThumbnail": {
                            "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
                            "httpMethod": "GET",
                            "id": "slides.presentations.pages.getThumbnail",
                            "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.file",
                                "https://www.googleapis.com/auth/drive.readonly",
                                "https://www.googleapis.com/auth/presentations",
                                "https://www.googleapis.com/auth/presentations.readonly"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://slides.googleapis.com/",
    "servicePath": "",
    "title": "Google Slides API",
    "version": "v1",
    "version_module": true
}