{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud-platform": {},
                "https://www.googleapis.com/auth/source.full_control": {},
                "https://www.googleapis.com/auth/source.read_only": {},
                "https://www.googleapis.com/auth/source.read_write": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://sourcerepo.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Cloud Source Repositories",
    "discoveryVersion": "v1",
    "documentationLink": "https://cloud.google.com/source-repositories/docs/apis",
    "fullyEncodeReservedExpansion": true,
    "id": "sourcerepo:v1",
    "kind": "discovery#restDescription",
    "name": "sourcerepo",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "projects": {
            "methods": {
                "getConfig": {
                    "flatPath": "v1/projects/{projectsId}/config",
                    "httpMethod": "GET",
                    "id": "sourcerepo.projects.getConfig",
                    "path": "v1/{+name}/config",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "updateConfig": {
                    "flatPath": "v1/projects/{projectsId}/config",
                    "httpMethod": "PATCH",
                    "id": "sourcerepo.projects.updateConfig",
                    "path": "v1/{+name}/config",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                }
            },
            "resources": {
                "repos": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/projects/{projectsId}/repos",
                            "httpMethod": "POST",
                            "id": "sourcerepo.projects.repos.create",
                            "path": "v1/{+parent}/repos",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
                            "httpMethod": "DELETE",
                            "id": "sourcerepo.projects.repos.delete",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
                            "httpMethod": "GET",
                            "id": "sourcerepo.projects.repos.get",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control",
                                "https://www.googleapis.com/auth/source.read_only",
                                "https://www.googleapis.com/auth/source.read_write"
                            ]
                        },
                        "getIamPolicy": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}:getIamPolicy",
                            "httpMethod": "GET",
                            "id": "sourcerepo.projects.repos.getIamPolicy",
                            "path": "v1/{+resource}:getIamPolicy",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control",
                                "https://www.googleapis.com/auth/source.read_only",
                                "https://www.googleapis.com/auth/source.read_write"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/projects/{projectsId}/repos",
                            "httpMethod": "GET",
                            "id": "sourcerepo.projects.repos.list",
                            "path": "v1/{+name}/repos",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control",
                                "https://www.googleapis.com/auth/source.read_only",
                                "https://www.googleapis.com/auth/source.read_write"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
                            "httpMethod": "PATCH",
                            "id": "sourcerepo.projects.repos.patch",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "setIamPolicy": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}:setIamPolicy",
                            "httpMethod": "POST",
                            "id": "sourcerepo.projects.repos.setIamPolicy",
                            "path": "v1/{+resource}:setIamPolicy",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control"
                            ]
                        },
                        "sync": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}:sync",
                            "httpMethod": "POST",
                            "id": "sourcerepo.projects.repos.sync",
                            "path": "v1/{+name}:sync",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform"
                            ]
                        },
                        "testIamPermissions": {
                            "flatPath": "v1/projects/{projectsId}/repos/{reposId}:testIamPermissions",
                            "httpMethod": "POST",
                            "id": "sourcerepo.projects.repos.testIamPermissions",
                            "path": "v1/{+resource}:testIamPermissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/source.full_control",
                                "https://www.googleapis.com/auth/source.read_only",
                                "https://www.googleapis.com/auth/source.read_write"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://sourcerepo.googleapis.com/",
    "servicePath": "",
    "title": "Cloud Source Repositories API",
    "version": "v1",
    "version_module": true
}