{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud-platform": {},
                "https://www.googleapis.com/auth/spanner.admin": {},
                "https://www.googleapis.com/auth/spanner.data": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://spanner.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Spanner",
    "discoveryVersion": "v1",
    "documentationLink": "https://cloud.google.com/spanner/",
    "fullyEncodeReservedExpansion": true,
    "id": "spanner:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://spanner.mtls.googleapis.com/",
    "name": "spanner",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "projects": {
            "resources": {
                "instanceConfigs": {
                    "methods": {
                        "get": {
                            "flatPath": "v1/projects/{projectsId}/instanceConfigs/{instanceConfigsId}",
                            "httpMethod": "GET",
                            "id": "spanner.projects.instanceConfigs.get",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/projects/{projectsId}/instanceConfigs",
                            "httpMethod": "GET",
                            "id": "spanner.projects.instanceConfigs.list",
                            "path": "v1/{+parent}/instanceConfigs",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        }
                    }
                },
                "instances": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/projects/{projectsId}/instances",
                            "httpMethod": "POST",
                            "id": "spanner.projects.instances.create",
                            "path": "v1/{+parent}/instances",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "DELETE",
                            "id": "spanner.projects.instances.delete",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "GET",
                            "id": "spanner.projects.instances.get",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "getIamPolicy": {
                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
                            "httpMethod": "POST",
                            "id": "spanner.projects.instances.getIamPolicy",
                            "path": "v1/{+resource}:getIamPolicy",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/projects/{projectsId}/instances",
                            "httpMethod": "GET",
                            "id": "spanner.projects.instances.list",
                            "path": "v1/{+parent}/instances",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "patch": {
                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}",
                            "httpMethod": "PATCH",
                            "id": "spanner.projects.instances.patch",
                            "path": "v1/{+name}",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "setIamPolicy": {
                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
                            "httpMethod": "POST",
                            "id": "spanner.projects.instances.setIamPolicy",
                            "path": "v1/{+resource}:setIamPolicy",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        },
                        "testIamPermissions": {
                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
                            "httpMethod": "POST",
                            "id": "spanner.projects.instances.testIamPermissions",
                            "path": "v1/{+resource}:testIamPermissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/spanner.admin"
                            ]
                        }
                    },
                    "resources": {
                        "backupOperations": {
                            "methods": {
                                "list": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backupOperations",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.backupOperations.list",
                                    "path": "v1/{+parent}/backupOperations",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                }
                            }
                        },
                        "backups": {
                            "methods": {
                                "create": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.backups.create",
                                    "path": "v1/{+parent}/backups",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}",
                                    "httpMethod": "DELETE",
                                    "id": "spanner.projects.instances.backups.delete",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.backups.get",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "getIamPolicy": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}:getIamPolicy",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.backups.getIamPolicy",
                                    "path": "v1/{+resource}:getIamPolicy",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.backups.list",
                                    "path": "v1/{+parent}/backups",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "patch": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}",
                                    "httpMethod": "PATCH",
                                    "id": "spanner.projects.instances.backups.patch",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "setIamPolicy": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}:setIamPolicy",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.backups.setIamPolicy",
                                    "path": "v1/{+resource}:setIamPolicy",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "testIamPermissions": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}:testIamPermissions",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.backups.testIamPermissions",
                                    "path": "v1/{+resource}:testIamPermissions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                }
                            },
                            "resources": {
                                "operations": {
                                    "methods": {
                                        "cancel": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}/operations/{operationsId}:cancel",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.backups.operations.cancel",
                                            "path": "v1/{+name}:cancel",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}/operations/{operationsId}",
                                            "httpMethod": "DELETE",
                                            "id": "spanner.projects.instances.backups.operations.delete",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}/operations/{operationsId}",
                                            "httpMethod": "GET",
                                            "id": "spanner.projects.instances.backups.operations.get",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/backups/{backupsId}/operations",
                                            "httpMethod": "GET",
                                            "id": "spanner.projects.instances.backups.operations.list",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "databaseOperations": {
                            "methods": {
                                "list": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databaseOperations",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.databaseOperations.list",
                                    "path": "v1/{+parent}/databaseOperations",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                }
                            }
                        },
                        "databases": {
                            "methods": {
                                "create": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.databases.create",
                                    "path": "v1/{+parent}/databases",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "dropDatabase": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}",
                                    "httpMethod": "DELETE",
                                    "id": "spanner.projects.instances.databases.dropDatabase",
                                    "path": "v1/{+database}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.databases.get",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "getDdl": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/ddl",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.databases.getDdl",
                                    "path": "v1/{+database}/ddl",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "getIamPolicy": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}:getIamPolicy",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.databases.getIamPolicy",
                                    "path": "v1/{+resource}:getIamPolicy",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.databases.list",
                                    "path": "v1/{+parent}/databases",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "restore": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases:restore",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.databases.restore",
                                    "path": "v1/{+parent}/databases:restore",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "setIamPolicy": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}:setIamPolicy",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.databases.setIamPolicy",
                                    "path": "v1/{+resource}:setIamPolicy",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "testIamPermissions": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}:testIamPermissions",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.databases.testIamPermissions",
                                    "path": "v1/{+resource}:testIamPermissions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "updateDdl": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/ddl",
                                    "httpMethod": "PATCH",
                                    "id": "spanner.projects.instances.databases.updateDdl",
                                    "path": "v1/{+database}/ddl",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                }
                            },
                            "resources": {
                                "operations": {
                                    "methods": {
                                        "cancel": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/operations/{operationsId}:cancel",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.operations.cancel",
                                            "path": "v1/{+name}:cancel",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/operations/{operationsId}",
                                            "httpMethod": "DELETE",
                                            "id": "spanner.projects.instances.databases.operations.delete",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/operations/{operationsId}",
                                            "httpMethod": "GET",
                                            "id": "spanner.projects.instances.databases.operations.get",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/operations",
                                            "httpMethod": "GET",
                                            "id": "spanner.projects.instances.databases.operations.list",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.admin"
                                            ]
                                        }
                                    }
                                },
                                "sessions": {
                                    "methods": {
                                        "batchCreate": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions:batchCreate",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.batchCreate",
                                            "path": "v1/{+database}/sessions:batchCreate",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "beginTransaction": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:beginTransaction",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.beginTransaction",
                                            "path": "v1/{+session}:beginTransaction",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "commit": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:commit",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.commit",
                                            "path": "v1/{+session}:commit",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "create": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.create",
                                            "path": "v1/{+database}/sessions",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}",
                                            "httpMethod": "DELETE",
                                            "id": "spanner.projects.instances.databases.sessions.delete",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "executeBatchDml": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:executeBatchDml",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.executeBatchDml",
                                            "path": "v1/{+session}:executeBatchDml",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "executeSql": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:executeSql",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.executeSql",
                                            "path": "v1/{+session}:executeSql",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "executeStreamingSql": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:executeStreamingSql",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.executeStreamingSql",
                                            "path": "v1/{+session}:executeStreamingSql",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}",
                                            "httpMethod": "GET",
                                            "id": "spanner.projects.instances.databases.sessions.get",
                                            "path": "v1/{+name}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions",
                                            "httpMethod": "GET",
                                            "id": "spanner.projects.instances.databases.sessions.list",
                                            "path": "v1/{+database}/sessions",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "partitionQuery": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:partitionQuery",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.partitionQuery",
                                            "path": "v1/{+session}:partitionQuery",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "partitionRead": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:partitionRead",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.partitionRead",
                                            "path": "v1/{+session}:partitionRead",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "read": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:read",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.read",
                                            "path": "v1/{+session}:read",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "rollback": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:rollback",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.rollback",
                                            "path": "v1/{+session}:rollback",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        },
                                        "streamingRead": {
                                            "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/databases/{databasesId}/sessions/{sessionsId}:streamingRead",
                                            "httpMethod": "POST",
                                            "id": "spanner.projects.instances.databases.sessions.streamingRead",
                                            "path": "v1/{+session}:streamingRead",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/cloud-platform",
                                                "https://www.googleapis.com/auth/spanner.data"
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "operations": {
                            "methods": {
                                "cancel": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/operations/{operationsId}:cancel",
                                    "httpMethod": "POST",
                                    "id": "spanner.projects.instances.operations.cancel",
                                    "path": "v1/{+name}:cancel",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/operations/{operationsId}",
                                    "httpMethod": "DELETE",
                                    "id": "spanner.projects.instances.operations.delete",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "get": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/operations/{operationsId}",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.operations.get",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/projects/{projectsId}/instances/{instancesId}/operations",
                                    "httpMethod": "GET",
                                    "id": "spanner.projects.instances.operations.list",
                                    "path": "v1/{+name}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform",
                                        "https://www.googleapis.com/auth/spanner.admin"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://spanner.googleapis.com/",
    "schemas": {
        "Backup": {
            "id": "Backup",
            "properties": {
                "createTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "expireTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "referencingDatabases": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "sizeBytes": {
                    "format": "int64",
                    "type": "string"
                },
                "state": {
                    "enum": [
                        "STATE_UNSPECIFIED",
                        "CREATING",
                        "READY"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "BackupInfo": {
            "id": "BackupInfo",
            "properties": {
                "backup": {
                    "type": "string"
                },
                "createTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "sourceDatabase": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "BatchCreateSessionsRequest": {
            "id": "BatchCreateSessionsRequest",
            "properties": {
                "sessionCount": {
                    "format": "int32",
                    "type": "integer"
                },
                "sessionTemplate": {
                    "$ref": "Session"
                }
            },
            "type": "object"
        },
        "BatchCreateSessionsResponse": {
            "id": "BatchCreateSessionsResponse",
            "properties": {
                "session": {
                    "items": {
                        "$ref": "Session"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "BeginTransactionRequest": {
            "id": "BeginTransactionRequest",
            "properties": {
                "options": {
                    "$ref": "TransactionOptions"
                }
            },
            "type": "object"
        },
        "Binding": {
            "id": "Binding",
            "properties": {
                "condition": {
                    "$ref": "Expr"
                },
                "members": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "role": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ChildLink": {
            "id": "ChildLink",
            "properties": {
                "childIndex": {
                    "format": "int32",
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "variable": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CommitRequest": {
            "id": "CommitRequest",
            "properties": {
                "mutations": {
                    "items": {
                        "$ref": "Mutation"
                    },
                    "type": "array"
                },
                "singleUseTransaction": {
                    "$ref": "TransactionOptions"
                },
                "transactionId": {
                    "format": "byte",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CommitResponse": {
            "id": "CommitResponse",
            "properties": {
                "commitTimestamp": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CreateBackupMetadata": {
            "id": "CreateBackupMetadata",
            "properties": {
                "cancelTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "progress": {
                    "$ref": "OperationProgress"
                }
            },
            "type": "object"
        },
        "CreateDatabaseMetadata": {
            "id": "CreateDatabaseMetadata",
            "properties": {
                "database": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CreateDatabaseRequest": {
            "id": "CreateDatabaseRequest",
            "properties": {
                "createStatement": {
                    "type": "string"
                },
                "extraStatements": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "CreateInstanceMetadata": {
            "id": "CreateInstanceMetadata",
            "properties": {
                "cancelTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "endTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "instance": {
                    "$ref": "Instance"
                },
                "startTime": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CreateInstanceRequest": {
            "id": "CreateInstanceRequest",
            "properties": {
                "instance": {
                    "$ref": "Instance"
                },
                "instanceId": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "CreateSessionRequest": {
            "id": "CreateSessionRequest",
            "properties": {
                "session": {
                    "$ref": "Session"
                }
            },
            "type": "object"
        },
        "Database": {
            "id": "Database",
            "properties": {
                "createTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "restoreInfo": {
                    "$ref": "RestoreInfo"
                },
                "state": {
                    "enum": [
                        "STATE_UNSPECIFIED",
                        "CREATING",
                        "READY",
                        "READY_OPTIMIZING"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Delete": {
            "id": "Delete",
            "properties": {
                "keySet": {
                    "$ref": "KeySet"
                },
                "table": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Empty": {
            "id": "Empty",
            "properties": {},
            "type": "object"
        },
        "ExecuteBatchDmlRequest": {
            "id": "ExecuteBatchDmlRequest",
            "properties": {
                "seqno": {
                    "format": "int64",
                    "type": "string"
                },
                "statements": {
                    "items": {
                        "$ref": "Statement"
                    },
                    "type": "array"
                },
                "transaction": {
                    "$ref": "TransactionSelector"
                }
            },
            "type": "object"
        },
        "ExecuteBatchDmlResponse": {
            "id": "ExecuteBatchDmlResponse",
            "properties": {
                "resultSets": {
                    "items": {
                        "$ref": "ResultSet"
                    },
                    "type": "array"
                },
                "status": {
                    "$ref": "Status"
                }
            },
            "type": "object"
        },
        "ExecuteSqlRequest": {
            "id": "ExecuteSqlRequest",
            "properties": {
                "paramTypes": {
                    "additionalProperties": {
                        "$ref": "Type"
                    },
                    "type": "object"
                },
                "params": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "partitionToken": {
                    "format": "byte",
                    "type": "string"
                },
                "queryMode": {
                    "enum": [
                        "NORMAL",
                        "PLAN",
                        "PROFILE"
                    ],
                    "type": "string"
                },
                "queryOptions": {
                    "$ref": "QueryOptions"
                },
                "resumeToken": {
                    "format": "byte",
                    "type": "string"
                },
                "seqno": {
                    "format": "int64",
                    "type": "string"
                },
                "sql": {
                    "type": "string"
                },
                "transaction": {
                    "$ref": "TransactionSelector"
                }
            },
            "type": "object"
        },
        "Expr": {
            "id": "Expr",
            "properties": {
                "expression": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Field": {
            "id": "Field",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "Type"
                }
            },
            "type": "object"
        },
        "GetDatabaseDdlResponse": {
            "id": "GetDatabaseDdlResponse",
            "properties": {
                "statements": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "GetIamPolicyRequest": {
            "id": "GetIamPolicyRequest",
            "properties": {
                "options": {
                    "$ref": "GetPolicyOptions"
                }
            },
            "type": "object"
        },
        "GetPolicyOptions": {
            "id": "GetPolicyOptions",
            "properties": {
                "requestedPolicyVersion": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "Instance": {
            "id": "Instance",
            "properties": {
                "config": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "endpointUris": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "labels": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "nodeCount": {
                    "format": "int32",
                    "type": "integer"
                },
                "state": {
                    "enum": [
                        "STATE_UNSPECIFIED",
                        "CREATING",
                        "READY"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "InstanceConfig": {
            "id": "InstanceConfig",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "replicas": {
                    "items": {
                        "$ref": "ReplicaInfo"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "KeyRange": {
            "id": "KeyRange",
            "properties": {
                "endClosed": {
                    "items": {
                        "type": "any"
                    },
                    "type": "array"
                },
                "endOpen": {
                    "items": {
                        "type": "any"
                    },
                    "type": "array"
                },
                "startClosed": {
                    "items": {
                        "type": "any"
                    },
                    "type": "array"
                },
                "startOpen": {
                    "items": {
                        "type": "any"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "KeySet": {
            "id": "KeySet",
            "properties": {
                "all": {
                    "type": "boolean"
                },
                "keys": {
                    "items": {
                        "items": {
                            "type": "any"
                        },
                        "type": "array"
                    },
                    "type": "array"
                },
                "ranges": {
                    "items": {
                        "$ref": "KeyRange"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListBackupOperationsResponse": {
            "id": "ListBackupOperationsResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "operations": {
                    "items": {
                        "$ref": "Operation"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListBackupsResponse": {
            "id": "ListBackupsResponse",
            "properties": {
                "backups": {
                    "items": {
                        "$ref": "Backup"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ListDatabaseOperationsResponse": {
            "id": "ListDatabaseOperationsResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "operations": {
                    "items": {
                        "$ref": "Operation"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListDatabasesResponse": {
            "id": "ListDatabasesResponse",
            "properties": {
                "databases": {
                    "items": {
                        "$ref": "Database"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ListInstanceConfigsResponse": {
            "id": "ListInstanceConfigsResponse",
            "properties": {
                "instanceConfigs": {
                    "items": {
                        "$ref": "InstanceConfig"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ListInstancesResponse": {
            "id": "ListInstancesResponse",
            "properties": {
                "instances": {
                    "items": {
                        "$ref": "Instance"
                    },
                    "type": "array"
                },
                "nextPageToken": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ListOperationsResponse": {
            "id": "ListOperationsResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "operations": {
                    "items": {
                        "$ref": "Operation"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ListSessionsResponse": {
            "id": "ListSessionsResponse",
            "properties": {
                "nextPageToken": {
                    "type": "string"
                },
                "sessions": {
                    "items": {
                        "$ref": "Session"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Mutation": {
            "id": "Mutation",
            "properties": {
                "delete": {
                    "$ref": "Delete"
                },
                "insert": {
                    "$ref": "Write"
                },
                "insertOrUpdate": {
                    "$ref": "Write"
                },
                "replace": {
                    "$ref": "Write"
                },
                "update": {
                    "$ref": "Write"
                }
            },
            "type": "object"
        },
        "Operation": {
            "id": "Operation",
            "properties": {
                "done": {
                    "type": "boolean"
                },
                "error": {
                    "$ref": "Status"
                },
                "metadata": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "OperationProgress": {
            "id": "OperationProgress",
            "properties": {
                "endTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "progressPercent": {
                    "format": "int32",
                    "type": "integer"
                },
                "startTime": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "OptimizeRestoredDatabaseMetadata": {
            "id": "OptimizeRestoredDatabaseMetadata",
            "properties": {
                "name": {
                    "type": "string"
                },
                "progress": {
                    "$ref": "OperationProgress"
                }
            },
            "type": "object"
        },
        "PartialResultSet": {
            "id": "PartialResultSet",
            "properties": {
                "chunkedValue": {
                    "type": "boolean"
                },
                "metadata": {
                    "$ref": "ResultSetMetadata"
                },
                "resumeToken": {
                    "format": "byte",
                    "type": "string"
                },
                "stats": {
                    "$ref": "ResultSetStats"
                },
                "values": {
                    "items": {
                        "type": "any"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Partition": {
            "id": "Partition",
            "properties": {
                "partitionToken": {
                    "format": "byte",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "PartitionOptions": {
            "id": "PartitionOptions",
            "properties": {
                "maxPartitions": {
                    "format": "int64",
                    "type": "string"
                },
                "partitionSizeBytes": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "PartitionQueryRequest": {
            "id": "PartitionQueryRequest",
            "properties": {
                "paramTypes": {
                    "additionalProperties": {
                        "$ref": "Type"
                    },
                    "type": "object"
                },
                "params": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "partitionOptions": {
                    "$ref": "PartitionOptions"
                },
                "sql": {
                    "type": "string"
                },
                "transaction": {
                    "$ref": "TransactionSelector"
                }
            },
            "type": "object"
        },
        "PartitionReadRequest": {
            "id": "PartitionReadRequest",
            "properties": {
                "columns": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "index": {
                    "type": "string"
                },
                "keySet": {
                    "$ref": "KeySet"
                },
                "partitionOptions": {
                    "$ref": "PartitionOptions"
                },
                "table": {
                    "type": "string"
                },
                "transaction": {
                    "$ref": "TransactionSelector"
                }
            },
            "type": "object"
        },
        "PartitionResponse": {
            "id": "PartitionResponse",
            "properties": {
                "partitions": {
                    "items": {
                        "$ref": "Partition"
                    },
                    "type": "array"
                },
                "transaction": {
                    "$ref": "Transaction"
                }
            },
            "type": "object"
        },
        "PartitionedDml": {
            "id": "PartitionedDml",
            "properties": {},
            "type": "object"
        },
        "PlanNode": {
            "id": "PlanNode",
            "properties": {
                "childLinks": {
                    "items": {
                        "$ref": "ChildLink"
                    },
                    "type": "array"
                },
                "displayName": {
                    "type": "string"
                },
                "executionStats": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "index": {
                    "format": "int32",
                    "type": "integer"
                },
                "kind": {
                    "enum": [
                        "KIND_UNSPECIFIED",
                        "RELATIONAL",
                        "SCALAR"
                    ],
                    "type": "string"
                },
                "metadata": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "shortRepresentation": {
                    "$ref": "ShortRepresentation"
                }
            },
            "type": "object"
        },
        "Policy": {
            "id": "Policy",
            "properties": {
                "bindings": {
                    "items": {
                        "$ref": "Binding"
                    },
                    "type": "array"
                },
                "etag": {
                    "format": "byte",
                    "type": "string"
                },
                "version": {
                    "format": "int32",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "QueryOptions": {
            "id": "QueryOptions",
            "properties": {
                "optimizerVersion": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "QueryPlan": {
            "id": "QueryPlan",
            "properties": {
                "planNodes": {
                    "items": {
                        "$ref": "PlanNode"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "ReadOnly": {
            "id": "ReadOnly",
            "properties": {
                "exactStaleness": {
                    "format": "google-duration",
                    "type": "string"
                },
                "maxStaleness": {
                    "format": "google-duration",
                    "type": "string"
                },
                "minReadTimestamp": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "readTimestamp": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "returnReadTimestamp": {
                    "type": "boolean"
                },
                "strong": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "ReadRequest": {
            "id": "ReadRequest",
            "properties": {
                "columns": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "index": {
                    "type": "string"
                },
                "keySet": {
                    "$ref": "KeySet"
                },
                "limit": {
                    "format": "int64",
                    "type": "string"
                },
                "partitionToken": {
                    "format": "byte",
                    "type": "string"
                },
                "resumeToken": {
                    "format": "byte",
                    "type": "string"
                },
                "table": {
                    "type": "string"
                },
                "transaction": {
                    "$ref": "TransactionSelector"
                }
            },
            "type": "object"
        },
        "ReadWrite": {
            "id": "ReadWrite",
            "properties": {},
            "type": "object"
        },
        "ReplicaInfo": {
            "id": "ReplicaInfo",
            "properties": {
                "defaultLeaderLocation": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "TYPE_UNSPECIFIED",
                        "READ_WRITE",
                        "READ_ONLY",
                        "WITNESS"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RestoreDatabaseMetadata": {
            "id": "RestoreDatabaseMetadata",
            "properties": {
                "backupInfo": {
                    "$ref": "BackupInfo"
                },
                "cancelTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "optimizeDatabaseOperationName": {
                    "type": "string"
                },
                "progress": {
                    "$ref": "OperationProgress"
                },
                "sourceType": {
                    "enum": [
                        "TYPE_UNSPECIFIED",
                        "BACKUP"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RestoreDatabaseRequest": {
            "id": "RestoreDatabaseRequest",
            "properties": {
                "backup": {
                    "type": "string"
                },
                "databaseId": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RestoreInfo": {
            "id": "RestoreInfo",
            "properties": {
                "backupInfo": {
                    "$ref": "BackupInfo"
                },
                "sourceType": {
                    "enum": [
                        "TYPE_UNSPECIFIED",
                        "BACKUP"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ResultSet": {
            "id": "ResultSet",
            "properties": {
                "metadata": {
                    "$ref": "ResultSetMetadata"
                },
                "rows": {
                    "items": {
                        "items": {
                            "type": "any"
                        },
                        "type": "array"
                    },
                    "type": "array"
                },
                "stats": {
                    "$ref": "ResultSetStats"
                }
            },
            "type": "object"
        },
        "ResultSetMetadata": {
            "id": "ResultSetMetadata",
            "properties": {
                "rowType": {
                    "$ref": "StructType"
                },
                "transaction": {
                    "$ref": "Transaction"
                }
            },
            "type": "object"
        },
        "ResultSetStats": {
            "id": "ResultSetStats",
            "properties": {
                "queryPlan": {
                    "$ref": "QueryPlan"
                },
                "queryStats": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "rowCountExact": {
                    "format": "int64",
                    "type": "string"
                },
                "rowCountLowerBound": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RollbackRequest": {
            "id": "RollbackRequest",
            "properties": {
                "transactionId": {
                    "format": "byte",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Session": {
            "id": "Session",
            "properties": {
                "approximateLastUseTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "createTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "labels": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "type": "object"
                },
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "SetIamPolicyRequest": {
            "id": "SetIamPolicyRequest",
            "properties": {
                "policy": {
                    "$ref": "Policy"
                }
            },
            "type": "object"
        },
        "ShortRepresentation": {
            "id": "ShortRepresentation",
            "properties": {
                "subqueries": {
                    "additionalProperties": {
                        "format": "int32",
                        "type": "integer"
                    },
                    "type": "object"
                }
            },
            "type": "object"
        },
        "Statement": {
            "id": "Statement",
            "properties": {
                "paramTypes": {
                    "additionalProperties": {
                        "$ref": "Type"
                    },
                    "type": "object"
                },
                "params": {
                    "additionalProperties": {
                        "type": "any"
                    },
                    "type": "object"
                },
                "sql": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Status": {
            "id": "Status",
            "properties": {
                "code": {
                    "format": "int32",
                    "type": "integer"
                },
                "details": {
                    "items": {
                        "additionalProperties": {
                            "type": "any"
                        },
                        "type": "object"
                    },
                    "type": "array"
                },
                "message": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "StructType": {
            "id": "StructType",
            "properties": {
                "fields": {
                    "items": {
                        "$ref": "Field"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "TestIamPermissionsRequest": {
            "id": "TestIamPermissionsRequest",
            "properties": {
                "permissions": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "TestIamPermissionsResponse": {
            "id": "TestIamPermissionsResponse",
            "properties": {
                "permissions": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "Transaction": {
            "id": "Transaction",
            "properties": {
                "id": {
                    "format": "byte",
                    "type": "string"
                },
                "readTimestamp": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TransactionOptions": {
            "id": "TransactionOptions",
            "properties": {
                "partitionedDml": {
                    "$ref": "PartitionedDml"
                },
                "readOnly": {
                    "$ref": "ReadOnly"
                },
                "readWrite": {
                    "$ref": "ReadWrite"
                }
            },
            "type": "object"
        },
        "TransactionSelector": {
            "id": "TransactionSelector",
            "properties": {
                "begin": {
                    "$ref": "TransactionOptions"
                },
                "id": {
                    "format": "byte",
                    "type": "string"
                },
                "singleUse": {
                    "$ref": "TransactionOptions"
                }
            },
            "type": "object"
        },
        "Type": {
            "id": "Type",
            "properties": {
                "arrayElementType": {
                    "$ref": "Type"
                },
                "code": {
                    "enum": [
                        "TYPE_CODE_UNSPECIFIED",
                        "BOOL",
                        "INT64",
                        "FLOAT64",
                        "TIMESTAMP",
                        "DATE",
                        "STRING",
                        "BYTES",
                        "ARRAY",
                        "STRUCT",
                        "NUMERIC"
                    ],
                    "type": "string"
                },
                "structType": {
                    "$ref": "StructType"
                }
            },
            "type": "object"
        },
        "UpdateDatabaseDdlMetadata": {
            "id": "UpdateDatabaseDdlMetadata",
            "properties": {
                "commitTimestamps": {
                    "items": {
                        "format": "google-datetime",
                        "type": "string"
                    },
                    "type": "array"
                },
                "database": {
                    "type": "string"
                },
                "statements": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "UpdateDatabaseDdlRequest": {
            "id": "UpdateDatabaseDdlRequest",
            "properties": {
                "operationId": {
                    "type": "string"
                },
                "statements": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "UpdateInstanceMetadata": {
            "id": "UpdateInstanceMetadata",
            "properties": {
                "cancelTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "endTime": {
                    "format": "google-datetime",
                    "type": "string"
                },
                "instance": {
                    "$ref": "Instance"
                },
                "startTime": {
                    "format": "google-datetime",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "UpdateInstanceRequest": {
            "id": "UpdateInstanceRequest",
            "properties": {
                "fieldMask": {
                    "format": "google-fieldmask",
                    "type": "string"
                },
                "instance": {
                    "$ref": "Instance"
                }
            },
            "type": "object"
        },
        "Write": {
            "id": "Write",
            "properties": {
                "columns": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "table": {
                    "type": "string"
                },
                "values": {
                    "items": {
                        "items": {
                            "type": "any"
                        },
                        "type": "array"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        }
    },
    "servicePath": "",
    "title": "Cloud Spanner API",
    "version": "v1",
    "version_module": true
}