{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/tagmanager.delete.containers": {},
                "https://www.googleapis.com/auth/tagmanager.edit.containers": {},
                "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {},
                "https://www.googleapis.com/auth/tagmanager.manage.accounts": {},
                "https://www.googleapis.com/auth/tagmanager.manage.users": {},
                "https://www.googleapis.com/auth/tagmanager.publish": {},
                "https://www.googleapis.com/auth/tagmanager.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://www.googleapis.com/",
    "batchPath": "batch/tagmanager/v2",
    "canonicalName": "Tag Manager",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/tag-manager",
    "id": "tagmanager:v2",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://www.mtls.googleapis.com/",
    "name": "tagmanager",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "accounts": {
            "methods": {
                "get": {
                    "flatPath": "tagmanager/v2/accounts/{accountsId}",
                    "httpMethod": "GET",
                    "id": "tagmanager.accounts.get",
                    "path": "tagmanager/v2/{+path}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.manage.accounts",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                    ]
                },
                "list": {
                    "flatPath": "tagmanager/v2/accounts",
                    "httpMethod": "GET",
                    "id": "tagmanager.accounts.list",
                    "path": "tagmanager/v2/accounts",
                    "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.manage.accounts",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                    ]
                },
                "update": {
                    "flatPath": "tagmanager/v2/accounts/{accountsId}",
                    "httpMethod": "PUT",
                    "id": "tagmanager.accounts.update",
                    "path": "tagmanager/v2/{+path}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.manage.accounts"
                    ]
                }
            },
            "resources": {
                "containers": {
                    "methods": {
                        "create": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers",
                            "httpMethod": "POST",
                            "id": "tagmanager.accounts.containers.create",
                            "path": "tagmanager/v2/{+parent}/containers",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                            ]
                        },
                        "delete": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
                            "httpMethod": "DELETE",
                            "id": "tagmanager.accounts.containers.delete",
                            "path": "tagmanager/v2/{+path}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.delete.containers"
                            ]
                        },
                        "get": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.containers.get",
                            "path": "tagmanager/v2/{+path}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                "https://www.googleapis.com/auth/tagmanager.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.containers.list",
                            "path": "tagmanager/v2/{+parent}/containers",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                "https://www.googleapis.com/auth/tagmanager.readonly"
                            ]
                        },
                        "update": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
                            "httpMethod": "PUT",
                            "id": "tagmanager.accounts.containers.update",
                            "path": "tagmanager/v2/{+path}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                            ]
                        }
                    },
                    "resources": {
                        "environments": {
                            "methods": {
                                "create": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.environments.create",
                                    "path": "tagmanager/v2/{+parent}/environments",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.environments.delete",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "get": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.environments.get",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.environments.list",
                                    "path": "tagmanager/v2/{+parent}/environments",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "reauthorize": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}:reauthorize",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.environments.reauthorize",
                                    "path": "tagmanager/v2/{+path}:reauthorize",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.publish"
                                    ]
                                },
                                "update": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.environments.update",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            }
                        },
                        "version_headers": {
                            "methods": {
                                "latest": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers:latest",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.version_headers.latest",
                                    "path": "tagmanager/v2/{+parent}/version_headers:latest",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.version_headers.list",
                                    "path": "tagmanager/v2/{+parent}/version_headers",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                }
                            }
                        },
                        "versions": {
                            "methods": {
                                "delete": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.versions.delete",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "get": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.versions.get",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "live": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions:live",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.versions.live",
                                    "path": "tagmanager/v2/{+parent}/versions:live",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "publish": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:publish",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.publish",
                                    "path": "tagmanager/v2/{+path}:publish",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.publish"
                                    ]
                                },
                                "set_latest": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:set_latest",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.set_latest",
                                    "path": "tagmanager/v2/{+path}:set_latest",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "undelete": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:undelete",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.undelete",
                                    "path": "tagmanager/v2/{+path}:undelete",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "update": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.versions.update",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                }
                            }
                        },
                        "workspaces": {
                            "methods": {
                                "create": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.workspaces.create",
                                    "path": "tagmanager/v2/{+parent}/workspaces",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "create_version": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:create_version",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.workspaces.create_version",
                                    "path": "tagmanager/v2/{+path}:create_version",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.workspaces.delete",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.delete.containers"
                                    ]
                                },
                                "get": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.workspaces.get",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "getStatus": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/status",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.workspaces.getStatus",
                                    "path": "tagmanager/v2/{+path}/status",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.workspaces.list",
                                    "path": "tagmanager/v2/{+parent}/workspaces",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "quick_preview": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:quick_preview",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.workspaces.quick_preview",
                                    "path": "tagmanager/v2/{+path}:quick_preview",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "resolve_conflict": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:resolve_conflict",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.workspaces.resolve_conflict",
                                    "path": "tagmanager/v2/{+path}:resolve_conflict",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "sync": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:sync",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.workspaces.sync",
                                    "path": "tagmanager/v2/{+path}:sync",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "update": {
                                    "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.workspaces.update",
                                    "path": "tagmanager/v2/{+path}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            },
                            "resources": {
                                "built_in_variables": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.built_in_variables.create",
                                            "path": "tagmanager/v2/{+parent}/built_in_variables",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.built_in_variables.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.built_in_variables.list",
                                            "path": "tagmanager/v2/{+parent}/built_in_variables",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.built_in_variables.revert",
                                            "path": "tagmanager/v2/{+path}/built_in_variables:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                },
                                "folders": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.create",
                                            "path": "tagmanager/v2/{+parent}/folders",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "entities": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:entities",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.entities",
                                            "path": "tagmanager/v2/{+path}:entities",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.get",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.list",
                                            "path": "tagmanager/v2/{+parent}/folders",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "move_entities_to_folder": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:move_entities_to_folder",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.move_entities_to_folder",
                                            "path": "tagmanager/v2/{+path}:move_entities_to_folder",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.revert",
                                            "path": "tagmanager/v2/{+path}:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "update": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                                            "httpMethod": "PUT",
                                            "id": "tagmanager.accounts.containers.workspaces.folders.update",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                },
                                "tags": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.tags.create",
                                            "path": "tagmanager/v2/{+parent}/tags",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.tags.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.tags.get",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.tags.list",
                                            "path": "tagmanager/v2/{+parent}/tags",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.tags.revert",
                                            "path": "tagmanager/v2/{+path}:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "update": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                                            "httpMethod": "PUT",
                                            "id": "tagmanager.accounts.containers.workspaces.tags.update",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                },
                                "templates": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.templates.create",
                                            "path": "tagmanager/v2/{+parent}/templates",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.templates.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.templates.get",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.templates.list",
                                            "path": "tagmanager/v2/{+parent}/templates",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.templates.revert",
                                            "path": "tagmanager/v2/{+path}:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "update": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                                            "httpMethod": "PUT",
                                            "id": "tagmanager.accounts.containers.workspaces.templates.update",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                },
                                "triggers": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.triggers.create",
                                            "path": "tagmanager/v2/{+parent}/triggers",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.triggers.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.triggers.get",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.triggers.list",
                                            "path": "tagmanager/v2/{+parent}/triggers",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.triggers.revert",
                                            "path": "tagmanager/v2/{+path}:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "update": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                                            "httpMethod": "PUT",
                                            "id": "tagmanager.accounts.containers.workspaces.triggers.update",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                },
                                "variables": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.variables.create",
                                            "path": "tagmanager/v2/{+parent}/variables",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.variables.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.variables.get",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.variables.list",
                                            "path": "tagmanager/v2/{+parent}/variables",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.variables.revert",
                                            "path": "tagmanager/v2/{+path}:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "update": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                                            "httpMethod": "PUT",
                                            "id": "tagmanager.accounts.containers.workspaces.variables.update",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                },
                                "zones": {
                                    "methods": {
                                        "create": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.zones.create",
                                            "path": "tagmanager/v2/{+parent}/zones",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "delete": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                                            "httpMethod": "DELETE",
                                            "id": "tagmanager.accounts.containers.workspaces.zones.delete",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "get": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.zones.get",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "list": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones",
                                            "httpMethod": "GET",
                                            "id": "tagmanager.accounts.containers.workspaces.zones.list",
                                            "path": "tagmanager/v2/{+parent}/zones",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                                "https://www.googleapis.com/auth/tagmanager.readonly"
                                            ]
                                        },
                                        "revert": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}:revert",
                                            "httpMethod": "POST",
                                            "id": "tagmanager.accounts.containers.workspaces.zones.revert",
                                            "path": "tagmanager/v2/{+path}:revert",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        },
                                        "update": {
                                            "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                                            "httpMethod": "PUT",
                                            "id": "tagmanager.accounts.containers.workspaces.zones.update",
                                            "path": "tagmanager/v2/{+path}",
                                            "scopes": [
                                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "user_permissions": {
                    "methods": {
                        "create": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions",
                            "httpMethod": "POST",
                            "id": "tagmanager.accounts.user_permissions.create",
                            "path": "tagmanager/v2/{+parent}/user_permissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "delete": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
                            "httpMethod": "DELETE",
                            "id": "tagmanager.accounts.user_permissions.delete",
                            "path": "tagmanager/v2/{+path}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "get": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.user_permissions.get",
                            "path": "tagmanager/v2/{+path}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "list": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.user_permissions.list",
                            "path": "tagmanager/v2/{+parent}/user_permissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "update": {
                            "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
                            "httpMethod": "PUT",
                            "id": "tagmanager.accounts.user_permissions.update",
                            "path": "tagmanager/v2/{+path}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "",
    "title": "Tag Manager API",
    "version": "v2"
}