{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/tasks": {},
                "https://www.googleapis.com/auth/tasks.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://www.googleapis.com/",
    "batchPath": "batch/tasks/v1",
    "canonicalName": "Tasks",
    "discoveryVersion": "v1",
    "documentationLink": "",
    "fullyEncodeReservedExpansion": true,
    "id": "tasks:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://www.mtls.googleapis.com/",
    "name": "tasks",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "tasklists": {
            "methods": {
                "delete": {
                    "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
                    "httpMethod": "DELETE",
                    "id": "tasks.tasklists.delete",
                    "path": "tasks/v1/users/@me/lists/{tasklist}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "get": {
                    "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
                    "httpMethod": "GET",
                    "id": "tasks.tasklists.get",
                    "path": "tasks/v1/users/@me/lists/{tasklist}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks",
                        "https://www.googleapis.com/auth/tasks.readonly"
                    ]
                },
                "insert": {
                    "flatPath": "tasks/v1/users/@me/lists",
                    "httpMethod": "POST",
                    "id": "tasks.tasklists.insert",
                    "path": "tasks/v1/users/@me/lists",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "list": {
                    "flatPath": "tasks/v1/users/@me/lists",
                    "httpMethod": "GET",
                    "id": "tasks.tasklists.list",
                    "path": "tasks/v1/users/@me/lists",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks",
                        "https://www.googleapis.com/auth/tasks.readonly"
                    ]
                },
                "patch": {
                    "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
                    "httpMethod": "PATCH",
                    "id": "tasks.tasklists.patch",
                    "path": "tasks/v1/users/@me/lists/{tasklist}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "update": {
                    "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
                    "httpMethod": "PUT",
                    "id": "tasks.tasklists.update",
                    "path": "tasks/v1/users/@me/lists/{tasklist}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                }
            }
        },
        "tasks": {
            "methods": {
                "clear": {
                    "flatPath": "tasks/v1/lists/{tasklist}/clear",
                    "httpMethod": "POST",
                    "id": "tasks.tasks.clear",
                    "path": "tasks/v1/lists/{tasklist}/clear",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "delete": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "httpMethod": "DELETE",
                    "id": "tasks.tasks.delete",
                    "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "get": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "httpMethod": "GET",
                    "id": "tasks.tasks.get",
                    "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks",
                        "https://www.googleapis.com/auth/tasks.readonly"
                    ]
                },
                "insert": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks",
                    "httpMethod": "POST",
                    "id": "tasks.tasks.insert",
                    "path": "tasks/v1/lists/{tasklist}/tasks",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "list": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks",
                    "httpMethod": "GET",
                    "id": "tasks.tasks.list",
                    "path": "tasks/v1/lists/{tasklist}/tasks",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks",
                        "https://www.googleapis.com/auth/tasks.readonly"
                    ]
                },
                "move": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}/move",
                    "httpMethod": "POST",
                    "id": "tasks.tasks.move",
                    "path": "tasks/v1/lists/{tasklist}/tasks/{task}/move",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "patch": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "httpMethod": "PATCH",
                    "id": "tasks.tasks.patch",
                    "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                },
                "update": {
                    "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "httpMethod": "PUT",
                    "id": "tasks.tasks.update",
                    "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tasks"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "",
    "title": "Tasks API",
    "version": "v1"
}