{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/ediscovery": {},
                "https://www.googleapis.com/auth/ediscovery.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://vault.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Vault",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/vault",
    "fullyEncodeReservedExpansion": true,
    "id": "vault:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
    "name": "vault",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "matters": {
            "methods": {
                "addPermissions": {
                    "flatPath": "v1/matters/{matterId}:addPermissions",
                    "httpMethod": "POST",
                    "id": "vault.matters.addPermissions",
                    "path": "v1/matters/{matterId}:addPermissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "close": {
                    "flatPath": "v1/matters/{matterId}:close",
                    "httpMethod": "POST",
                    "id": "vault.matters.close",
                    "path": "v1/matters/{matterId}:close",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "create": {
                    "flatPath": "v1/matters",
                    "httpMethod": "POST",
                    "id": "vault.matters.create",
                    "path": "v1/matters",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "delete": {
                    "flatPath": "v1/matters/{matterId}",
                    "httpMethod": "DELETE",
                    "id": "vault.matters.delete",
                    "path": "v1/matters/{matterId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "get": {
                    "flatPath": "v1/matters/{matterId}",
                    "httpMethod": "GET",
                    "id": "vault.matters.get",
                    "path": "v1/matters/{matterId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery",
                        "https://www.googleapis.com/auth/ediscovery.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v1/matters",
                    "httpMethod": "GET",
                    "id": "vault.matters.list",
                    "path": "v1/matters",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery",
                        "https://www.googleapis.com/auth/ediscovery.readonly"
                    ]
                },
                "removePermissions": {
                    "flatPath": "v1/matters/{matterId}:removePermissions",
                    "httpMethod": "POST",
                    "id": "vault.matters.removePermissions",
                    "path": "v1/matters/{matterId}:removePermissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "reopen": {
                    "flatPath": "v1/matters/{matterId}:reopen",
                    "httpMethod": "POST",
                    "id": "vault.matters.reopen",
                    "path": "v1/matters/{matterId}:reopen",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "undelete": {
                    "flatPath": "v1/matters/{matterId}:undelete",
                    "httpMethod": "POST",
                    "id": "vault.matters.undelete",
                    "path": "v1/matters/{matterId}:undelete",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "update": {
                    "flatPath": "v1/matters/{matterId}",
                    "httpMethod": "PUT",
                    "id": "vault.matters.update",
                    "path": "v1/matters/{matterId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                }
            },
            "resources": {
                "exports": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/matters/{matterId}/exports",
                            "httpMethod": "POST",
                            "id": "vault.matters.exports.create",
                            "path": "v1/matters/{matterId}/exports",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/matters/{matterId}/exports/{exportId}",
                            "httpMethod": "DELETE",
                            "id": "vault.matters.exports.delete",
                            "path": "v1/matters/{matterId}/exports/{exportId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/matters/{matterId}/exports/{exportId}",
                            "httpMethod": "GET",
                            "id": "vault.matters.exports.get",
                            "path": "v1/matters/{matterId}/exports/{exportId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/matters/{matterId}/exports",
                            "httpMethod": "GET",
                            "id": "vault.matters.exports.list",
                            "path": "v1/matters/{matterId}/exports",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        }
                    }
                },
                "holds": {
                    "methods": {
                        "addHeldAccounts": {
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
                            "httpMethod": "POST",
                            "id": "vault.matters.holds.addHeldAccounts",
                            "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "create": {
                            "flatPath": "v1/matters/{matterId}/holds",
                            "httpMethod": "POST",
                            "id": "vault.matters.holds.create",
                            "path": "v1/matters/{matterId}/holds",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}",
                            "httpMethod": "DELETE",
                            "id": "vault.matters.holds.delete",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}",
                            "httpMethod": "GET",
                            "id": "vault.matters.holds.get",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/matters/{matterId}/holds",
                            "httpMethod": "GET",
                            "id": "vault.matters.holds.list",
                            "path": "v1/matters/{matterId}/holds",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        },
                        "removeHeldAccounts": {
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
                            "httpMethod": "POST",
                            "id": "vault.matters.holds.removeHeldAccounts",
                            "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "update": {
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}",
                            "httpMethod": "PUT",
                            "id": "vault.matters.holds.update",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        }
                    },
                    "resources": {
                        "accounts": {
                            "methods": {
                                "create": {
                                    "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "httpMethod": "POST",
                                    "id": "vault.matters.holds.accounts.create",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery"
                                    ]
                                },
                                "delete": {
                                    "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                                    "httpMethod": "DELETE",
                                    "id": "vault.matters.holds.accounts.delete",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery"
                                    ]
                                },
                                "list": {
                                    "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "httpMethod": "GET",
                                    "id": "vault.matters.holds.accounts.list",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery",
                                        "https://www.googleapis.com/auth/ediscovery.readonly"
                                    ]
                                }
                            }
                        }
                    }
                },
                "savedQueries": {
                    "methods": {
                        "create": {
                            "flatPath": "v1/matters/{matterId}/savedQueries",
                            "httpMethod": "POST",
                            "id": "vault.matters.savedQueries.create",
                            "path": "v1/matters/{matterId}/savedQueries",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "httpMethod": "DELETE",
                            "id": "vault.matters.savedQueries.delete",
                            "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "get": {
                            "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "httpMethod": "GET",
                            "id": "vault.matters.savedQueries.get",
                            "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/matters/{matterId}/savedQueries",
                            "httpMethod": "GET",
                            "id": "vault.matters.savedQueries.list",
                            "path": "v1/matters/{matterId}/savedQueries",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "operations": {
            "methods": {
                "delete": {
                    "flatPath": "v1/operations/{operationsId}",
                    "httpMethod": "DELETE",
                    "id": "vault.operations.delete",
                    "path": "v1/{+name}"
                }
            }
        }
    },
    "rootUrl": "https://vault.googleapis.com/",
    "servicePath": "",
    "title": "G Suite Vault API",
    "version": "v1",
    "version_module": true
}