{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/webmasters": {},
                "https://www.googleapis.com/auth/webmasters.readonly": {}
            }
        }
    },
    "basePath": "/webmasters/v3/",
    "baseUrl": "https://www.googleapis.com/webmasters/v3/",
    "batchPath": "batch/webmasters/v3",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/webmaster-tools/",
    "id": "webmasters:v3",
    "kind": "discovery#restDescription",
    "name": "webmasters",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "searchanalytics": {
            "methods": {
                "query": {
                    "httpMethod": "POST",
                    "id": "webmasters.searchanalytics.query",
                    "path": "sites/{siteUrl}/searchAnalytics/query",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                }
            }
        },
        "sitemaps": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "webmasters.sitemaps.delete",
                    "path": "sites/{siteUrl}/sitemaps/{feedpath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "webmasters.sitemaps.get",
                    "path": "sites/{siteUrl}/sitemaps/{feedpath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "webmasters.sitemaps.list",
                    "path": "sites/{siteUrl}/sitemaps",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "submit": {
                    "httpMethod": "PUT",
                    "id": "webmasters.sitemaps.submit",
                    "path": "sites/{siteUrl}/sitemaps/{feedpath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                }
            }
        },
        "sites": {
            "methods": {
                "add": {
                    "httpMethod": "PUT",
                    "id": "webmasters.sites.add",
                    "path": "sites/{siteUrl}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "webmasters.sites.delete",
                    "path": "sites/{siteUrl}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                },
                "get": {
                    "httpMethod": "GET",
                    "id": "webmasters.sites.get",
                    "path": "sites/{siteUrl}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "webmasters.sites.list",
                    "path": "sites",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "webmasters/v3/",
    "title": "Search Console API",
    "version": "v3"
}