{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {},
                "https://www.googleapis.com/auth/yt-analytics.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://youtubereporting.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "YouTube Reporting",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/youtube/reporting/v1/reports/",
    "id": "youtubereporting:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://youtubereporting.mtls.googleapis.com/",
    "name": "youtubereporting",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "jobs": {
            "methods": {
                "create": {
                    "flatPath": "v1/jobs",
                    "httpMethod": "POST",
                    "id": "youtubereporting.jobs.create",
                    "path": "v1/jobs",
                    "scopes": [
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "delete": {
                    "flatPath": "v1/jobs/{jobId}",
                    "httpMethod": "DELETE",
                    "id": "youtubereporting.jobs.delete",
                    "path": "v1/jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "get": {
                    "flatPath": "v1/jobs/{jobId}",
                    "httpMethod": "GET",
                    "id": "youtubereporting.jobs.get",
                    "path": "v1/jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v1/jobs",
                    "httpMethod": "GET",
                    "id": "youtubereporting.jobs.list",
                    "path": "v1/jobs",
                    "scopes": [
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                }
            },
            "resources": {
                "reports": {
                    "methods": {
                        "get": {
                            "flatPath": "v1/jobs/{jobId}/reports/{reportId}",
                            "httpMethod": "GET",
                            "id": "youtubereporting.jobs.reports.get",
                            "path": "v1/jobs/{jobId}/reports/{reportId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                                "https://www.googleapis.com/auth/yt-analytics.readonly"
                            ]
                        },
                        "list": {
                            "flatPath": "v1/jobs/{jobId}/reports",
                            "httpMethod": "GET",
                            "id": "youtubereporting.jobs.reports.list",
                            "path": "v1/jobs/{jobId}/reports",
                            "scopes": [
                                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                                "https://www.googleapis.com/auth/yt-analytics.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "media": {
            "methods": {
                "download": {
                    "flatPath": "v1/media/{mediaId}",
                    "httpMethod": "GET",
                    "id": "youtubereporting.media.download",
                    "path": "v1/media/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ],
                    "supportsMediaDownload": true,
                    "useMediaDownloadService": true
                }
            }
        },
        "reportTypes": {
            "methods": {
                "list": {
                    "flatPath": "v1/reportTypes",
                    "httpMethod": "GET",
                    "id": "youtubereporting.reportTypes.list",
                    "path": "v1/reportTypes",
                    "scopes": [
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://youtubereporting.googleapis.com/",
    "servicePath": "",
    "title": "YouTube Reporting API",
    "version": "v1"
}