{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/youtube": {},
                "https://www.googleapis.com/auth/youtube.channel-memberships.creator": {},
                "https://www.googleapis.com/auth/youtube.force-ssl": {},
                "https://www.googleapis.com/auth/youtube.readonly": {},
                "https://www.googleapis.com/auth/youtube.upload": {},
                "https://www.googleapis.com/auth/youtubepartner": {},
                "https://www.googleapis.com/auth/youtubepartner-channel-audit": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://www.googleapis.com/",
    "batchPath": "batch/youtube",
    "canonicalName": "YouTube",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/youtube/",
    "fullyEncodeReservedExpansion": true,
    "id": "youtube:v3",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://www.mtls.googleapis.com/",
    "name": "youtube",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "abuseReports": {
            "methods": {
                "insert": {
                    "flatPath": "youtube/v3/abuseReports",
                    "httpMethod": "POST",
                    "id": "youtube.abuseReports.insert",
                    "path": "youtube/v3/abuseReports",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "activities": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/activities",
                    "httpMethod": "GET",
                    "id": "youtube.activities.list",
                    "path": "youtube/v3/activities",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "captions": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/captions",
                    "httpMethod": "DELETE",
                    "id": "youtube.captions.delete",
                    "path": "youtube/v3/captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "download": {
                    "flatPath": "youtube/v3/captions/{id}",
                    "httpMethod": "GET",
                    "id": "youtube.captions.download",
                    "path": "youtube/v3/captions/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaDownload": true,
                    "useMediaDownloadService": true
                },
                "insert": {
                    "flatPath": "youtube/v3/captions",
                    "httpMethod": "POST",
                    "id": "youtube.captions.insert",
                    "path": "youtube/v3/captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                },
                "list": {
                    "flatPath": "youtube/v3/captions",
                    "httpMethod": "GET",
                    "id": "youtube.captions.list",
                    "path": "youtube/v3/captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/captions",
                    "httpMethod": "PUT",
                    "id": "youtube.captions.update",
                    "path": "youtube/v3/captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "channelBanners": {
            "methods": {
                "insert": {
                    "flatPath": "youtube/v3/channelBanners/insert",
                    "httpMethod": "POST",
                    "id": "youtube.channelBanners.insert",
                    "path": "youtube/v3/channelBanners/insert",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "channelSections": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/channelSections",
                    "httpMethod": "DELETE",
                    "id": "youtube.channelSections.delete",
                    "path": "youtube/v3/channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/channelSections",
                    "httpMethod": "POST",
                    "id": "youtube.channelSections.insert",
                    "path": "youtube/v3/channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/channelSections",
                    "httpMethod": "GET",
                    "id": "youtube.channelSections.list",
                    "path": "youtube/v3/channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/channelSections",
                    "httpMethod": "PUT",
                    "id": "youtube.channelSections.update",
                    "path": "youtube/v3/channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "channels": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/channels",
                    "httpMethod": "GET",
                    "id": "youtube.channels.list",
                    "path": "youtube/v3/channels",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/youtubepartner-channel-audit"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/channels",
                    "httpMethod": "PUT",
                    "id": "youtube.channels.update",
                    "path": "youtube/v3/channels",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "commentThreads": {
            "methods": {
                "insert": {
                    "flatPath": "youtube/v3/commentThreads",
                    "httpMethod": "POST",
                    "id": "youtube.commentThreads.insert",
                    "path": "youtube/v3/commentThreads",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/commentThreads",
                    "httpMethod": "GET",
                    "id": "youtube.commentThreads.list",
                    "path": "youtube/v3/commentThreads",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/commentThreads",
                    "httpMethod": "PUT",
                    "id": "youtube.commentThreads.update",
                    "path": "youtube/v3/commentThreads",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/comments",
                    "httpMethod": "DELETE",
                    "id": "youtube.comments.delete",
                    "path": "youtube/v3/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/comments",
                    "httpMethod": "POST",
                    "id": "youtube.comments.insert",
                    "path": "youtube/v3/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/comments",
                    "httpMethod": "GET",
                    "id": "youtube.comments.list",
                    "path": "youtube/v3/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "markAsSpam": {
                    "flatPath": "youtube/v3/comments/markAsSpam",
                    "httpMethod": "POST",
                    "id": "youtube.comments.markAsSpam",
                    "path": "youtube/v3/comments/markAsSpam",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "setModerationStatus": {
                    "flatPath": "youtube/v3/comments/setModerationStatus",
                    "httpMethod": "POST",
                    "id": "youtube.comments.setModerationStatus",
                    "path": "youtube/v3/comments/setModerationStatus",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/comments",
                    "httpMethod": "PUT",
                    "id": "youtube.comments.update",
                    "path": "youtube/v3/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "guideCategories": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/guideCategories",
                    "httpMethod": "GET",
                    "id": "youtube.guideCategories.list",
                    "path": "youtube/v3/guideCategories",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "i18nLanguages": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/i18nLanguages",
                    "httpMethod": "GET",
                    "id": "youtube.i18nLanguages.list",
                    "path": "youtube/v3/i18nLanguages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "i18nRegions": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/i18nRegions",
                    "httpMethod": "GET",
                    "id": "youtube.i18nRegions.list",
                    "path": "youtube/v3/i18nRegions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "liveBroadcasts": {
            "methods": {
                "bind": {
                    "flatPath": "youtube/v3/liveBroadcasts/bind",
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.bind",
                    "path": "youtube/v3/liveBroadcasts/bind",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "control": {
                    "flatPath": "youtube/v3/liveBroadcasts/control",
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.control",
                    "path": "youtube/v3/liveBroadcasts/control",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "delete": {
                    "flatPath": "youtube/v3/liveBroadcasts",
                    "httpMethod": "DELETE",
                    "id": "youtube.liveBroadcasts.delete",
                    "path": "youtube/v3/liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/liveBroadcasts",
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.insert",
                    "path": "youtube/v3/liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/liveBroadcasts",
                    "httpMethod": "GET",
                    "id": "youtube.liveBroadcasts.list",
                    "path": "youtube/v3/liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                },
                "transition": {
                    "flatPath": "youtube/v3/liveBroadcasts/transition",
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.transition",
                    "path": "youtube/v3/liveBroadcasts/transition",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/liveBroadcasts",
                    "httpMethod": "PUT",
                    "id": "youtube.liveBroadcasts.update",
                    "path": "youtube/v3/liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "liveChatBans": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/liveChat/bans",
                    "httpMethod": "DELETE",
                    "id": "youtube.liveChatBans.delete",
                    "path": "youtube/v3/liveChat/bans",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/liveChat/bans",
                    "httpMethod": "POST",
                    "id": "youtube.liveChatBans.insert",
                    "path": "youtube/v3/liveChat/bans",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "liveChatMessages": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/liveChat/messages",
                    "httpMethod": "DELETE",
                    "id": "youtube.liveChatMessages.delete",
                    "path": "youtube/v3/liveChat/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/liveChat/messages",
                    "httpMethod": "POST",
                    "id": "youtube.liveChatMessages.insert",
                    "path": "youtube/v3/liveChat/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/liveChat/messages",
                    "httpMethod": "GET",
                    "id": "youtube.liveChatMessages.list",
                    "path": "youtube/v3/liveChat/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "liveChatModerators": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/liveChat/moderators",
                    "httpMethod": "DELETE",
                    "id": "youtube.liveChatModerators.delete",
                    "path": "youtube/v3/liveChat/moderators",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/liveChat/moderators",
                    "httpMethod": "POST",
                    "id": "youtube.liveChatModerators.insert",
                    "path": "youtube/v3/liveChat/moderators",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/liveChat/moderators",
                    "httpMethod": "GET",
                    "id": "youtube.liveChatModerators.list",
                    "path": "youtube/v3/liveChat/moderators",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "liveStreams": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/liveStreams",
                    "httpMethod": "DELETE",
                    "id": "youtube.liveStreams.delete",
                    "path": "youtube/v3/liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/liveStreams",
                    "httpMethod": "POST",
                    "id": "youtube.liveStreams.insert",
                    "path": "youtube/v3/liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/liveStreams",
                    "httpMethod": "GET",
                    "id": "youtube.liveStreams.list",
                    "path": "youtube/v3/liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/liveStreams",
                    "httpMethod": "PUT",
                    "id": "youtube.liveStreams.update",
                    "path": "youtube/v3/liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "members": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/members",
                    "httpMethod": "GET",
                    "id": "youtube.members.list",
                    "path": "youtube/v3/members",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.channel-memberships.creator",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "membershipsLevels": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/membershipsLevels",
                    "httpMethod": "GET",
                    "id": "youtube.membershipsLevels.list",
                    "path": "youtube/v3/membershipsLevels",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.channel-memberships.creator",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "playlistItems": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/playlistItems",
                    "httpMethod": "DELETE",
                    "id": "youtube.playlistItems.delete",
                    "path": "youtube/v3/playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/playlistItems",
                    "httpMethod": "POST",
                    "id": "youtube.playlistItems.insert",
                    "path": "youtube/v3/playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/playlistItems",
                    "httpMethod": "GET",
                    "id": "youtube.playlistItems.list",
                    "path": "youtube/v3/playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/playlistItems",
                    "httpMethod": "PUT",
                    "id": "youtube.playlistItems.update",
                    "path": "youtube/v3/playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "playlists": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/playlists",
                    "httpMethod": "DELETE",
                    "id": "youtube.playlists.delete",
                    "path": "youtube/v3/playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/playlists",
                    "httpMethod": "POST",
                    "id": "youtube.playlists.insert",
                    "path": "youtube/v3/playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/playlists",
                    "httpMethod": "GET",
                    "id": "youtube.playlists.list",
                    "path": "youtube/v3/playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/playlists",
                    "httpMethod": "PUT",
                    "id": "youtube.playlists.update",
                    "path": "youtube/v3/playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "search": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/search",
                    "httpMethod": "GET",
                    "id": "youtube.search.list",
                    "path": "youtube/v3/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "sponsors": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/sponsors",
                    "httpMethod": "GET",
                    "id": "youtube.sponsors.list",
                    "path": "youtube/v3/sponsors",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "subscriptions": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/subscriptions",
                    "httpMethod": "DELETE",
                    "id": "youtube.subscriptions.delete",
                    "path": "youtube/v3/subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/subscriptions",
                    "httpMethod": "POST",
                    "id": "youtube.subscriptions.insert",
                    "path": "youtube/v3/subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "flatPath": "youtube/v3/subscriptions",
                    "httpMethod": "GET",
                    "id": "youtube.subscriptions.list",
                    "path": "youtube/v3/subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "superChatEvents": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/superChatEvents",
                    "httpMethod": "GET",
                    "id": "youtube.superChatEvents.list",
                    "path": "youtube/v3/superChatEvents",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "tests": {
            "methods": {
                "insert": {
                    "flatPath": "youtube/v3/tests",
                    "httpMethod": "POST",
                    "id": "youtube.tests.insert",
                    "path": "youtube/v3/tests",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "thirdPartyLinks": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/thirdPartyLinks",
                    "httpMethod": "DELETE",
                    "id": "youtube.thirdPartyLinks.delete",
                    "path": "youtube/v3/thirdPartyLinks"
                },
                "insert": {
                    "flatPath": "youtube/v3/thirdPartyLinks",
                    "httpMethod": "POST",
                    "id": "youtube.thirdPartyLinks.insert",
                    "path": "youtube/v3/thirdPartyLinks"
                },
                "list": {
                    "flatPath": "youtube/v3/thirdPartyLinks",
                    "httpMethod": "GET",
                    "id": "youtube.thirdPartyLinks.list",
                    "path": "youtube/v3/thirdPartyLinks"
                },
                "update": {
                    "flatPath": "youtube/v3/thirdPartyLinks",
                    "httpMethod": "PUT",
                    "id": "youtube.thirdPartyLinks.update",
                    "path": "youtube/v3/thirdPartyLinks"
                }
            }
        },
        "thumbnails": {
            "methods": {
                "set": {
                    "flatPath": "youtube/v3/thumbnails/set",
                    "httpMethod": "POST",
                    "id": "youtube.thumbnails.set",
                    "path": "youtube/v3/thumbnails/set",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "videoAbuseReportReasons": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/videoAbuseReportReasons",
                    "httpMethod": "GET",
                    "id": "youtube.videoAbuseReportReasons.list",
                    "path": "youtube/v3/videoAbuseReportReasons",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "videoCategories": {
            "methods": {
                "list": {
                    "flatPath": "youtube/v3/videoCategories",
                    "httpMethod": "GET",
                    "id": "youtube.videoCategories.list",
                    "path": "youtube/v3/videoCategories",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "videos": {
            "methods": {
                "delete": {
                    "flatPath": "youtube/v3/videos",
                    "httpMethod": "DELETE",
                    "id": "youtube.videos.delete",
                    "path": "youtube/v3/videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "getRating": {
                    "flatPath": "youtube/v3/videos/getRating",
                    "httpMethod": "GET",
                    "id": "youtube.videos.getRating",
                    "path": "youtube/v3/videos/getRating",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "flatPath": "youtube/v3/videos",
                    "httpMethod": "POST",
                    "id": "youtube.videos.insert",
                    "path": "youtube/v3/videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                },
                "list": {
                    "flatPath": "youtube/v3/videos",
                    "httpMethod": "GET",
                    "id": "youtube.videos.list",
                    "path": "youtube/v3/videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "rate": {
                    "flatPath": "youtube/v3/videos/rate",
                    "httpMethod": "POST",
                    "id": "youtube.videos.rate",
                    "path": "youtube/v3/videos/rate",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "reportAbuse": {
                    "flatPath": "youtube/v3/videos/reportAbuse",
                    "httpMethod": "POST",
                    "id": "youtube.videos.reportAbuse",
                    "path": "youtube/v3/videos/reportAbuse",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "flatPath": "youtube/v3/videos",
                    "httpMethod": "PUT",
                    "id": "youtube.videos.update",
                    "path": "youtube/v3/videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "watermarks": {
            "methods": {
                "set": {
                    "flatPath": "youtube/v3/watermarks/set",
                    "httpMethod": "POST",
                    "id": "youtube.watermarks.set",
                    "path": "youtube/v3/watermarks/set",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                },
                "unset": {
                    "flatPath": "youtube/v3/watermarks/unset",
                    "httpMethod": "POST",
                    "id": "youtube.watermarks.unset",
                    "path": "youtube/v3/watermarks/unset",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "youtube": {
            "resources": {
                "v3": {
                    "methods": {
                        "infocards": {
                            "flatPath": "youtube/v3/infocards",
                            "httpMethod": "POST",
                            "id": "youtube.youtube.v3.infocards",
                            "path": "youtube/v3/infocards",
                            "scopes": [
                                "https://www.googleapis.com/auth/youtube",
                                "https://www.googleapis.com/auth/youtube.force-ssl",
                                "https://www.googleapis.com/auth/youtubepartner"
                            ]
                        }
                    },
                    "resources": {
                        "infocards": {
                            "methods": {
                                "list": {
                                    "flatPath": "youtube/v3/infocards",
                                    "httpMethod": "GET",
                                    "id": "youtube.youtube.v3.infocards.list",
                                    "path": "youtube/v3/infocards",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/youtube",
                                        "https://www.googleapis.com/auth/youtube.force-ssl",
                                        "https://www.googleapis.com/auth/youtubepartner"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "",
    "title": "YouTube Data API v3",
    "version": "v3"
}