{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/youtube": {},
                "https://www.googleapis.com/auth/youtube.readonly": {},
                "https://www.googleapis.com/auth/youtubepartner": {},
                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {},
                "https://www.googleapis.com/auth/yt-analytics.readonly": {}
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://youtubeanalytics.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "YouTube Analytics",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/youtube/analytics",
    "fullyEncodeReservedExpansion": true,
    "id": "youtubeAnalytics:v2",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
    "name": "youtubeAnalytics",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "groupItems": {
            "methods": {
                "delete": {
                    "flatPath": "v2/groupItems",
                    "httpMethod": "DELETE",
                    "id": "youtubeAnalytics.groupItems.delete",
                    "path": "v2/groupItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "insert": {
                    "flatPath": "v2/groupItems",
                    "httpMethod": "POST",
                    "id": "youtubeAnalytics.groupItems.insert",
                    "path": "v2/groupItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v2/groupItems",
                    "httpMethod": "GET",
                    "id": "youtubeAnalytics.groupItems.list",
                    "path": "v2/groupItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                }
            }
        },
        "groups": {
            "methods": {
                "delete": {
                    "flatPath": "v2/groups",
                    "httpMethod": "DELETE",
                    "id": "youtubeAnalytics.groups.delete",
                    "path": "v2/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "insert": {
                    "flatPath": "v2/groups",
                    "httpMethod": "POST",
                    "id": "youtubeAnalytics.groups.insert",
                    "path": "v2/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "list": {
                    "flatPath": "v2/groups",
                    "httpMethod": "GET",
                    "id": "youtubeAnalytics.groups.list",
                    "path": "v2/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                },
                "update": {
                    "flatPath": "v2/groups",
                    "httpMethod": "PUT",
                    "id": "youtubeAnalytics.groups.update",
                    "path": "v2/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                }
            }
        },
        "reports": {
            "methods": {
                "query": {
                    "flatPath": "v2/reports",
                    "httpMethod": "GET",
                    "id": "youtubeAnalytics.reports.query",
                    "path": "v2/reports",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                        "https://www.googleapis.com/auth/yt-analytics.readonly"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://youtubeanalytics.googleapis.com/",
    "servicePath": "",
    "title": "YouTube Analytics API",
    "version": "v2",
    "version_module": true
}