{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/youtube": {},
                "https://www.googleapis.com/auth/youtube.force-ssl": {},
                "https://www.googleapis.com/auth/youtube.readonly": {},
                "https://www.googleapis.com/auth/youtube.upload": {},
                "https://www.googleapis.com/auth/youtubepartner": {},
                "https://www.googleapis.com/auth/youtubepartner-channel-audit": {}
            }
        }
    },
    "basePath": "/youtube/v3/",
    "baseUrl": "https://www.googleapis.com/youtube/v3/",
    "batchPath": "batch/youtube/v3",
    "canonicalName": "YouTube",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/youtube/v3",
    "id": "youtube:v3",
    "kind": "discovery#restDescription",
    "name": "youtube",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "activities": {
            "methods": {
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.activities.insert",
                    "path": "activities",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.activities.list",
                    "path": "activities",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "captions": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.captions.delete",
                    "path": "captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "download": {
                    "httpMethod": "GET",
                    "id": "youtube.captions.download",
                    "path": "captions/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaDownload": true
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.captions.insert",
                    "path": "captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.captions.list",
                    "path": "captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.captions.update",
                    "path": "captions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "channelBanners": {
            "methods": {
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.channelBanners.insert",
                    "path": "channelBanners/insert",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "channelSections": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.channelSections.delete",
                    "path": "channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.channelSections.insert",
                    "path": "channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.channelSections.list",
                    "path": "channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.channelSections.update",
                    "path": "channelSections",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "channels": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.channels.list",
                    "path": "channels",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/youtubepartner-channel-audit"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.channels.update",
                    "path": "channels",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "commentThreads": {
            "methods": {
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.commentThreads.insert",
                    "path": "commentThreads",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.commentThreads.list",
                    "path": "commentThreads",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.commentThreads.update",
                    "path": "commentThreads",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.comments.delete",
                    "path": "comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.comments.insert",
                    "path": "comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.comments.list",
                    "path": "comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "markAsSpam": {
                    "httpMethod": "POST",
                    "id": "youtube.comments.markAsSpam",
                    "path": "comments/markAsSpam",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "setModerationStatus": {
                    "httpMethod": "POST",
                    "id": "youtube.comments.setModerationStatus",
                    "path": "comments/setModerationStatus",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.comments.update",
                    "path": "comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "guideCategories": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.guideCategories.list",
                    "path": "guideCategories",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "i18nLanguages": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.i18nLanguages.list",
                    "path": "i18nLanguages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "i18nRegions": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.i18nRegions.list",
                    "path": "i18nRegions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "liveBroadcasts": {
            "methods": {
                "bind": {
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.bind",
                    "path": "liveBroadcasts/bind",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "control": {
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.control",
                    "path": "liveBroadcasts/control",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.liveBroadcasts.delete",
                    "path": "liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.insert",
                    "path": "liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.liveBroadcasts.list",
                    "path": "liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                },
                "transition": {
                    "httpMethod": "POST",
                    "id": "youtube.liveBroadcasts.transition",
                    "path": "liveBroadcasts/transition",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.liveBroadcasts.update",
                    "path": "liveBroadcasts",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "liveChatBans": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.liveChatBans.delete",
                    "path": "liveChat/bans",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.liveChatBans.insert",
                    "path": "liveChat/bans",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "liveChatMessages": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.liveChatMessages.delete",
                    "path": "liveChat/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.liveChatMessages.insert",
                    "path": "liveChat/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.liveChatMessages.list",
                    "path": "liveChat/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "liveChatModerators": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.liveChatModerators.delete",
                    "path": "liveChat/moderators",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.liveChatModerators.insert",
                    "path": "liveChat/moderators",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.liveChatModerators.list",
                    "path": "liveChat/moderators",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "liveStreams": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.liveStreams.delete",
                    "path": "liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.liveStreams.insert",
                    "path": "liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.liveStreams.list",
                    "path": "liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.liveStreams.update",
                    "path": "liveStreams",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ]
                }
            }
        },
        "members": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.members.list",
                    "path": "members",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "membershipsLevels": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.membershipsLevels.list",
                    "path": "membershipsLevels",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "playlistItems": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.playlistItems.delete",
                    "path": "playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.playlistItems.insert",
                    "path": "playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.playlistItems.list",
                    "path": "playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsSubscription": true
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.playlistItems.update",
                    "path": "playlistItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "playlists": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.playlists.delete",
                    "path": "playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.playlists.insert",
                    "path": "playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.playlists.list",
                    "path": "playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.playlists.update",
                    "path": "playlists",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "search": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.search.list",
                    "path": "search",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "sponsors": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.sponsors.list",
                    "path": "sponsors",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "subscriptions": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.subscriptions.delete",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.subscriptions.insert",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.subscriptions.list",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "superChatEvents": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.superChatEvents.list",
                    "path": "superChatEvents",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "thumbnails": {
            "methods": {
                "set": {
                    "httpMethod": "POST",
                    "id": "youtube.thumbnails.set",
                    "path": "thumbnails/set",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "videoAbuseReportReasons": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.videoAbuseReportReasons.list",
                    "path": "videoAbuseReportReasons",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ]
                }
            }
        },
        "videoCategories": {
            "methods": {
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.videoCategories.list",
                    "path": "videoCategories",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "videos": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "youtube.videos.delete",
                    "path": "videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "getRating": {
                    "httpMethod": "GET",
                    "id": "youtube.videos.getRating",
                    "path": "videos/getRating",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "youtube.videos.insert",
                    "path": "videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                },
                "list": {
                    "httpMethod": "GET",
                    "id": "youtube.videos.list",
                    "path": "videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "rate": {
                    "httpMethod": "POST",
                    "id": "youtube.videos.rate",
                    "path": "videos/rate",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "reportAbuse": {
                    "httpMethod": "POST",
                    "id": "youtube.videos.reportAbuse",
                    "path": "videos/reportAbuse",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                },
                "update": {
                    "httpMethod": "PUT",
                    "id": "youtube.videos.update",
                    "path": "videos",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        },
        "watermarks": {
            "methods": {
                "set": {
                    "httpMethod": "POST",
                    "id": "youtube.watermarks.set",
                    "path": "watermarks/set",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "supportsMediaUpload": true
                },
                "unset": {
                    "httpMethod": "POST",
                    "id": "youtube.watermarks.unset",
                    "path": "watermarks/unset",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ]
                }
            }
        }
    },
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "youtube/v3/",
    "title": "YouTube Data API",
    "version": "v3"
}